#!/usr/bin/env tsx
/**
 * T2.12 (PLAN-ci-time-budget). The dependency probe's own analysis step.
 *
 * `ct-e2e-probe.yml` runs every E2E Workers spec file ALONE, on a fresh VM
 * (one matrix leg per file), and uploads one small `{file, outcome}` JSON per
 * leg. This script reads all of them and proposes `needs` edges, in the exact
 * shape `unit-enumerators.ts`'s `Unit.needs?: string[]` and `shardPlan`
 * (`lanes.ts`) already consume: a file that FAILS alone but is part of the
 * committed, currently-green `test-e2e-workers` shard plan needs its
 * immediate predecessor in suite order (numeric filename prefix, the same
 * order `playwright.config.ts`'s `test-NN` projects enforce via
 * `workers: 1` + `fullyParallel: false`).
 *
 * IT NEVER EDITS THE MANIFEST. `.ci/config/shards/test-e2e-workers.json` is
 * generated by `gate-bind --write` from `shardPlan`, and this script has no
 * business hand-writing it -- it only PRINTS the proposed edges (to stdout,
 * as JSON) for a human, or a future `unit-enumerators.ts` change, to apply.
 *
 * ONE EDGE PER FAILURE, TO THE IMMEDIATE PREDECESSOR ONLY. The probe's
 * signal is binary (alone vs. the full suite, which is assumed green -- a
 * file that failed inside the full suite would already have reddened
 * ordinary CI and never reach this probe), so it cannot itself distinguish
 * "needs the file right before it" from "needs some earlier file". Naming
 * the nearest predecessor is the smallest true claim the data supports; a
 * wider dependency shows up as that predecessor ALSO failing alone, which a
 * repeat probe run after the first edge is applied would catch. A failure
 * with no predecessor at all (the very first file in order) is not an
 * ordering dependency -- it is reported separately as `unexplained`, not as
 * an edge to nothing.
 *
 * Usage:
 *   npx tsx scripts/ci-runner/e2e-probe-edges.ts --results-dir <dir>
 *   npx tsx scripts/ci-runner/e2e-probe-edges.ts --selftest
 */

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

export interface ProbeResult {
  /** Spec file basename, e.g. "03-datastore-lifecycle.test.ts" -- matches unit-enumerators.ts's e2eWorkersUnits() id tail. */
  file: string;
  outcome: 'pass' | 'fail';
}

export interface ProposedEdge {
  /** e2e-workers unit id, exactly as unit-enumerators.ts's e2eWorkersUnits() and the shard manifest name it. */
  id: string;
  needs: string[];
}

export interface ProbeEdgesReport {
  probed: number;
  /** Every file that failed run alone, in suite order. */
  failedAlone: string[];
  /** The proposed `needs` edges, one per failedAlone entry that has a predecessor. */
  edges: ProposedEdge[];
  /** failedAlone entries with no predecessor to blame -- a real bug, not an ordering gap. */
  unexplained: string[];
}

const UNIT_PREFIX = 'e2e-workers:';

/**
 * Suite order is the plain lexicographic sort of the probed file names. Every
 * `NN-*.test.ts` file in this repo carries a zero-padded two-digit prefix
 * (01..26), so a string sort agrees with playwright.config.ts's numeric
 * `test-NN` project order -- verified against the committed file list
 * (packages/e2e-tests/tests/*.test.ts) rather than assumed.
 */
export function computeEdges(results: readonly ProbeResult[]): ProbeEdgesReport {
  if (results.length === 0) {
    throw new Error('VACUOUS: computeEdges received zero probe results.');
  }
  const order = [...results].map((r) => r.file).sort();
  const outcomeByFile = new Map(results.map((r) => [r.file, r.outcome]));

  const failedAlone: string[] = [];
  const edges: ProposedEdge[] = [];
  const unexplained: string[] = [];

  for (let i = 0; i < order.length; i++) {
    const file = order[i] as string;
    if (outcomeByFile.get(file) !== 'fail') continue;
    failedAlone.push(file);
    const predecessor = i > 0 ? order[i - 1] : undefined;
    if (predecessor === undefined) {
      unexplained.push(file);
    } else {
      edges.push({ id: `${UNIT_PREFIX}${file}`, needs: [`${UNIT_PREFIX}${predecessor}`] });
    }
  }

  return { probed: results.length, failedAlone, edges, unexplained };
}

function collectJsonFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...collectJsonFiles(full));
    else if (entry.isFile() && entry.name.endsWith('.json')) out.push(full);
  }
  return out;
}

/**
 * Reads every leg's uploaded `{file, outcome}` JSON out of a directory tree
 * (a plain `actions/download-artifact` with a `pattern:` and no
 * `merge-multiple` lands one subdirectory per artifact, so this walks
 * recursively rather than assuming a flat layout).
 */
export function parseResultsDir(dir: string): ProbeResult[] {
  const files = collectJsonFiles(dir);
  const results: ProbeResult[] = [];
  const seenAt = new Map<string, string>();

  for (const f of files) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(fs.readFileSync(f, 'utf-8'));
    } catch (err) {
      throw new Error(
        `e2e-probe-edges: ${f} is not valid JSON: ${err instanceof Error ? err.message : String(err)}`
      );
    }
    if (parsed === null || typeof parsed !== 'object') {
      throw new Error(`e2e-probe-edges: ${f} must hold a JSON object.`);
    }
    const { file, outcome } = parsed as { file?: unknown; outcome?: unknown };
    if (typeof file !== 'string' || file === '') {
      throw new Error(`e2e-probe-edges: ${f} is missing a non-empty string "file".`);
    }
    if (outcome !== 'pass' && outcome !== 'fail') {
      throw new Error(
        `e2e-probe-edges: ${f} has outcome ${JSON.stringify(outcome)}; must be "pass" or "fail".`
      );
    }
    const already = seenAt.get(file);
    if (already !== undefined) {
      throw new Error(`e2e-probe-edges: file "${file}" was reported twice (${already} and ${f}).`);
    }
    seenAt.set(file, f);
    results.push({ file, outcome });
  }

  if (results.length === 0) {
    throw new Error(`VACUOUS: e2e-probe-edges: ${dir} holds no leg result JSON file.`);
  }
  return results;
}

function printSummary(report: ProbeEdgesReport): void {
  process.stderr.write(
    `e2e-probe-edges: ${report.probed} file(s) probed, ${report.failedAlone.length} failed alone, ` +
      `${report.edges.length} proposed edge(s), ${report.unexplained.length} unexplained.\n`
  );
  for (const edge of report.edges) {
    process.stderr.write(`  needs edge: ${edge.id} needs ${edge.needs.join(', ')}\n`);
  }
  for (const file of report.unexplained) {
    process.stderr.write(
      `  UNEXPLAINED: ${UNIT_PREFIX}${file} failed alone with no predecessor in suite order -- ` +
        'this is a real bug, not an ordering gap; a needs edge cannot be proposed for it.\n'
    );
  }
}

function require_(cond: boolean, message: string, failures: string[]): void {
  if (!cond) failures.push(message);
}

function selftest(): number {
  const failures: string[] = [];

  // CONTROL: 03 fails alone; its immediate predecessor (02) is available, so one edge is proposed, pointing only at the immediate predecessor.
  const control = computeEdges([
    { file: '01-system-checks.test.ts', outcome: 'pass' },
    { file: '02-machine-setup.test.ts', outcome: 'pass' },
    { file: '03-datastore-lifecycle.test.ts', outcome: 'fail' },
    { file: '04-repository-lifecycle.test.ts', outcome: 'pass' },
  ]);
  require_(
    control.failedAlone.length === 1,
    `control: expected 1 failedAlone, got ${control.failedAlone.length}`,
    failures
  );
  require_(
    control.edges.length === 1,
    `control: expected 1 edge, got ${control.edges.length}`,
    failures
  );
  require_(
    control.edges[0]?.id === 'e2e-workers:03-datastore-lifecycle.test.ts',
    `control: edge id was ${String(control.edges[0]?.id)}`,
    failures
  );
  require_(
    JSON.stringify(control.edges[0]?.needs) ===
      JSON.stringify(['e2e-workers:02-machine-setup.test.ts']),
    `control: needs was ${JSON.stringify(control.edges[0]?.needs)}`,
    failures
  );
  require_(control.unexplained.length === 0, 'control: unexpected unexplained entry', failures);

  // INVERSE: everything passes alone -- zero failures, zero edges.
  const inverse = computeEdges([
    { file: '01-system-checks.test.ts', outcome: 'pass' },
    { file: '02-machine-setup.test.ts', outcome: 'pass' },
    { file: '03-datastore-lifecycle.test.ts', outcome: 'pass' },
  ]);
  require_(
    inverse.failedAlone.length === 0,
    `inverse: expected 0 failedAlone, got ${inverse.failedAlone.length}`,
    failures
  );
  require_(
    inverse.edges.length === 0,
    `inverse: expected 0 edges, got ${inverse.edges.length}`,
    failures
  );
  require_(
    inverse.unexplained.length === 0,
    `inverse: expected 0 unexplained, got ${inverse.unexplained.length}`,
    failures
  );

  // NO PREDECESSOR: the very first file in suite order fails alone. That is not an ordering dependency (nothing precedes it), so it must land in `unexplained`, never as an edge to a nonexistent unit.
  const noPredecessor = computeEdges([
    { file: '01-system-checks.test.ts', outcome: 'fail' },
    { file: '02-machine-setup.test.ts', outcome: 'pass' },
  ]);
  require_(
    noPredecessor.edges.length === 0,
    `no-predecessor: expected 0 edges, got ${noPredecessor.edges.length}`,
    failures
  );
  require_(
    JSON.stringify(noPredecessor.unexplained) === JSON.stringify(['01-system-checks.test.ts']),
    `no-predecessor: unexplained was ${JSON.stringify(noPredecessor.unexplained)}`,
    failures
  );

  // CONSECUTIVE FAILURES: each gets an edge to its OWN immediate predecessor in suite order, not merged or chained past it.
  const consecutive = computeEdges([
    { file: '01-system-checks.test.ts', outcome: 'pass' },
    { file: '02-machine-setup.test.ts', outcome: 'fail' },
    { file: '03-datastore-lifecycle.test.ts', outcome: 'fail' },
  ]);
  require_(
    consecutive.edges.length === 2,
    `consecutive: expected 2 edges, got ${consecutive.edges.length}`,
    failures
  );
  require_(
    consecutive.edges[0]?.needs[0] === 'e2e-workers:01-system-checks.test.ts',
    'consecutive: first edge must point at its own immediate predecessor',
    failures
  );
  require_(
    consecutive.edges[1]?.needs[0] === 'e2e-workers:02-machine-setup.test.ts',
    'consecutive: second edge must point at its own immediate predecessor, not skip over it',
    failures
  );

  // VACUOUS INPUT refuses rather than reporting a silent "all clear".
  let threw = false;
  try {
    computeEdges([]);
  } catch {
    threw = true;
  }
  require_(threw, 'computeEdges([]) must throw rather than report zero findings', failures);

  if (failures.length > 0) {
    for (const message of failures) process.stderr.write(`FAIL: ${message}\n`);
    return 1;
  }
  process.stderr.write(
    'OK: e2e-probe-edges selftest passed (control, inverse, no-predecessor, consecutive, vacuous)\n'
  );
  return 0;
}

function main(): number {
  const argv = process.argv.slice(2);
  if (argv.includes('--selftest')) return selftest();

  const dirFlagAt = argv.indexOf('--results-dir');
  const dir = dirFlagAt >= 0 ? argv[dirFlagAt + 1] : undefined;
  if (dir === undefined) {
    process.stderr.write('usage: e2e-probe-edges.ts --results-dir <dir> | --selftest\n');
    return 1;
  }
  if (!fs.existsSync(dir)) {
    process.stderr.write(`e2e-probe-edges: ${dir} does not exist.\n`);
    return 1;
  }

  const results = parseResultsDir(dir);
  const report = computeEdges(results);
  // JSON on stdout only, so a caller can pipe this straight into a committed file or an artifact upload without the human summary interleaved.
  process.stdout.write(`${JSON.stringify(report, null, 2)}\n`);
  printSummary(report);
  // Always exits 0: a proposed edge is a finding for a human to apply, not a gate. The workflow that calls this never fails the run on its output.
  return 0;
}

process.exitCode = main();
