"""The `env-manifest` gen-docs region, re-derived in Python and compared both ways.

WHY A SECOND READING, WHEN `check:ci-doc-region-parity` ALREADY COMPARES THE BYTES.

That gate re-renders the region from the SAME TypeScript provider that wrote it, so the two sides of its comparison share every assumption. It answers "has a human hand-edited the region", which is the question it was built for, and it cannot answer "does the region say what the manifest says": a provider that dropped the tombstone shard on the floor would render a smaller table,
and the gate would re-render the same smaller table and call it a match.

So this module reads `.ci/config/env-manifest.json` itself, in a different language, with no import from the emitter, and asserts the committed region against that. Two independent readings of one file is the only shape in which a wrong answer has to be wrong twice.

WHAT IT ASSERTS WHEN THERE IS NO REGION YET, WHICH IS NOT NOTHING.

The emitter (`scripts/lib/doc-providers.ts`) and its region (`scripts/data/doc-registry.md`) are single-writer files during the tooling transformation, so this file can land before, with, or after them. It therefore splits its clauses:

  * the CONTRACT clauses run unconditionally against the manifest. They are the
    same refusals the provider makes -- shard key parity, a per-shard floor,
    pairwise disjointness, no annotation about an unclassified name -- restated
    here so the manifest is held to them even on a tree with no region at all.
  * the REGION clauses run when the provider is declared. If it IS declared and the
    region is missing, that is a hard failure and not a skip: it is exactly
    invariant 1 (emitter and parity land together) failing open.
  * a region present with no provider declaring it is equally a failure. The
    generator errors on such a region, so a green here with one present would mean
    this module had stopped looking.

There is no state in which every clause is skipped, which is the property that keeps a conditional test from becoming a decoration.

NO COUNT IS WRITTEN DOWN ANYWHERE IN THIS FILE. Every total is derived and printed, never compared against a literal, because the manifest moved by tens of names in a single day while it was being built. A floor typed here would be a second thing to update and the first thing to go stale. The floors that ARE here are structural: "more than zero", "every shard more than zero", "the
footer equals the rows".
"""

import json
import re

from rediacc_ci import paths

ROOT = paths.repo_root()

MANIFEST_REL = ".ci/config/env-manifest.json"
REGISTRY_REL = "scripts/data/doc-registry.md"
PROVIDERS_REL = "scripts/lib/doc-providers.ts"
REGION_ID = "env-manifest"

OPEN_MARKER = "<!-- >>> gen-docs: %s -->" % REGION_ID
CLOSE_MARKER = "<!-- <<< gen-docs -->"

# The provider's own id line, which is how "the emitter has landed" is decided. A grep for the word `env-manifest` would also match the manifest's own path in a comment, and a comment is not a declaration.
PROVIDER_ID_RE = re.compile(r"""^\s*id:\s*['"]%s['"],?\s*$""" % re.escape(REGION_ID), re.MULTILINE)

FOOTER_RE = re.compile(
    r"^(\d+) row\(s\)\. Generated by `npx tsx scripts/gen-docs\.ts --write`; do not hand-edit\.$"
)


def read(rel: str) -> str:
    path = ROOT / rel
    if not path.is_file():
        # A missing input is never a pass. Naming the path and the root matters because this module is routinely pointed at a fixture tree.
        msg = "%s does not exist under %s, so nothing below could be checked" % (rel, ROOT)
        raise AssertionError(msg)
    return path.read_text(encoding="utf-8")


def load_manifest(text: str) -> dict:
    return json.loads(text)


def shard_of(manifest: dict) -> dict[str, str]:
    """name -> shard, over every populated shard. Duplicates are the caller's problem."""
    out: dict[str, str] = {}
    for shard, names in manifest.get("shards", {}).items():
        for name in names:
            out.setdefault(name, shard)
    return out


def contract_findings(manifest: dict) -> list[str]:
    """The refusals the emitter makes, restated against the data itself.

    Each one is a way the region could shrink while every byte of it still matched what the provider would emit, which is precisely the class the byte-comparison gate cannot see.
    """
    findings: list[str] = []
    defs = manifest.get("shard_definitions")
    shards = manifest.get("shards")
    if not isinstance(defs, dict) or not isinstance(shards, dict):
        return ["shard_definitions or shards is missing or is not an object"]
    declared, populated = set(defs), set(shards)
    findings.extend(
        "shard %s is defined and holds no list of names" % s for s in sorted(declared - populated)
    )
    findings.extend(
        "shard %s holds names and is defined nowhere" % s for s in sorted(populated - declared)
    )
    if not declared:
        findings.append("the manifest declares no shard at all")
    seen: dict[str, str] = {}
    for shard in sorted(populated):
        names = shards[shard]
        if not isinstance(names, list) or any(not isinstance(n, str) or not n for n in names):
            findings.append("shard %s is not a list of non-empty names" % shard)
            continue
        if not names:
            findings.append(
                "shard %s holds zero names; a total floor cannot see one shard empty out" % shard
            )
        for name in names:
            if name in seen:
                findings.append("%s is in both the %s and %s shards" % (name, seen[name], shard))
            else:
                seen[name] = shard
    findings.extend(
        "collisions names %r, which is in no shard" % c.get("name")
        for c in manifest.get("collisions", [])
        if c.get("name") not in seen
    )
    findings.extend(
        "notes names %r, which is in no shard" % n
        for n in manifest.get("notes", {})
        if n not in seen
    )
    findings.extend(
        "tombstone_proof_sites/%s names %r, which is in no shard" % (site, n)
        for site, names in manifest.get("tombstone_proof_sites", {}).items()
        for n in names
        if n not in seen
    )
    return findings


def cell(value: str) -> str:
    """The emitter's escaping: `|` ends a cell and a newline ends the row."""
    return re.sub(r"[\r\n]+", " ", value.replace("|", "\\|"))


def expected_rows(manifest: dict) -> list[tuple[str, str, str]]:
    """(rendered variable, shard, residue) per name, in the order the region must hold.

    Sorted by the NAME in code point order. The emitter sorts by UTF-16 code unit, which differs from this only for characters outside the basic plane; an environment variable name outside it would be a finding of its own, and the row comparison below would report the disagreement rather than hide it.
    """
    collisions = {c["name"]: c for c in manifest.get("collisions", []) if "name" in c}
    notes = manifest.get("notes", {})
    proofs: dict[str, list[str]] = {}
    for site, names in manifest.get("tombstone_proof_sites", {}).items():
        for name in names:
            proofs.setdefault(name, []).append(site)
    rows: list[tuple[str, str, str, str]] = []
    for name, shard in shard_of(manifest).items():
        also: list[str] = []
        collision = collisions.get(name)
        if collision is not None:
            also.append(
                "collision: dead in %s, live in %s" % (collision["dead_in"], collision["live_in"])
            )
        if name in notes:
            also.append("note")
        sites = proofs.get(name)
        if sites is not None:
            also.append("tombstone proof: %s" % ", ".join("`%s`" % s for s in sorted(sites)))
        rows.append(
            (name, cell("`%s`" % name), cell(shard), cell("; ".join(also) if also else "-"))
        )
    # SORTED ON THE RAW NAME, NEVER ON THE RENDERED CELL, and the difference is not theoretical: the first draft sorted the backticked form and disagreed with the region at `AWS_SES_ACCESS_KEY_ID` against `AWS_SES_ACCESS_KEY_ID_ASIA`. A closing backtick is 0x60 and an underscore is 0x5F, so wrapping the value reverses the order of a name and any name that extends it. The emitter
    # sorts on its row KEY, so this must too.
    return [r[1:] for r in sorted(rows, key=lambda r: r[0])]


def region_body(doc: str) -> list[str] | None:
    """The lines strictly between the region's markers, or None if there is no region."""
    lines = doc.split("\n")
    try:
        start = lines.index(OPEN_MARKER)
    except ValueError:
        return None
    for index in range(start + 1, len(lines)):
        if lines[index] == CLOSE_MARKER:
            return lines[start + 1 : index]
    msg = "%s carries the %s opening marker and no closing marker" % (REGISTRY_REL, REGION_ID)
    raise AssertionError(msg)


# A cell boundary is an UNESCAPED pipe. The emitter escapes a `|` inside a value as `\|` precisely so it cannot end a cell, and splitting on the bare character would shift every column after the first value that ever contains one.
CELL_SPLIT_RE = re.compile(r"(?<!\\)\|")


def parse_rows(body: list[str]) -> list[tuple[str, ...]]:
    """Every row of the region's one table, cells stripped, the separator dropped.

    The separator row is `|---|---|---|`, and it survived a first version of this
    function that split on `" | "` -- it came back as a SINGLE cell reading
    `---|---|---` and was reported as a row naming no variable. The failure was loud rather than silent, which is the only reason it cost a minute.
    """
    rows: list[tuple[str, ...]] = []
    for line in body:
        if not line.startswith("|") or not line.endswith("|"):
            continue
        cells = tuple(c.strip() for c in CELL_SPLIT_RE.split(line[1:-1]))
        if all(c and set(c) <= {"-"} for c in cells):
            continue
        rows.append(cells)
    return rows


def test_the_manifest_holds_the_contract_the_region_is_rendered_from():
    manifest = load_manifest(read(MANIFEST_REL))
    findings = contract_findings(manifest)
    assert findings == [], "%s violates the contract this region is rendered from:\n  %s" % (
        MANIFEST_REL,
        "\n  ".join(findings),
    )
    shards = manifest["shards"]
    total = sum(len(v) for v in shards.values())
    assert total > 0, "%s classifies zero variables; a green over it would mean nothing" % (
        MANIFEST_REL
    )
    print(
        "manifest: %d name(s) over %d shard(s) [%s]"
        % (
            total,
            len(shards),
            ", ".join("%s %d" % (k, len(shards[k])) for k in sorted(shards)),
        )
    )


def test_the_control_fires_on_every_contract_clause():
    """Both directions. A checker with no negative control flags the whole tree.

    Each perturbation is applied to a COPY of the real manifest, so the clause is proved against the shape the repository actually has rather than against a toy.
    """
    base = load_manifest(read(MANIFEST_REL))
    assert contract_findings(base) == [], "the unperturbed manifest must be clean"

    a_shard = min(base["shards"])
    a_name = min(base["shards"][a_shard])
    other = min(set(base["shards"]) - {a_shard})

    plants: list[tuple[str, dict, str]] = []

    emptied = json.loads(json.dumps(base))
    emptied["shards"][a_shard] = []
    plants.append(("an emptied shard", emptied, "holds zero names"))

    duplicated = json.loads(json.dumps(base))
    duplicated["shards"][other].append(a_name)
    plants.append(("one name in two shards", duplicated, "is in both the"))

    undeclared = json.loads(json.dumps(base))
    del undeclared["shard_definitions"][a_shard]
    plants.append(("a shard defined nowhere", undeclared, "is defined nowhere"))

    dangling = json.loads(json.dumps(base))
    dangling["notes"]["A_NAME_IN_NO_SHARD"] = "planted"
    plants.append(("a note about an unclassified name", dangling, "which is in no shard"))

    for label, perturbed, needle in plants:
        findings = contract_findings(perturbed)
        assert findings, "the control did not fire: %s" % label
        assert any(needle in f for f in findings), "%s fired with the wrong message: %s" % (
            label,
            findings,
        )
        print("control fired: %-36s -> %s" % (label, findings[0]))


def test_emitter_and_region_are_wired_together_or_neither_is():
    """Invariant 1, checked in both directions rather than assumed."""
    declared = PROVIDER_ID_RE.search(read(PROVIDERS_REL)) is not None
    present = region_body(read(REGISTRY_REL)) is not None
    if declared and not present:
        msg = (
            "%s declares the %s provider and %s carries no region for it. gen-docs would "
            "then never render it and check:ci-doc-region-parity reds on an unused provider: "
            "the emitter and its region land in the SAME change."
        ) % (PROVIDERS_REL, REGION_ID, REGISTRY_REL)
        raise AssertionError(msg)
    if present and not declared:
        msg = (
            "%s carries a %s region and no provider declares that id, so the generator "
            "cannot render it and the table between the markers is hand-typed."
        ) % (REGISTRY_REL, REGION_ID)
        raise AssertionError(msg)
    print("emitter declared: %s; region present: %s" % (declared, present))


def test_the_region_says_exactly_what_the_manifest_says():
    """Set, order, cells and footer, against a reading that never touches the emitter."""
    body = region_body(read(REGISTRY_REL))
    if body is None:
        # Not a silent pass: the clause above owns the "should it be here" question, and it fails when the emitter is declared. Here there is nothing to compare.
        print(
            "no %s region in %s yet; the wiring clause owns that case" % (REGION_ID, REGISTRY_REL)
        )
        return
    # NAMES ONLY, AND CHECKED FIRST. `KEY=value` is what an environment file looks
    # like, and no line of this region may look like one: the table is a map of the seams, not a copy of the values. It runs ahead of the row comparison so that a leaked value is reported AS a leaked value, rather than as whichever set or order clause the same edit happens to trip on the way past.
    assignments = [line for line in body if re.search(r"`[A-Z][A-Z0-9_]*=", line)]
    assert not assignments, "the region carries something shaped like a VALUE: %s" % assignments[:3]

    manifest = load_manifest(read(MANIFEST_REL))
    expected = expected_rows(manifest)
    assert expected, "the manifest yields no row, so a matching region would be an empty table"

    rows = parse_rows(body)
    header, data = rows[0], rows[1:]
    assert header == ("Variable", "Shard", "Also recorded"), "unexpected columns: %s" % (header,)

    want_names = [r[0] for r in expected]
    got_names = [r[0] for r in data]
    missing = sorted(set(want_names) - set(got_names))
    extra = sorted(set(got_names) - set(want_names))
    assert not missing, "%d variable(s) in the manifest and not in the region: %s" % (
        len(missing),
        ", ".join(missing[:20]),
    )
    assert not extra, "%d row(s) in the region naming no classified variable: %s" % (
        len(extra),
        ", ".join(extra[:20]),
    )
    assert got_names == want_names, (
        "the region holds the right variables in the wrong ORDER; order is generator-owned, "
        "so this is a provider sort change or a hand reordering, not a content edit"
    )
    wrong = [
        "%s: region says (%s, %s), manifest says (%s, %s)" % (w[0], g[1], g[2], w[1], w[2])
        for w, g in zip(expected, data, strict=True)
        if w != g
    ]
    assert not wrong, "%d row(s) disagree with the manifest:\n  %s" % (
        len(wrong),
        "\n  ".join(wrong[:20]),
    )

    scans = [line for line in body if line.startswith("Scans: ")]
    assert len(scans) == 1, "the region must carry exactly one Scans line, found %d" % len(scans)
    assert MANIFEST_REL in scans[0], (
        "the Scans line does not name %s, so a reader cannot tell " % (MANIFEST_REL)
        + "which file the table is a projection of"
    )

    footers = [FOOTER_RE.match(line) for line in body]
    matched = [m for m in footers if m is not None]
    assert len(matched) == 1, "the region must carry exactly one row-count footer"
    assert int(matched[0].group(1)) == len(data), (
        "the footer claims %s row(s) and the table holds %d; a truncated region whose footer "
        "still matched would read as a smaller estate"
    ) % (matched[0].group(1), len(data))

    print(
        "region: %d row(s), %d shard(s) named, %d carrying residue"
        % (len(data), len({r[1] for r in data}), sum(1 for r in data if r[2] != "-"))
    )
