"""Differential: `rediacc_ci.pr.sync_epic_block` against its twin `.ci/scripts/pr/sync-epic-block.sh`.

A DISPOSABLE LOCAL GIT REPO (never GitHub), on the strategy the retired `test_review_epic_context.py` used: real commits, an `agent/pr/<branch>.md` snapshot the twin reads by convention, `git rev-parse --show-toplevel` resolving the fixture root rather than this checkout's.

A RECORDING FAKE `gh`, written as Python per ruling 7, seam is PATH. The seam matters here for a reason `ci-stop-elite`'s fake docker also proved: `gh pr edit` is NOT stdout/stderr-redirected by either subject, so a fake that stays silent on success would hide a port that swallowed that pass-through -- `test_gh_edit_stdout_is_not_swallowed` exists to catch exactly that class, after
it was confirmed present in a first draft of the port (both `stdout`
and `stderr` were passed `capture_output=True` for the edit call, silently
eating gh's own URL line; fixed to inherit both, matching the twin).

K=5 LEDGER: `.ci/shadow/w7p6-sync-epic-block.observations.jsonl`.
"""

from __future__ import annotations

import importlib
import os
import pathlib
import subprocess
import tempfile

from rediacc_ci import paths
from rediacc_ci.core import gh_retry, ghx

ROOT = paths.repo_root()
# The shipped `.ci/scripts/pr/sync-epic-block.sh` is a thin `exec` of the port (its one-shot `gh pr view` read was the PLAN-gh-retry class), so it cannot be this differential's oracle: comparing it to the port would compare the port with itself. The bash body it replaced is kept HERE, verbatim, and written into each case's tmp dir. Not a tracked `.sh`, because the language policy baseline refuses a new bash path.
SHIPPED = ROOT / ".ci" / "scripts" / "pr" / "sync-epic-block.sh"
TWIN_NAME = "sync-epic-block.sh"
TWIN_BODY = r"""#!/usr/bin/env bash
# Sync the worklist epic block into a PR description.
#
# Reads the published snapshot (agent/pr/<branch>.md, written by
# `worklist.py --publish`) and rebuilds a delimited block in the PR body. The
# store itself lives in TMPDIR and is unreadable from CI, which is exactly why
# the snapshot exists.
#
# THE MARKER PAIR IS DISTINCT ON PURPOSE. Three writers already append a block
# at the end of this repo's PR bodies: refresh-pr-body.sh's `pushed-head`,
# submodule-prs.sh's `autopilot-submodule-prs`, and whatever a human typed.
# submodule-prs.sh warns in its own header that sharing markers with
# refresh-pr-body.sh is fatal, because that hook rewrites the WHOLE body on every
# push and anything inside its markers is destroyed on the next one. Each writer
# strips only its own markers, so all three survive; the price is that block
# ORDER flips depending on who ran last, and nothing may depend on position.
#
# Idiom copied verbatim from .ci/scripts/autopilot/submodule-prs.sh: exact-line
# equality on the markers (not a substring match), `next` on both so the markers
# themselves are dropped, and the block REBUILT rather than appended to.
set -euo pipefail

BEGIN='<!-- worklist-epics:begin -->'
END='<!-- worklist-epics:end -->'

usage() {
    cat >&2 <<'MSG'
usage: sync-epic-block.sh <pr-number> <branch> [--dry-run]

Rebuilds the worklist epic block in a PR description from
agent/pr/<branch>.md. With --dry-run the new body goes to stdout and
nothing is written.
MSG
    exit 2
}

[[ $# -lt 2 ]] && usage
PR="$1"
BRANCH="$2"
DRY="${3:-}"
REPO_ROOT="$(git rev-parse --show-toplevel)"
SNAP="$REPO_ROOT/agent/pr/${BRANCH//\//-}.md"

if [[ ! -f "$SNAP" ]]; then
    echo "✗ no snapshot at ${SNAP#"$REPO_ROOT"/}" >&2
    echo "  run: worklist.py --publish <me> $BRANCH" >&2
    exit 1
fi

# The snapshot's own generated header is for readers of the file, not the PR.
SECTION="$(sed '1{/^<!-- generated by worklist.py/d;}; /^# Work in /d' "$SNAP")"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

if [[ "$DRY" == "--dry-run" ]]; then
    : >"$work/body-old.md"
else
    gh pr view "$PR" --json body --jq '.body // ""' >"$work/body-old.md"
fi

awk -v b="$BEGIN" -v e="$END" '
    $0 == b { skip = 1; next }
    $0 == e { skip = 0; next }
    !skip   { print }
' "$work/body-old.md" >"$work/body-stripped.md"

{
    cat "$work/body-stripped.md"
    printf '\n%s\n' "$BEGIN"
    printf '## Work in this PR\n\n'
    printf '%s\n' "$SECTION"
    printf '%s\n' "$END"
} >"$work/body-new.md"

if [[ "$DRY" == "--dry-run" ]]; then
    cat "$work/body-new.md"
    exit 0
fi

gh pr edit "$PR" --body-file "$work/body-new.md"
echo "✓ epic block synced into PR #$PR from ${SNAP#"$REPO_ROOT"/}"
"""
PORT = ROOT / ".ci" / "rediacc_ci" / "pr" / "sync_epic_block.py"

FAKE_GH = """#!/usr/bin/env python3
import os
import sys

LOG = os.environ["FAKE_GH_LOG"]
BODY = os.environ.get("FAKE_GH_BODY", "")
VIEW_RC = int(os.environ.get("FAKE_GH_VIEW_RC", "0"))
EDIT_RC = int(os.environ.get("FAKE_GH_EDIT_RC", "0"))
BODY_CAPTURE = os.environ.get("FAKE_GH_BODY_CAPTURE")

with open(LOG, "a", encoding="utf-8") as fh:
    fh.write("\\t".join(sys.argv[1:]) + "\\n")

argv = sys.argv[1:]
if argv[:2] == ["pr", "view"]:
    if VIEW_RC != 0:
        sys.stderr.write("gh: fake pr view failure\\n")
        sys.exit(VIEW_RC)
    sys.stdout.write(BODY)
    sys.exit(0)
if argv[:2] == ["pr", "edit"]:
    if EDIT_RC != 0:
        sys.stderr.write("gh: fake pr edit failure\\n")
        sys.exit(EDIT_RC)
    if BODY_CAPTURE:
        # `--body-file <path>` is always argv index 4 in this script's own
        # invocation shape; captured so a test can inspect the file's content
        # before the caller's `trap EXIT` deletes its temp dir.
        body_file = argv[4]
        with open(body_file, "r", encoding="utf-8") as src:
            content = src.read()
        with open(BODY_CAPTURE, "a", encoding="utf-8") as dst:
            dst.write(content)
            dst.write("\\x00")
    # REAL `gh pr edit` prints the PR URL to its own stdout on success, and
    # NEITHER subject redirects that call's streams -- reproduced here or a
    # port that silently captured (and dropped) it would agree with the twin
    # on every other assertion in this file.
    sys.stdout.write("https://github.com/example/repo/pull/" + argv[2] + "\\n")
    sys.exit(0)
sys.exit(1)
"""


def _git(cwd: pathlib.Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, check=True)


def _repo(tmp_path: pathlib.Path) -> pathlib.Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q")
    _git(repo, "config", "user.email", "test@example.com")
    _git(repo, "config", "user.name", "Test")
    (repo / "agent" / "pr").mkdir(parents=True)
    (repo / "f.txt").write_text("base\n", encoding="utf-8")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "base")
    origin = tmp_path / "origin.git"
    _git(tmp_path, "init", "-q", "--bare", str(origin))
    _git(repo, "remote", "add", "origin", str(origin))
    return repo


def _snapshot(repo: pathlib.Path, branch: str, text: str) -> None:
    slug = branch.replace("/", "-")
    (repo / "agent" / "pr" / f"{slug}.md").write_text(text, encoding="utf-8")


def _publish(repo: pathlib.Path, branch: str, text: str) -> None:
    """Write the snapshot, commit it and push it to the fixture's origin as `branch`: the state the pushed-tip check wants before a real sync."""
    _snapshot(repo, branch, text)
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "snapshot")
    _git(repo, "push", "-q", "origin", f"HEAD:refs/heads/{branch}")


def _fake_gh_bin(where: pathlib.Path) -> pathlib.Path:
    where.mkdir(parents=True, exist_ok=True)
    fake = where / "gh"
    fake.write_text(FAKE_GH, encoding="utf-8")
    fake.chmod(0o755)
    return where


def _run(
    subject: pathlib.Path,
    cwd: pathlib.Path,
    *args: str,
    gh_env: dict[str, str] | None = None,
    path_override: str | None = None,
) -> tuple[subprocess.CompletedProcess[str], list[str]]:
    runner = ["bash"] if subject.suffix == ".sh" else ["python3"]
    env = dict(os.environ)
    # The port imports `rediacc_ci.core.gh_retry`, so a script-path run needs the package root.
    env["PYTHONPATH"] = str(ROOT / ".ci")
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    log = cwd.parent / f"ghlog-{subject.name}.txt"
    log.write_text("", encoding="utf-8")
    if gh_env is not None:
        env.update(gh_env)
        env["FAKE_GH_LOG"] = str(log)
        fake_bin = _fake_gh_bin(cwd.parent / f"fakebin-{subject.name}")
        env["PATH"] = f"{fake_bin}:{env.get('PATH', '')}"
    if path_override is not None:
        env["PATH"] = path_override
    proc = subprocess.run(
        [*runner, str(subject), *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        env=env,
        check=False,
        timeout=30,
    )
    calls = (
        [line for line in log.read_text(encoding="utf-8").splitlines() if line]
        if gh_env is not None
        else []
    )
    return proc, calls


def _twin(where: pathlib.Path) -> pathlib.Path:
    """The frozen bash oracle, written beside the case's fixture (never inside it, so `git rev-parse --show-toplevel` still answers from the cwd)."""
    twin = where / TWIN_NAME
    if not twin.exists():
        twin.write_text(TWIN_BODY, encoding="utf-8")
        twin.chmod(0o755)
    return twin


def run_both(repo: pathlib.Path, *args: str, gh_env: dict[str, str] | None = None):
    old, old_calls = _run(_twin(repo.parent), repo, *args, gh_env=gh_env)
    new, new_calls = _run(PORT, repo, *args, gh_env=gh_env)
    return old, new, old_calls, new_calls


def _assert_agree(old, new, label: str) -> None:
    assert new.returncode == old.returncode, (
        f"{label}: exit diverged: {old.returncode!r} vs {new.returncode!r}"
    )
    assert new.stdout == old.stdout, (
        f"{label}: stdout diverged:\nold: {old.stdout!r}\nnew: {new.stdout!r}"
    )
    assert new.stderr == old.stderr, (
        f"{label}: stderr diverged:\nold: {old.stderr!r}\nnew: {new.stderr!r}"
    )


def _normalize_edit_call(calls: list[str]) -> list[str]:
    """The last token of the `pr edit` call is a per-run mktemp path, which necessarily differs between the two independent subprocess runs; every other token (the verb sequence and its fixed flags) must still match."""
    return [c.rsplit("\t", 1)[0] if c.startswith("pr\tedit") else c for c in calls]


def test_usage_with_zero_args(tmp_path: pathlib.Path) -> None:
    repo = _repo(tmp_path)
    old, new, _, _ = run_both(repo)
    assert old.returncode == 2
    _assert_agree(old, new, "usage-0")


def test_usage_with_one_arg(tmp_path: pathlib.Path) -> None:
    repo = _repo(tmp_path)
    old, new, _, _ = run_both(repo, "5")
    assert old.returncode == 2
    _assert_agree(old, new, "usage-1")


def test_not_a_git_repo(tmp_path: pathlib.Path) -> None:
    outside = tmp_path / "not-a-repo"
    outside.mkdir()
    old, new, _, _ = run_both(outside, "5", "branch", "--dry-run")
    assert old.returncode == 128
    _assert_agree(old, new, "not-a-git-repo")
    assert "not a git repository" in old.stderr


def test_no_snapshot(tmp_path: pathlib.Path) -> None:
    repo = _repo(tmp_path)
    old, new, _, _ = run_both(repo, "5", "no-such-branch", "--dry-run")
    assert old.returncode == 1
    _assert_agree(old, new, "no-snapshot")
    assert "no snapshot at agent/pr/no-such-branch.md" in old.stderr


def test_dry_run_strips_generated_header_and_epic_heading(tmp_path: pathlib.Path) -> None:
    repo = _repo(tmp_path)
    _snapshot(
        repo,
        "0906-1",
        "<!-- generated by worklist.py, do not hand-edit -->\n"
        "# Work in 0906-1\n\n"
        "- [x] item one (abc123)\n"
        "- [ ] item two (def456)\n",
    )
    old, new, _, _ = run_both(repo, "7", "0906-1", "--dry-run")
    assert old.returncode == 0
    _assert_agree(old, new, "dry-run")
    assert "<!-- worklist-epics:begin -->" in old.stdout
    assert "# Work in 0906-1" not in old.stdout
    assert "generated by worklist.py" not in old.stdout


def test_dry_run_slash_in_branch_name_maps_to_dash(tmp_path: pathlib.Path) -> None:
    repo = _repo(tmp_path)
    _snapshot(repo, "feature/thing", "body text\n")
    old, new, _, _ = run_both(repo, "9", "feature/thing", "--dry-run")
    assert old.returncode == 0
    _assert_agree(old, new, "slash-branch")


def test_gh_pr_edit_replaces_existing_block_and_url_passes_through(tmp_path: pathlib.Path) -> None:
    repo = _repo(tmp_path)
    _publish(repo, "0906-1", "- [x] a\n- [ ] b\n")
    gh_env = {
        "FAKE_GH_BODY": (
            "Some existing body text.\n\n"
            "<!-- worklist-epics:begin -->\nold stale block\n<!-- worklist-epics:end -->\n"
            "Trailer line.\n"
        )
    }
    old, new, old_calls, new_calls = run_both(repo, "5", "0906-1", gh_env=gh_env)
    assert old.returncode == 0
    _assert_agree(old, new, "gh-edit-replace")
    assert _normalize_edit_call(old_calls) == _normalize_edit_call(new_calls), (
        f"gh call sequence diverged:\n old: {old_calls}\n new: {new_calls}"
    )
    assert "old stale block" not in old.stdout
    assert "epic block synced into PR #5" in old.stdout


def test_gh_edit_stdout_is_not_swallowed(tmp_path: pathlib.Path) -> None:
    """ANTI-VACUITY for the pass-through requirement. `gh pr edit`'s own stdout (the PR URL) must appear BEFORE the final checkmark line on both sides -- a port that captured and discarded it would still exit 0 and print the checkmark, passing every other assertion in this file."""
    repo = _repo(tmp_path)
    _publish(repo, "0906-1", "- [x] a\n")
    gh_env = {"FAKE_GH_BODY": "plain body\n"}
    old, _, _, _ = run_both(repo, "5", "0906-1", gh_env=gh_env)
    lines = old.stdout.splitlines()
    assert any("github.com" in line for line in lines), (
        f"gh's own stdout is missing: {old.stdout!r}"
    )
    assert lines[-1].startswith("✓"), f"the final line is not the checkmark: {lines[-1]!r}"
    url_line = next(line for line in lines if "github.com" in line)
    assert lines.index(url_line) < len(lines) - 1


def test_gh_pr_view_failure_propagates(tmp_path: pathlib.Path) -> None:
    repo = _repo(tmp_path)
    _publish(repo, "0906-1", "body\n")
    gh_env = {"FAKE_GH_VIEW_RC": "17"}
    old, new, _, _ = run_both(repo, "5", "0906-1", gh_env=gh_env)
    assert old.returncode == 17
    _assert_agree(old, new, "gh-view-fails")


def test_gh_pr_edit_failure_propagates(tmp_path: pathlib.Path) -> None:
    repo = _repo(tmp_path)
    _publish(repo, "0906-1", "body\n")
    gh_env = {"FAKE_GH_EDIT_RC": "3", "FAKE_GH_BODY": "plain body\n"}
    old, new, _, _ = run_both(repo, "5", "0906-1", gh_env=gh_env)
    assert old.returncode == 3
    _assert_agree(old, new, "gh-edit-fails")


def test_planted_defect_is_caught(tmp_path: pathlib.Path) -> None:
    """ANTI-VACUITY. Flip `line == BEGIN` to `line.startswith(BEGIN)` in the
    marker-strip helper -- a plausible-looking "more lenient" rewrite that breaks exact-line equality, which the twin's own header calls out explicitly ("exact-line equality on the markers (not a substring match)"). Driven red on a body whose begin marker has trailing content on the same line as real prose containing the marker text, then the source is restored byte-identical
    and re-verified green."""
    original = PORT.read_text(encoding="utf-8")
    mutated = original.replace(
        "if line == BEGIN:\n            skip = True",
        "if line.startswith(BEGIN):\n            skip = True",
    )
    assert mutated != original, "the line this plant targets is no longer present verbatim"

    repo = _repo(tmp_path)
    _publish(repo, "0906-1", "- [x] a\n")
    # The line STARTS WITH the exact begin marker but carries trailing junk,
    # so real awk's `$0==b` (exact equality) does NOT treat it as the marker
    # and passes it through unskipped; `.startswith(BEGIN)` wrongly does.
    body = "<!-- worklist-epics:begin --> plus trailing junk\nkeep me\n"

    with tempfile.TemporaryDirectory() as td:
        mutant_path = pathlib.Path(td) / "mutant.py"
        mutant_path.write_text(mutated, encoding="utf-8")

        # The rebuilt body is only ever WRITTEN to a file passed to `gh pr edit` in the non-dry-run path (never printed), and that file is deleted by the caller's own `trap EXIT` before this test could look at it -- the fake `gh` copies it out first.
        old_capture = pathlib.Path(td) / "old-body.txt"
        new_capture = pathlib.Path(td) / "new-body.txt"
        old_gh_env = {"FAKE_GH_BODY": body, "FAKE_GH_BODY_CAPTURE": str(old_capture)}
        new_gh_env = {"FAKE_GH_BODY": body, "FAKE_GH_BODY_CAPTURE": str(new_capture)}
        _old, _old_calls = _run(_twin(repo.parent), repo, "5", "0906-1", gh_env=old_gh_env)
        _new, _new_calls = _run(mutant_path, repo, "5", "0906-1", gh_env=new_gh_env)

        old_body = old_capture.read_text(encoding="utf-8")
        new_body = new_capture.read_text(encoding="utf-8")
        assert "keep me" in old_body, "fixture line was stripped by the TWIN; plant is untested"
        assert "keep me" not in new_body, "the mutant did not over-strip; plant did not fire"
        assert new_body != old_body, "planted defect was not caught by the rebuilt-body comparison"

    assert PORT.read_text(encoding="utf-8") == original, (
        "port source must be restored byte-identical"
    )


# --- PLAN-gh-retry G12: the `pr view` read retries a transient fault ----------------------


def _inprocess_view(monkeypatch, tmp_path, results):
    mod = importlib.import_module("rediacc_ci.pr.sync_epic_block")
    repo = _repo(tmp_path)
    _publish(repo, "b1", "## Epic\n\nitems\n")
    monkeypatch.chdir(repo)
    queue = list(results)
    calls: list[list[str]] = []

    def fake(args, **_kw):
        calls.append(list(args))
        rc, out, err = queue.pop(0)
        return ghx.GhResult(["gh", *args], rc, out, err)

    monkeypatch.setattr(gh_retry.ghx, "gh", fake)
    monkeypatch.setattr(gh_retry.time, "sleep", lambda _s: None)
    edits: list[list[str]] = []
    real_run = subprocess.run

    def run(argv, *a, **kw):
        if argv[:3] == ["gh", "pr", "edit"]:
            edits.append(argv)
            return subprocess.CompletedProcess(argv, 0)
        return real_run(argv, *a, **kw)

    monkeypatch.setattr(mod.subprocess, "run", run)
    return mod, calls, edits


def test_pr_view_transient_fault_is_retried_then_synced(monkeypatch, tmp_path) -> None:
    mod, calls, edits = _inprocess_view(
        monkeypatch,
        tmp_path,
        [(1, "", "gh: Server Error (HTTP 502)"), (0, "old body\n", "")],
    )
    assert mod.main(["5", "b1"]) == 0
    assert len(calls) == 2
    assert len(edits) == 1


def test_pr_view_4xx_fails_at_once_with_gh_stderr(monkeypatch, tmp_path, capsys) -> None:
    mod, calls, edits = _inprocess_view(
        monkeypatch, tmp_path, [(1, "", "gh: Not Found (HTTP 404)\n")]
    )
    assert mod.main(["5", "b1"]) == 1
    assert len(calls) == 1
    assert edits == []
    assert "HTTP 404" in capsys.readouterr().err


# --- the shipped script is the port, and its read is retried ------------------------------


def test_the_shipped_script_is_a_thin_exec_of_the_port() -> None:
    """The cutover, pinned. The shipped script must hold no `gh` call of its own (the one-shot `gh pr view` was the PLAN-gh-retry class) and must hand its argv to the port unchanged."""
    text = SHIPPED.read_text(encoding="utf-8")
    code = [
        line for line in text.splitlines() if line.strip() and not line.lstrip().startswith("#")
    ]
    assert not any(" gh " in " %s " % line for line in code), "the shipped script calls gh itself"
    assert code[-1] == 'exec python3 -m rediacc_ci.pr.sync_epic_block "$@"', code[-1]
    assert "gh pr view" in TWIN_BODY, "the oracle lost the read it exists to compare"


def test_the_shipped_script_and_the_oracle_agree_end_to_end(tmp_path: pathlib.Path) -> None:
    """Through the real entry point an agent runs: the edit path, the gh call sequence and the streams match the frozen bash body."""
    repo = _repo(tmp_path)
    _publish(repo, "0906-1", "- [x] a\n- [ ] b\n")
    gh_env = {
        "FAKE_GH_BODY": "Body.\n\n<!-- worklist-epics:begin -->\nstale\n<!-- worklist-epics:end -->\n"
    }
    old, old_calls = _run(_twin(tmp_path), repo, "5", "0906-1", gh_env=gh_env)
    new, new_calls = _run(SHIPPED, repo, "5", "0906-1", gh_env=gh_env)
    assert old.returncode == 0
    _assert_agree(old, new, "shipped-vs-oracle")
    assert _normalize_edit_call(old_calls) == _normalize_edit_call(new_calls)


# --- INTENTIONAL DELTA (Rule T): a sync refuses a snapshot the pushed tip does not hold ---


def _calls_edit(calls: list[str]) -> bool:
    return any(c.startswith("pr\tedit") for c in calls)


def test_delta_a_snapshot_that_differs_from_the_pushed_tip_is_refused(
    tmp_path: pathlib.Path,
) -> None:
    """INTENTIONAL DELTA. 2026-10-07 run 37642753285: `worklist.py --publish` rewrote the snapshot, the sync ran, nothing was committed or pushed, and `check:ci-pr-epic-block` failed three legs ("in the body but not the snapshot"). The twin is the control: it syncs the very same state. The port refuses, names the commit and the push, and never edits the PR."""
    repo = _repo(tmp_path)
    _publish(repo, "0906-1", "- [x] a\n")
    _snapshot(repo, "0906-1", "- [x] a\n- [ ] c965ea99 new epic\n")  # rewritten, unpushed
    gh_env = {"FAKE_GH_BODY": "plain body\n"}
    old, new, old_calls, new_calls = run_both(repo, "5", "0906-1", gh_env=gh_env)
    assert old.returncode == 0
    assert _calls_edit(old_calls), "twin moved: it no longer syncs the unpushed state"
    assert new.returncode == 1
    assert "refusing to sync" in new.stderr
    assert "agent/pr/0906-1.md differs from the copy at origin's tip of 0906-1" in new.stderr
    assert "git commit" in new.stderr
    assert "git push origin 0906-1" in new.stderr
    assert not _calls_edit(new_calls), "the refused sync still edited the PR"
    assert new_calls == [], "the refusal must come before any gh call"
    assert new.stdout == ""


def test_a_snapshot_equal_to_the_pushed_tip_syncs_as_before(tmp_path: pathlib.Path) -> None:
    """The matching direction: pushed and identical, so port and twin agree byte for byte, edit included."""
    repo = _repo(tmp_path)
    _publish(repo, "0906-1", "- [x] a\n- [ ] b\n")
    old, new, old_calls, new_calls = run_both(
        repo, "5", "0906-1", gh_env={"FAKE_GH_BODY": "body\n"}
    )
    assert old.returncode == 0
    _assert_agree(old, new, "snapshot-matches-tip")
    assert _normalize_edit_call(old_calls) == _normalize_edit_call(new_calls)
    assert _calls_edit(new_calls)


def test_delta_a_snapshot_absent_at_the_pushed_tip_is_refused(tmp_path: pathlib.Path) -> None:
    """INTENTIONAL DELTA. The branch is pushed but the tip has no `agent/pr/<branch>.md` (only the working tree does). The twin syncs it; the port refuses with its own message."""
    repo = _repo(tmp_path)
    _git(repo, "push", "-q", "origin", "HEAD:refs/heads/0906-1")  # tip = base commit, no snapshot
    _snapshot(repo, "0906-1", "- [x] a\n")
    old, new, old_calls, new_calls = run_both(
        repo, "5", "0906-1", gh_env={"FAKE_GH_BODY": "body\n"}
    )
    assert old.returncode == 0
    assert _calls_edit(old_calls), "twin moved"
    assert new.returncode == 1
    assert "agent/pr/0906-1.md is absent at origin's tip of 0906-1" in new.stderr
    assert "differs" not in new.stderr
    assert new_calls == []


def test_delta_a_branch_not_on_origin_is_refused(tmp_path: pathlib.Path) -> None:
    """INTENTIONAL DELTA. No pushed tip at all: refused, telling the author to push the branch."""
    repo = _repo(tmp_path)
    _snapshot(repo, "0906-1", "- [x] a\n")
    old, new, old_calls, new_calls = run_both(
        repo, "5", "0906-1", gh_env={"FAKE_GH_BODY": "body\n"}
    )
    assert old.returncode == 0
    assert _calls_edit(old_calls), "twin moved"
    assert new.returncode == 1
    assert "0906-1 is not on origin" in new.stderr
    assert new_calls == []


def test_delta_an_unreadable_origin_is_a_refusal_not_a_pass(tmp_path: pathlib.Path) -> None:
    """Unknown is a failure: with no `origin` the pushed copy is unchecked, so nothing is synced."""
    repo = _repo(tmp_path)
    _git(repo, "remote", "remove", "origin")
    _snapshot(repo, "0906-1", "- [x] a\n")
    _new, new_calls = _run(PORT, repo, "5", "0906-1", gh_env={"FAKE_GH_BODY": "body\n"})
    assert _new.returncode == 1
    assert "cannot read origin's tip" in _new.stderr
    assert new_calls == []


def test_dry_run_is_not_gated_on_the_pushed_tip(tmp_path: pathlib.Path) -> None:
    """`--dry-run` writes nothing, so an unpushed snapshot still previews (the existing dry-run cases already agree with the twin; this pins it with a differing tip)."""
    repo = _repo(tmp_path)
    _publish(repo, "0906-1", "- [x] a\n")
    _snapshot(repo, "0906-1", "- [x] a\n- [ ] unpushed\n")
    old, new, _, _ = run_both(repo, "5", "0906-1", "--dry-run")
    assert old.returncode == 0
    _assert_agree(old, new, "dry-run-unpushed")
    assert "unpushed" in new.stdout
