// AUTO-GENERATED by renet bridge generate-types - DO NOT EDIT
// Run: ./go deploy prep
// Source: renet/pkg/bridge/commands/

// ============================================
// Type-safe parameter interfaces
// ============================================

/** Pull repository from remote source (machine or storage) */
export interface BackupPullParams {
  /** Source type: machine (SSH) or storage (rclone) */
  sourceType: string;
  /** Source machine or storage name */
  from: string;
  /** Grand repository GUID for CoW pre-seeding optimization */
  grand?: string;
}

/** Push repository to remote destination (machine or storage) */
export interface BackupPushParams {
  /** Destination type: machine (SSH) or storage (rclone) */
  destinationType: string;
  /** Single destination (machine or storage name) */
  to?: string;
  /** Target machines for parallel deployment */
  machines?: string[];
  /** Target storage systems for parallel backup */
  storages?: string[];
  /** Backup filename */
  dest: string;
  /** Deployment/version tag */
  tag?: string;
  /** Repository state validation */
  state?: string;
  /** CRIU hot backup (zero-downtime) */
  checkpoint?: boolean;
  /** Overwrite existing backup */
  override?: boolean;
  /** Grand repository GUID for differential/CoW optimization */
  grand?: string;
}

/** Mount RBD image on client */
export interface CephClientMountParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Mount point path */
  mountPoint?: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
  /** Filesystem type (ext4, xfs, btrfs) */
  filesystem?: string;
  /** Format the device before mounting */
  format?: boolean;
  /** Add to fstab for persistence */
  persistent?: boolean;
}

/** Unmount RBD image from client */
export interface CephClientUnmountParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Delete a clone image */
export interface CephCloneDeleteParams {
  /** Clone image name */
  clone: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Flatten clone to remove parent dependency */
export interface CephCloneFlattenParams {
  /** Clone image name */
  clone: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Clone image from snapshot */
export interface CephCloneImageParams {
  /** Source image name */
  image?: string;
  /** Source snapshot name */
  snapshot: string;
  /** Clone image name */
  clone: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** List snapshot clones */
export interface CephCloneListParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Snapshot name */
  snapshot: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Mount clone with COW overlay for read-write access */
export interface CephCloneMountParams {
  /** Clone image name */
  clone: string;
  /** Mount point path */
  mountPoint: string;
  /** COW backing file size */
  cowSize?: string;
  /** Directory for COW files */
  cowDir?: string;
  /** Filesystem type (btrfs, ext4, xfs) */
  filesystem?: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Unmount clone and cleanup COW resources */
export interface CephCloneUnmountParams {
  /** Clone image name */
  clone: string;
  /** Mount point (helps with discovery) */
  mountPoint?: string;
  /** Keep COW file to preserve changes */
  keepCow?: boolean;
  /** Force cleanup even on errors */
  force?: boolean;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Create RBD image */
export interface CephImageCreateParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Image size */
  size: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Delete RBD image */
export interface CephImageDeleteParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Format RBD image with filesystem (maps, formats, unmaps) */
export interface CephImageFormatParams {
  /** Image name */
  image: string;
  /** Pool name */
  pool?: string;
  /** Filesystem type (btrfs, ext4, xfs) */
  filesystem?: string;
  /** Filesystem label */
  label?: string;
  /** Cluster name */
  cluster?: string;
}

/** Get image info */
export interface CephImageInfoParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** List RBD images */
export interface CephImageListParams {
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Map RBD image to local device */
export interface CephImageMapParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Resize RBD image */
export interface CephImageResizeParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** New image size */
  size: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Unmap RBD image from local device */
export interface CephImageUnmapParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Create image snapshot */
export interface CephSnapshotCreateParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Snapshot name */
  snapshot: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Delete image snapshot */
export interface CephSnapshotDeleteParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Snapshot name */
  snapshot: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** List image snapshots */
export interface CephSnapshotListParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Protect snapshot from deletion */
export interface CephSnapshotProtectParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Snapshot name */
  snapshot: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Rollback image to snapshot */
export interface CephSnapshotRollbackParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Snapshot name */
  snapshot: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Unprotect snapshot for deletion */
export interface CephSnapshotUnprotectParams {
  /** Image name (defaults to repository) */
  image?: string;
  /** Snapshot name */
  snapshot: string;
  /** Pool name */
  pool?: string;
  /** Cluster name */
  cluster?: string;
}

/** Execute command in container */
export interface ContainerExecParams {
  /** Container name */
  container: string;
  /** Command to run */
  command: string;
  /** User to run as */
  user?: string;
  /** Allocate TTY */
  tty?: boolean;
}

/** Inspect container details */
export interface ContainerInspectParams {
  /** Container name */
  container: string;
}

/** Kill a container */
export interface ContainerKillParams {
  /** Container name */
  container: string;
  /** Signal to send */
  signal?: string;
}

/** List all containers */
export interface ContainerListParams {
  /** Show all containers (including stopped) */
  all?: boolean;
}

/** Get container logs */
export interface ContainerLogsParams {
  /** Container name */
  container: string;
  /** Number of lines to show */
  lines?: number;
  /** Follow log output */
  follow?: boolean;
  /** Show timestamps */
  timestamps?: boolean;
}

/** Pause a container */
export interface ContainerPauseParams {
  /** Container name */
  container: string;
}

/** Remove a container */
export interface ContainerRemoveParams {
  /** Container name */
  container: string;
  /** Force removal */
  force?: boolean;
}

/** Restart a container */
export interface ContainerRestartParams {
  /** Container name */
  container: string;
  /** Stop timeout in seconds */
  timeout?: number;
}

/** Start a container */
export interface ContainerStartParams {
  /** Container name */
  container: string;
}

/** Get container statistics */
export interface ContainerStatsParams {
  /** Container name (optional, all if omitted) */
  container?: string;
}

/** Stop a container */
export interface ContainerStopParams {
  /** Container name */
  container: string;
  /** Stop timeout in seconds */
  timeout?: number;
}

/** Unpause a container */
export interface ContainerUnpauseParams {
  /** Container name */
  container: string;
}

/** Test SSH connectivity */
export interface MachinePingParams {}

/** Test SSH connectivity */
export interface MachineSshTestParams {}

/** Uninstall renet */
export interface MachineUninstallParams {}

/** Get renet version */
export interface MachineVersionParams {}

/** Create a new repository */
export interface RepositoryCreateParams {
  /** Repository size (e.g., 100G, 1T) */
  size: string;
  /** Owner user ID */
  ownerUid?: string;
  /** Base64 encoded template JSON */
  tmpl?: string;
}

/** Remove a repository */
export interface RepositoryDeleteParams {
  /** Grand repository GUID for tracking */
  grand?: string;
}

/** Stop repository services */
export interface RepositoryDownParams {
  /** Shutdown options */
  option?: string;
  /** Grand repository GUID */
  grand?: string;
}

/** Expand a repository */
export interface RepositoryExpandParams {
  /** Size to add */
  size: string;
}

/** Create a CoW fork of a repository */
export interface RepositoryForkParams {
  /** Fork repository name */
  tag: string;
}

/** Get repository information */
export interface RepositoryInfoParams {}

/** List repositories on machine */
export interface RepositoryListParams {
  /** List type */
  kind?: string;
  /** Output format */
  format?: string;
  /** Source machine or storage */
  from?: string;
}

/** Mount a repository */
export interface RepositoryMountParams {
  /** Restore from checkpoint */
  checkpoint?: boolean;
}

/** Change repository ownership */
export interface RepositoryOwnershipParams {
  /** New owner user ID */
  ownerUid?: string;
}

/** Resize a repository */
export interface RepositoryResizeParams {
  /** New repository size */
  size: string;
}

/** Get repository status */
export interface RepositoryStatusParams {}

/** Apply template to repository */
export interface RepositoryTemplateApplyParams {
  /** Base64 encoded template JSON */
  tmpl: string;
  /** Grand repository GUID */
  grand: string;
}

/** Unmount a repository */
export interface RepositoryUnmountParams {
  /** Create checkpoint before unmount */
  checkpoint?: boolean;
}

/** Start repository services */
export interface RepositoryUpParams {
  /** Startup options */
  option?: string;
  /** Grand repository GUID */
  grand?: string;
}

/** Validate repository configuration */
export interface RepositoryValidateParams {
  /** Skip preparation step */
  skipPrep?: boolean;
  /** Skip down step */
  skipDown?: boolean;
  /** Cleanup after validation */
  cleanup?: boolean;
  /** Validation timeout in seconds */
  timeout?: number;
}

/** Install and configure renet */
export interface SetupParams {
  /** Datastore size */
  datastoreSize?: string;
  /** Installation source */
  from?: string;
  /** Rclone installation source */
  rcloneSource?: string;
  /** Docker installation source */
  dockerSource?: string;
  /** Install AMD driver */
  installAmdDriver?: string;
  /** Install CRIU */
  installCriu?: string;
  /** Install NVIDIA driver */
  installNvidiaDriver?: string;
}

export const BRIDGE_FUNCTIONS = [
  'backup_pull',
  'backup_push',
  'ceph_client_mount',
  'ceph_client_unmount',
  'ceph_clone_delete',
  'ceph_clone_flatten',
  'ceph_clone_image',
  'ceph_clone_list',
  'ceph_clone_mount',
  'ceph_clone_unmount',
  'ceph_image_create',
  'ceph_image_delete',
  'ceph_image_format',
  'ceph_image_info',
  'ceph_image_list',
  'ceph_image_map',
  'ceph_image_resize',
  'ceph_image_unmap',
  'ceph_snapshot_create',
  'ceph_snapshot_delete',
  'ceph_snapshot_list',
  'ceph_snapshot_protect',
  'ceph_snapshot_rollback',
  'ceph_snapshot_unprotect',
  'container_exec',
  'container_inspect',
  'container_kill',
  'container_list',
  'container_logs',
  'container_pause',
  'container_remove',
  'container_restart',
  'container_start',
  'container_stats',
  'container_stop',
  'container_unpause',
  'machine_ping',
  'machine_ssh_test',
  'machine_uninstall',
  'machine_version',
  'repository_create',
  'repository_delete',
  'repository_down',
  'repository_expand',
  'repository_fork',
  'repository_info',
  'repository_list',
  'repository_mount',
  'repository_ownership',
  'repository_resize',
  'repository_status',
  'repository_template_apply',
  'repository_unmount',
  'repository_up',
  'repository_validate',
  'setup',
] as const;

export const BRIDGE_FUNCTIONS_VERSION = 'v0.4.91-4-g1978a25a';

export type BridgeFunctionName = (typeof BRIDGE_FUNCTIONS)[number];

export type FunctionParamsMap = {
  backup_pull: BackupPullParams;
  backup_push: BackupPushParams;
  ceph_client_mount: CephClientMountParams;
  ceph_client_unmount: CephClientUnmountParams;
  ceph_clone_delete: CephCloneDeleteParams;
  ceph_clone_flatten: CephCloneFlattenParams;
  ceph_clone_image: CephCloneImageParams;
  ceph_clone_list: CephCloneListParams;
  ceph_clone_mount: CephCloneMountParams;
  ceph_clone_unmount: CephCloneUnmountParams;
  ceph_image_create: CephImageCreateParams;
  ceph_image_delete: CephImageDeleteParams;
  ceph_image_format: CephImageFormatParams;
  ceph_image_info: CephImageInfoParams;
  ceph_image_list: CephImageListParams;
  ceph_image_map: CephImageMapParams;
  ceph_image_resize: CephImageResizeParams;
  ceph_image_unmap: CephImageUnmapParams;
  ceph_snapshot_create: CephSnapshotCreateParams;
  ceph_snapshot_delete: CephSnapshotDeleteParams;
  ceph_snapshot_list: CephSnapshotListParams;
  ceph_snapshot_protect: CephSnapshotProtectParams;
  ceph_snapshot_rollback: CephSnapshotRollbackParams;
  ceph_snapshot_unprotect: CephSnapshotUnprotectParams;
  container_exec: ContainerExecParams;
  container_inspect: ContainerInspectParams;
  container_kill: ContainerKillParams;
  container_list: ContainerListParams;
  container_logs: ContainerLogsParams;
  container_pause: ContainerPauseParams;
  container_remove: ContainerRemoveParams;
  container_restart: ContainerRestartParams;
  container_start: ContainerStartParams;
  container_stats: ContainerStatsParams;
  container_stop: ContainerStopParams;
  container_unpause: ContainerUnpauseParams;
  machine_ping: MachinePingParams;
  machine_ssh_test: MachineSshTestParams;
  machine_uninstall: MachineUninstallParams;
  machine_version: MachineVersionParams;
  repository_create: RepositoryCreateParams;
  repository_delete: RepositoryDeleteParams;
  repository_down: RepositoryDownParams;
  repository_expand: RepositoryExpandParams;
  repository_fork: RepositoryForkParams;
  repository_info: RepositoryInfoParams;
  repository_list: RepositoryListParams;
  repository_mount: RepositoryMountParams;
  repository_ownership: RepositoryOwnershipParams;
  repository_resize: RepositoryResizeParams;
  repository_status: RepositoryStatusParams;
  repository_template_apply: RepositoryTemplateApplyParams;
  repository_unmount: RepositoryUnmountParams;
  repository_up: RepositoryUpParams;
  repository_validate: RepositoryValidateParams;
  setup: SetupParams;
};

export const FUNCTION_REQUIREMENTS: Record<BridgeFunctionName, { requirements: Partial<Record<'machine' | 'team' | 'repository' | 'storage' | 'organization' | 'bridge' | 'network_id', boolean>> }> = {
  'backup_pull': {
    requirements: { machine: true, team: true, repository: true, storage: true },
  },
  'backup_push': {
    requirements: { machine: true, team: true, repository: true, storage: true },
  },
  'ceph_client_mount': {
    requirements: { machine: true, team: true },
  },
  'ceph_client_unmount': {
    requirements: { machine: true, team: true },
  },
  'ceph_clone_delete': {
    requirements: { machine: true, team: true },
  },
  'ceph_clone_flatten': {
    requirements: { machine: true, team: true },
  },
  'ceph_clone_image': {
    requirements: { machine: true, team: true },
  },
  'ceph_clone_list': {
    requirements: { machine: true, team: true },
  },
  'ceph_clone_mount': {
    requirements: { machine: true, team: true },
  },
  'ceph_clone_unmount': {
    requirements: { machine: true, team: true },
  },
  'ceph_image_create': {
    requirements: { machine: true, team: true },
  },
  'ceph_image_delete': {
    requirements: { machine: true, team: true },
  },
  'ceph_image_format': {
    requirements: { machine: true, team: true },
  },
  'ceph_image_info': {
    requirements: { machine: true, team: true },
  },
  'ceph_image_list': {
    requirements: { machine: true, team: true },
  },
  'ceph_image_map': {
    requirements: { machine: true, team: true },
  },
  'ceph_image_resize': {
    requirements: { machine: true, team: true },
  },
  'ceph_image_unmap': {
    requirements: { machine: true, team: true },
  },
  'ceph_snapshot_create': {
    requirements: { machine: true, team: true },
  },
  'ceph_snapshot_delete': {
    requirements: { machine: true, team: true },
  },
  'ceph_snapshot_list': {
    requirements: { machine: true, team: true },
  },
  'ceph_snapshot_protect': {
    requirements: { machine: true, team: true },
  },
  'ceph_snapshot_rollback': {
    requirements: { machine: true, team: true },
  },
  'ceph_snapshot_unprotect': {
    requirements: { machine: true, team: true },
  },
  'container_exec': {
    requirements: { machine: true, team: true, repository: true, network_id: true },
  },
  'container_inspect': {
    requirements: { machine: true, team: true, repository: true, network_id: true },
  },
  'container_kill': {
    requirements: { machine: true, team: true, repository: true, network_id: true },
  },
  'container_list': {
    requirements: { machine: true, team: true, network_id: true },
  },
  'container_logs': {
    requirements: { machine: true, team: true, repository: true, network_id: true },
  },
  'container_pause': {
    requirements: { machine: true, team: true, repository: true, network_id: true },
  },
  'container_remove': {
    requirements: { machine: true, team: true, repository: true, network_id: true },
  },
  'container_restart': {
    requirements: { machine: true, team: true, repository: true, network_id: true },
  },
  'container_start': {
    requirements: { machine: true, team: true, repository: true, network_id: true },
  },
  'container_stats': {
    requirements: { machine: true, team: true, repository: true, network_id: true },
  },
  'container_stop': {
    requirements: { machine: true, team: true, repository: true, network_id: true },
  },
  'container_unpause': {
    requirements: { machine: true, team: true, repository: true, network_id: true },
  },
  'machine_ping': {
    requirements: { machine: true, team: true },
  },
  'machine_ssh_test': {
    requirements: { machine: true, team: true },
  },
  'machine_uninstall': {
    requirements: { machine: true, team: true },
  },
  'machine_version': {
    requirements: { machine: true, team: true },
  },
  'repository_create': {
    requirements: { machine: true, team: true, repository: true },
  },
  'repository_delete': {
    requirements: { machine: true, team: true, repository: true },
  },
  'repository_down': {
    requirements: { machine: true, team: true, repository: true },
  },
  'repository_expand': {
    requirements: { machine: true, team: true, repository: true },
  },
  'repository_fork': {
    requirements: { machine: true, team: true, repository: true },
  },
  'repository_info': {
    requirements: { machine: true, team: true, repository: true },
  },
  'repository_list': {
    requirements: { machine: true, team: true, organization: true },
  },
  'repository_mount': {
    requirements: { machine: true, team: true, repository: true },
  },
  'repository_ownership': {
    requirements: { machine: true, team: true, repository: true },
  },
  'repository_resize': {
    requirements: { machine: true, team: true, repository: true },
  },
  'repository_status': {
    requirements: { machine: true, team: true, repository: true },
  },
  'repository_template_apply': {
    requirements: { machine: true, team: true, repository: true },
  },
  'repository_unmount': {
    requirements: { machine: true, team: true, repository: true },
  },
  'repository_up': {
    requirements: { machine: true, team: true, repository: true, bridge: true },
  },
  'repository_validate': {
    requirements: { machine: true, team: true, repository: true, bridge: true },
  },
  'setup': {
    requirements: { machine: true, team: true, organization: true },
  },
};

export const FUNCTION_CATEGORIES = [
  'backup',
  'ceph',
  'container',
  'machine',
  'repository',
] as const;

export type FunctionCategory = (typeof FUNCTION_CATEGORIES)[number];

export interface CheckboxOption {
  value: string;
  label: string;
}

/**
 * UI widget types for parameter rendering.
 * These values determine which component the console uses to render the parameter.
 */
export type UIType =
  | 'dropdown'
  | 'checkbox'
  | 'machine-multiselect'
  | 'storage-multiselect'
  | 'template-selector'
  | 'source-dropdown'
  | 'destination-dropdown'
  | 'repo-dropdown';

export interface FunctionParameterDefinition {
  type: 'string' | 'int' | 'bool' | 'array';
  required?: boolean;
  default?: string;
  help?: string;

  // UI metadata
  options?: string[];
  format?: string;
  ui?: UIType;
  units?: string[];
  placeholder?: string;
  label?: string;
  checkboxOptions?: CheckboxOption[];

  // Parameter dependencies (for UI field interactions)
  dependsOn?: string;
  clearWhen?: string;

  // Validation constraints (for runtime validation / Zod schema generation)
  minLength?: number;
  maxLength?: number;
  pattern?: string;
  enum?: string[];
}

export interface FunctionDefinition {
  name: string;
  category: FunctionCategory;
  showInMenu: boolean;
  requirements: Partial<Record<'machine' | 'team' | 'repository' | 'storage' | 'organization' | 'bridge' | 'network_id', boolean>>;
  params: Record<string, FunctionParameterDefinition>;
}

// ============================================
// Function definitions (single source of truth - replaces functions.json)
// ============================================

export const FUNCTION_DEFINITIONS: Record<BridgeFunctionName, FunctionDefinition> = {
  'backup_pull': {
    name: 'backup_pull',
    category: 'backup',
    showInMenu: true,
    requirements: { machine: true, team: true, repository: true, storage: true },
    params: {
      sourceType: {
        type: 'string',
        required: true,
        default: 'storage',
        help: 'Source type: machine (SSH) or storage (rclone)',
        options: ['machine', 'storage'],
        ui: 'dropdown',
        enum: ['machine', 'storage'],
      },
      from: {
        type: 'string',
        required: true,
        help: 'Source machine or storage name',
        ui: 'source-dropdown',
        dependsOn: 'sourceType',
        minLength: 1,
      },
      grand: {
        type: 'string',
        help: 'Grand repository GUID for CoW pre-seeding optimization',
      },
    },
  },
  'backup_push': {
    name: 'backup_push',
    category: 'backup',
    showInMenu: true,
    requirements: { machine: true, team: true, repository: true, storage: true },
    params: {
      destinationType: {
        type: 'string',
        required: true,
        default: 'machine',
        help: 'Destination type: machine (SSH) or storage (rclone)',
        options: ['machine', 'storage'],
        ui: 'dropdown',
        enum: ['machine', 'storage'],
      },
      to: {
        type: 'string',
        help: 'Single destination (machine or storage name)',
        ui: 'destination-dropdown',
        dependsOn: 'destinationType',
      },
      machines: {
        type: 'array',
        help: 'Target machines for parallel deployment',
        ui: 'machine-multiselect',
        label: 'Target Machines',
      },
      storages: {
        type: 'array',
        help: 'Target storage systems for parallel backup',
        ui: 'storage-multiselect',
        label: 'Target Storage Systems',
      },
      dest: {
        type: 'string',
        required: true,
        help: 'Backup filename',
        minLength: 1,
      },
      tag: {
        type: 'string',
        help: 'Deployment/version tag',
        placeholder: 'e.g., 2025-01-09-14-30-00',
      },
      state: {
        type: 'string',
        help: 'Repository state validation',
        options: ['online', 'offline'],
        ui: 'dropdown',
        enum: ['online', 'offline'],
      },
      checkpoint: {
        type: 'bool',
        default: 'false',
        help: 'CRIU hot backup (zero-downtime)',
        options: ['true', 'false'],
        ui: 'dropdown',
      },
      override: {
        type: 'bool',
        help: 'Overwrite existing backup',
      },
      grand: {
        type: 'string',
        help: 'Grand repository GUID for differential/CoW optimization',
      },
    },
  },
  'ceph_client_mount': {
    name: 'ceph_client_mount',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      mountPoint: {
        type: 'string',
        help: 'Mount point path',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
      filesystem: {
        type: 'string',
        default: 'ext4',
        help: 'Filesystem type (ext4, xfs, btrfs)',
      },
      format: {
        type: 'bool',
        help: 'Format the device before mounting',
      },
      persistent: {
        type: 'bool',
        help: 'Add to fstab for persistence',
      },
    },
  },
  'ceph_client_unmount': {
    name: 'ceph_client_unmount',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_clone_delete': {
    name: 'ceph_clone_delete',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      clone: {
        type: 'string',
        required: true,
        help: 'Clone image name',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_clone_flatten': {
    name: 'ceph_clone_flatten',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      clone: {
        type: 'string',
        required: true,
        help: 'Clone image name',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_clone_image': {
    name: 'ceph_clone_image',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Source image name',
      },
      snapshot: {
        type: 'string',
        required: true,
        help: 'Source snapshot name',
      },
      clone: {
        type: 'string',
        required: true,
        help: 'Clone image name',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_clone_list': {
    name: 'ceph_clone_list',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      snapshot: {
        type: 'string',
        required: true,
        help: 'Snapshot name',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_clone_mount': {
    name: 'ceph_clone_mount',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      clone: {
        type: 'string',
        required: true,
        help: 'Clone image name',
      },
      mountPoint: {
        type: 'string',
        required: true,
        help: 'Mount point path',
      },
      cowSize: {
        type: 'string',
        default: '10G',
        help: 'COW backing file size',
      },
      cowDir: {
        type: 'string',
        default: '/tmp/cowdata',
        help: 'Directory for COW files',
      },
      filesystem: {
        type: 'string',
        default: 'btrfs',
        help: 'Filesystem type (btrfs, ext4, xfs)',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_clone_unmount': {
    name: 'ceph_clone_unmount',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      clone: {
        type: 'string',
        required: true,
        help: 'Clone image name',
      },
      mountPoint: {
        type: 'string',
        help: 'Mount point (helps with discovery)',
      },
      keepCow: {
        type: 'bool',
        help: 'Keep COW file to preserve changes',
      },
      force: {
        type: 'bool',
        help: 'Force cleanup even on errors',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_image_create': {
    name: 'ceph_image_create',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      size: {
        type: 'string',
        required: true,
        help: 'Image size',
        format: 'size',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_image_delete': {
    name: 'ceph_image_delete',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_image_format': {
    name: 'ceph_image_format',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        required: true,
        help: 'Image name',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      filesystem: {
        type: 'string',
        default: 'btrfs',
        help: 'Filesystem type (btrfs, ext4, xfs)',
      },
      label: {
        type: 'string',
        help: 'Filesystem label',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_image_info': {
    name: 'ceph_image_info',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_image_list': {
    name: 'ceph_image_list',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_image_map': {
    name: 'ceph_image_map',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_image_resize': {
    name: 'ceph_image_resize',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      size: {
        type: 'string',
        required: true,
        help: 'New image size',
        format: 'size',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_image_unmap': {
    name: 'ceph_image_unmap',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_snapshot_create': {
    name: 'ceph_snapshot_create',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      snapshot: {
        type: 'string',
        required: true,
        help: 'Snapshot name',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_snapshot_delete': {
    name: 'ceph_snapshot_delete',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      snapshot: {
        type: 'string',
        required: true,
        help: 'Snapshot name',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_snapshot_list': {
    name: 'ceph_snapshot_list',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_snapshot_protect': {
    name: 'ceph_snapshot_protect',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      snapshot: {
        type: 'string',
        required: true,
        help: 'Snapshot name',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_snapshot_rollback': {
    name: 'ceph_snapshot_rollback',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      snapshot: {
        type: 'string',
        required: true,
        help: 'Snapshot name',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'ceph_snapshot_unprotect': {
    name: 'ceph_snapshot_unprotect',
    category: 'ceph',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
      image: {
        type: 'string',
        help: 'Image name (defaults to repository)',
      },
      snapshot: {
        type: 'string',
        required: true,
        help: 'Snapshot name',
      },
      pool: {
        type: 'string',
        default: 'rbd',
        help: 'Pool name',
      },
      cluster: {
        type: 'string',
        default: 'rediacc',
        help: 'Cluster name',
      },
    },
  },
  'container_exec': {
    name: 'container_exec',
    category: 'container',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true, network_id: true },
    params: {
      container: {
        type: 'string',
        required: true,
        help: 'Container name',
      },
      command: {
        type: 'string',
        required: true,
        help: 'Command to run',
      },
      user: {
        type: 'string',
        help: 'User to run as',
      },
      tty: {
        type: 'bool',
        help: 'Allocate TTY',
        options: ['true', 'false'],
      },
    },
  },
  'container_inspect': {
    name: 'container_inspect',
    category: 'container',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true, network_id: true },
    params: {
      container: {
        type: 'string',
        required: true,
        help: 'Container name',
      },
    },
  },
  'container_kill': {
    name: 'container_kill',
    category: 'container',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true, network_id: true },
    params: {
      container: {
        type: 'string',
        required: true,
        help: 'Container name',
      },
      signal: {
        type: 'string',
        default: 'SIGTERM',
        help: 'Signal to send',
      },
    },
  },
  'container_list': {
    name: 'container_list',
    category: 'container',
    showInMenu: false,
    requirements: { machine: true, team: true, network_id: true },
    params: {
      all: {
        type: 'bool',
        default: 'true',
        help: 'Show all containers (including stopped)',
      },
    },
  },
  'container_logs': {
    name: 'container_logs',
    category: 'container',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true, network_id: true },
    params: {
      container: {
        type: 'string',
        required: true,
        help: 'Container name',
      },
      lines: {
        type: 'int',
        default: '100',
        help: 'Number of lines to show',
      },
      follow: {
        type: 'bool',
        help: 'Follow log output',
        options: ['true', 'false'],
      },
      timestamps: {
        type: 'bool',
        help: 'Show timestamps',
      },
    },
  },
  'container_pause': {
    name: 'container_pause',
    category: 'container',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true, network_id: true },
    params: {
      container: {
        type: 'string',
        required: true,
        help: 'Container name',
      },
    },
  },
  'container_remove': {
    name: 'container_remove',
    category: 'container',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true, network_id: true },
    params: {
      container: {
        type: 'string',
        required: true,
        help: 'Container name',
      },
      force: {
        type: 'bool',
        help: 'Force removal',
        options: ['true', 'false'],
      },
    },
  },
  'container_restart': {
    name: 'container_restart',
    category: 'container',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true, network_id: true },
    params: {
      container: {
        type: 'string',
        required: true,
        help: 'Container name',
      },
      timeout: {
        type: 'int',
        help: 'Stop timeout in seconds',
      },
    },
  },
  'container_start': {
    name: 'container_start',
    category: 'container',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true, network_id: true },
    params: {
      container: {
        type: 'string',
        required: true,
        help: 'Container name',
      },
    },
  },
  'container_stats': {
    name: 'container_stats',
    category: 'container',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true, network_id: true },
    params: {
      container: {
        type: 'string',
        help: 'Container name (optional, all if omitted)',
      },
    },
  },
  'container_stop': {
    name: 'container_stop',
    category: 'container',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true, network_id: true },
    params: {
      container: {
        type: 'string',
        required: true,
        help: 'Container name',
      },
      timeout: {
        type: 'int',
        help: 'Stop timeout in seconds',
      },
    },
  },
  'container_unpause': {
    name: 'container_unpause',
    category: 'container',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true, network_id: true },
    params: {
      container: {
        type: 'string',
        required: true,
        help: 'Container name',
      },
    },
  },
  'machine_ping': {
    name: 'machine_ping',
    category: 'machine',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
    },
  },
  'machine_ssh_test': {
    name: 'machine_ssh_test',
    category: 'machine',
    showInMenu: false,
    requirements: { machine: true, team: true },
    params: {
    },
  },
  'machine_uninstall': {
    name: 'machine_uninstall',
    category: 'machine',
    showInMenu: true,
    requirements: { machine: true, team: true },
    params: {
    },
  },
  'machine_version': {
    name: 'machine_version',
    category: 'machine',
    showInMenu: true,
    requirements: { machine: true, team: true },
    params: {
    },
  },
  'repository_create': {
    name: 'repository_create',
    category: 'repository',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true },
    params: {
      size: {
        type: 'string',
        required: true,
        help: 'Repository size (e.g., 100G, 1T)',
        format: 'size',
        units: ['G', 'T'],
      },
      ownerUid: {
        type: 'string',
        help: 'Owner user ID',
      },
      tmpl: {
        type: 'string',
        help: 'Base64 encoded template JSON',
      },
    },
  },
  'repository_delete': {
    name: 'repository_delete',
    category: 'repository',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true },
    params: {
      grand: {
        type: 'string',
        help: 'Grand repository GUID for tracking',
      },
    },
  },
  'repository_down': {
    name: 'repository_down',
    category: 'repository',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true },
    params: {
      option: {
        type: 'string',
        help: 'Shutdown options',
        ui: 'checkbox',
        label: 'Options',
        checkboxOptions: [
          { value: 'unmount', label: 'unmountAfterStopping' },
        ],
      },
      grand: {
        type: 'string',
        help: 'Grand repository GUID',
      },
    },
  },
  'repository_expand': {
    name: 'repository_expand',
    category: 'repository',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true },
    params: {
      size: {
        type: 'string',
        required: true,
        help: 'Size to add',
        format: 'size',
        units: ['G', 'T'],
      },
    },
  },
  'repository_fork': {
    name: 'repository_fork',
    category: 'repository',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true },
    params: {
      tag: {
        type: 'string',
        required: true,
        help: 'Fork repository name',
      },
    },
  },
  'repository_info': {
    name: 'repository_info',
    category: 'repository',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true },
    params: {
    },
  },
  'repository_list': {
    name: 'repository_list',
    category: 'repository',
    showInMenu: false,
    requirements: { machine: true, team: true, organization: true },
    params: {
      kind: {
        type: 'string',
        default: 'repo',
        help: 'List type',
      },
      format: {
        type: 'string',
        help: 'Output format',
      },
      from: {
        type: 'string',
        help: 'Source machine or storage',
        ui: 'source-dropdown',
      },
    },
  },
  'repository_mount': {
    name: 'repository_mount',
    category: 'repository',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true },
    params: {
      checkpoint: {
        type: 'bool',
        help: 'Restore from checkpoint',
        options: ['true', 'false'],
      },
    },
  },
  'repository_ownership': {
    name: 'repository_ownership',
    category: 'repository',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true },
    params: {
      ownerUid: {
        type: 'string',
        help: 'New owner user ID',
      },
    },
  },
  'repository_resize': {
    name: 'repository_resize',
    category: 'repository',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true },
    params: {
      size: {
        type: 'string',
        required: true,
        help: 'New repository size',
        format: 'size',
        units: ['G', 'T'],
      },
    },
  },
  'repository_status': {
    name: 'repository_status',
    category: 'repository',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true },
    params: {
    },
  },
  'repository_template_apply': {
    name: 'repository_template_apply',
    category: 'repository',
    showInMenu: true,
    requirements: { machine: true, team: true, repository: true },
    params: {
      tmpl: {
        type: 'string',
        required: true,
        help: 'Base64 encoded template JSON',
        ui: 'template-selector',
      },
      grand: {
        type: 'string',
        required: true,
        help: 'Grand repository GUID',
      },
    },
  },
  'repository_unmount': {
    name: 'repository_unmount',
    category: 'repository',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true },
    params: {
      checkpoint: {
        type: 'bool',
        help: 'Create checkpoint before unmount',
        options: ['true', 'false'],
      },
    },
  },
  'repository_up': {
    name: 'repository_up',
    category: 'repository',
    showInMenu: false,
    requirements: { machine: true, team: true, repository: true, bridge: true },
    params: {
      option: {
        type: 'string',
        help: 'Startup options',
        ui: 'checkbox',
        label: 'Options',
        checkboxOptions: [
          { value: 'mount', label: 'mountRepositoryFirst' },
          { value: 'prep-only', label: 'preparationOnly' },
        ],
      },
      grand: {
        type: 'string',
        help: 'Grand repository GUID',
      },
    },
  },
  'repository_validate': {
    name: 'repository_validate',
    category: 'repository',
    showInMenu: true,
    requirements: { machine: true, team: true, repository: true, bridge: true },
    params: {
      skipPrep: {
        type: 'bool',
        default: 'false',
        help: 'Skip preparation step',
        options: ['true', 'false'],
        ui: 'dropdown',
      },
      skipDown: {
        type: 'bool',
        default: 'false',
        help: 'Skip down step',
        options: ['true', 'false'],
        ui: 'dropdown',
      },
      cleanup: {
        type: 'bool',
        default: 'true',
        help: 'Cleanup after validation',
        options: ['true', 'false'],
        ui: 'dropdown',
      },
      timeout: {
        type: 'int',
        default: '300',
        help: 'Validation timeout in seconds',
      },
    },
  },
  'setup': {
    name: 'setup',
    category: 'machine',
    showInMenu: true,
    requirements: { machine: true, team: true, organization: true },
    params: {
      datastoreSize: {
        type: 'string',
        default: '95%',
        help: 'Datastore size',
        format: 'size',
        units: ['percentage', 'G', 'T'],
        pattern: '^\\d+(%|G|T)$',
      },
      from: {
        type: 'string',
        default: 'apt-repo',
        help: 'Installation source',
        options: ['apt-repo', 'tar-static', 'deb-local'],
        ui: 'dropdown',
        enum: ['apt-repo', 'tar-static', 'deb-local'],
      },
      rcloneSource: {
        type: 'string',
        default: 'install-script',
        help: 'Rclone installation source',
        options: ['install-script', 'package-manager', 'manual'],
        ui: 'dropdown',
        enum: ['install-script', 'package-manager', 'manual'],
      },
      dockerSource: {
        type: 'string',
        default: 'docker-repo',
        help: 'Docker installation source',
        options: ['docker-repo', 'package-manager', 'snap', 'manual'],
        ui: 'dropdown',
        enum: ['docker-repo', 'package-manager', 'snap', 'manual'],
      },
      installAmdDriver: {
        type: 'string',
        default: 'auto',
        help: 'Install AMD driver',
        options: ['auto', 'true', 'false'],
        ui: 'dropdown',
        enum: ['auto', 'true', 'false'],
      },
      installCriu: {
        type: 'string',
        default: 'auto',
        help: 'Install CRIU',
        options: ['auto', 'true', 'false', 'manual'],
        ui: 'dropdown',
        enum: ['auto', 'true', 'false', 'manual'],
      },
      installNvidiaDriver: {
        type: 'string',
        default: 'auto',
        help: 'Install NVIDIA driver',
        options: ['auto', 'true', 'false'],
        ui: 'dropdown',
        enum: ['auto', 'true', 'false'],
      },
    },
  },
};

export type QueueFunctionsType = {
  [K in BridgeFunctionName]: (
    params: FunctionParamsMap[K]
  ) => { functionName: K; params: FunctionParamsMap[K] };
};

export const queueFunctions: QueueFunctionsType = {
  backup_pull: (params) => ({ functionName: 'backup_pull', params }),
  backup_push: (params) => ({ functionName: 'backup_push', params }),
  ceph_client_mount: (params) => ({ functionName: 'ceph_client_mount', params }),
  ceph_client_unmount: (params) => ({ functionName: 'ceph_client_unmount', params }),
  ceph_clone_delete: (params) => ({ functionName: 'ceph_clone_delete', params }),
  ceph_clone_flatten: (params) => ({ functionName: 'ceph_clone_flatten', params }),
  ceph_clone_image: (params) => ({ functionName: 'ceph_clone_image', params }),
  ceph_clone_list: (params) => ({ functionName: 'ceph_clone_list', params }),
  ceph_clone_mount: (params) => ({ functionName: 'ceph_clone_mount', params }),
  ceph_clone_unmount: (params) => ({ functionName: 'ceph_clone_unmount', params }),
  ceph_image_create: (params) => ({ functionName: 'ceph_image_create', params }),
  ceph_image_delete: (params) => ({ functionName: 'ceph_image_delete', params }),
  ceph_image_format: (params) => ({ functionName: 'ceph_image_format', params }),
  ceph_image_info: (params) => ({ functionName: 'ceph_image_info', params }),
  ceph_image_list: (params) => ({ functionName: 'ceph_image_list', params }),
  ceph_image_map: (params) => ({ functionName: 'ceph_image_map', params }),
  ceph_image_resize: (params) => ({ functionName: 'ceph_image_resize', params }),
  ceph_image_unmap: (params) => ({ functionName: 'ceph_image_unmap', params }),
  ceph_snapshot_create: (params) => ({ functionName: 'ceph_snapshot_create', params }),
  ceph_snapshot_delete: (params) => ({ functionName: 'ceph_snapshot_delete', params }),
  ceph_snapshot_list: (params) => ({ functionName: 'ceph_snapshot_list', params }),
  ceph_snapshot_protect: (params) => ({ functionName: 'ceph_snapshot_protect', params }),
  ceph_snapshot_rollback: (params) => ({ functionName: 'ceph_snapshot_rollback', params }),
  ceph_snapshot_unprotect: (params) => ({ functionName: 'ceph_snapshot_unprotect', params }),
  container_exec: (params) => ({ functionName: 'container_exec', params }),
  container_inspect: (params) => ({ functionName: 'container_inspect', params }),
  container_kill: (params) => ({ functionName: 'container_kill', params }),
  container_list: (params) => ({ functionName: 'container_list', params }),
  container_logs: (params) => ({ functionName: 'container_logs', params }),
  container_pause: (params) => ({ functionName: 'container_pause', params }),
  container_remove: (params) => ({ functionName: 'container_remove', params }),
  container_restart: (params) => ({ functionName: 'container_restart', params }),
  container_start: (params) => ({ functionName: 'container_start', params }),
  container_stats: (params) => ({ functionName: 'container_stats', params }),
  container_stop: (params) => ({ functionName: 'container_stop', params }),
  container_unpause: (params) => ({ functionName: 'container_unpause', params }),
  machine_ping: (params) => ({ functionName: 'machine_ping', params }),
  machine_ssh_test: (params) => ({ functionName: 'machine_ssh_test', params }),
  machine_uninstall: (params) => ({ functionName: 'machine_uninstall', params }),
  machine_version: (params) => ({ functionName: 'machine_version', params }),
  repository_create: (params) => ({ functionName: 'repository_create', params }),
  repository_delete: (params) => ({ functionName: 'repository_delete', params }),
  repository_down: (params) => ({ functionName: 'repository_down', params }),
  repository_expand: (params) => ({ functionName: 'repository_expand', params }),
  repository_fork: (params) => ({ functionName: 'repository_fork', params }),
  repository_info: (params) => ({ functionName: 'repository_info', params }),
  repository_list: (params) => ({ functionName: 'repository_list', params }),
  repository_mount: (params) => ({ functionName: 'repository_mount', params }),
  repository_ownership: (params) => ({ functionName: 'repository_ownership', params }),
  repository_resize: (params) => ({ functionName: 'repository_resize', params }),
  repository_status: (params) => ({ functionName: 'repository_status', params }),
  repository_template_apply: (params) => ({ functionName: 'repository_template_apply', params }),
  repository_unmount: (params) => ({ functionName: 'repository_unmount', params }),
  repository_up: (params) => ({ functionName: 'repository_up', params }),
  repository_validate: (params) => ({ functionName: 'repository_validate', params }),
  setup: (params) => ({ functionName: 'setup', params }),
};

export type TypedFunctionPayload<F extends BridgeFunctionName> = {
  functionName: F;
  params: FunctionParamsMap[F];
};

export function createFunctionPayload<F extends BridgeFunctionName>(
  functionName: F,
  params: FunctionParamsMap[F]
): TypedFunctionPayload<F> {
  return { functionName, params };
}

export function getTypedParams<F extends BridgeFunctionName>(
  _functionName: F,
  params: FunctionParamsMap[F]
): FunctionParamsMap[F] {
  return params;
}

export function isBridgeFunction(name: string): name is BridgeFunctionName {
  return (BRIDGE_FUNCTIONS as readonly string[]).includes(name);
}

// All functions in this file are public. Visibility validation is handled server-side by renet.
export function isPublicBridgeFunction(name: string): boolean {
  return isBridgeFunction(name);
}

export function getFunctionsByCategory(category: FunctionCategory): BridgeFunctionName[] {
  return BRIDGE_FUNCTIONS.filter((name) => FUNCTION_DEFINITIONS[name].category === category);
}

export function getMenuFunctions(): BridgeFunctionName[] {
  return BRIDGE_FUNCTIONS.filter((name) => FUNCTION_DEFINITIONS[name].showInMenu);
}
