// AUTO-GENERATED by renet bridge generate-types - DO NOT EDIT
// Run: ./go deploy prep
// Source: renet/pkg/bridge/commands/

import { z, type ZodSafeParseResult } from 'zod';
import type { BridgeFunctionName, FunctionParamsMap } from './functions.generated';

// ============================================
// Zod schemas for runtime validation
// ============================================

/** Pull repository from remote source (machine or storage) */
export const BackupPullParamsSchema = z.object({
  sourceType: z
    .enum(['machine', 'storage'])
    .default('storage')
    .describe('Source type: machine (SSH) or storage (rclone)'),
  from: z.string().min(1).describe('Source machine or storage name'),
  grand: z.string().optional().describe('Grand repository GUID for CoW pre-seeding optimization'),
});

/** Push repository to remote destination (machine or storage) */
export const BackupPushParamsSchema = z.object({
  destinationType: z
    .enum(['machine', 'storage'])
    .default('machine')
    .describe('Destination type: machine (SSH) or storage (rclone)'),
  to: z.string().optional().describe('Single destination (machine or storage name)'),
  machines: z.array(z.string()).optional().describe('Target machines for parallel deployment'),
  storages: z.array(z.string()).optional().describe('Target storage systems for parallel backup'),
  dest: z.string().min(1).describe('Backup filename'),
  tag: z.string().optional().describe('Deployment/version tag'),
  state: z.enum(['online', 'offline']).optional().describe('Repository state validation'),
  checkpoint: z.boolean().default(false).optional().describe('CRIU hot backup (zero-downtime)'),
  override: z.boolean().optional().describe('Overwrite existing backup'),
  grand: z.string().optional().describe('Grand repository GUID for differential/CoW optimization'),
});

/** Bootstrap Ceph cluster */
export const CephBootstrapClusterParamsSchema = z.object({
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
  monitor: z.string().optional().describe('Monitor node address'),
});

/** Mount RBD image on client */
export const CephClientMountParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  mountPoint: z.string().optional().describe('Mount point path'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
  filesystem: z.string().default('ext4').optional().describe('Filesystem type (ext4, xfs, btrfs)'),
  format: z.boolean().optional().describe('Format the device before mounting'),
  persistent: z.boolean().optional().describe('Add to fstab for persistence'),
});

/** Unmount RBD image from client */
export const CephClientUnmountParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Clean up orphan clones */
export const CephCloneCleanupParamsSchema = z.object({
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Delete a clone image */
export const CephCloneDeleteParamsSchema = z.object({
  clone: z.string().min(1).describe('Clone image name'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Flatten clone to remove parent dependency */
export const CephCloneFlattenParamsSchema = z.object({
  clone: z.string().min(1).describe('Clone image name'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Clone image from snapshot */
export const CephCloneImageParamsSchema = z.object({
  image: z.string().optional().describe('Source image name'),
  snapshot: z.string().min(1).describe('Source snapshot name'),
  clone: z.string().min(1).describe('Clone image name'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** List snapshot clones */
export const CephCloneListParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  snapshot: z.string().min(1).describe('Snapshot name'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Mount clone with COW overlay for read-write access */
export const CephCloneMountParamsSchema = z.object({
  clone: z.string().min(1).describe('Clone image name'),
  mountPoint: z.string().min(1).describe('Mount point path'),
  cowSize: z.string().default('10G').optional().describe('COW backing file size'),
  cowDir: z.string().default('/tmp/cowdata').optional().describe('Directory for COW files'),
  filesystem: z.string().default('btrfs').optional().describe('Filesystem type (btrfs, ext4, xfs)'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Unmount clone and cleanup COW resources */
export const CephCloneUnmountParamsSchema = z.object({
  clone: z.string().min(1).describe('Clone image name'),
  mountPoint: z.string().optional().describe('Mount point (helps with discovery)'),
  keepCow: z.boolean().optional().describe('Keep COW file to preserve changes'),
  force: z.boolean().optional().describe('Force cleanup even on errors'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Create Ceph cluster */
export const CephClusterCreateParamsSchema = z.object({
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
  nodes: z.string().optional().describe('Comma-separated node list'),
  osdDevice: z.string().optional().describe('OSD device path'),
});

/** Get dashboard URL */
export const CephClusterDashboardParamsSchema = z.object({
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Destroy Ceph cluster */
export const CephClusterDestroyParamsSchema = z.object({
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Get cluster status */
export const CephClusterStatusParamsSchema = z.object({
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Check Ceph cluster health */
export const CephHealthParamsSchema = z.object({
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Create RBD image */
export const CephImageCreateParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  size: z.string().min(1).describe('Image size'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Delete RBD image */
export const CephImageDeleteParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Format RBD image with filesystem (maps, formats, unmaps) */
export const CephImageFormatParamsSchema = z.object({
  image: z.string().min(1).describe('Image name'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  filesystem: z.string().default('btrfs').optional().describe('Filesystem type (btrfs, ext4, xfs)'),
  label: z.string().optional().describe('Filesystem label'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Get image info */
export const CephImageInfoParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** List RBD images */
export const CephImageListParamsSchema = z.object({
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Map RBD image to local device */
export const CephImageMapParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Resize RBD image */
export const CephImageResizeParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  size: z.string().min(1).describe('New image size'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Unmap RBD image from local device */
export const CephImageUnmapParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Install Ceph prerequisites */
export const CephInstallPrerequisitesParamsSchema = z.object({});

/** Create storage pool */
export const CephPoolCreateParamsSchema = z.object({
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
  pgNum: z.number().int().optional().describe('Placement group count'),
});

/** Delete storage pool */
export const CephPoolDeleteParamsSchema = z.object({
  pool: z.string().min(1).describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Get pool info */
export const CephPoolInfoParamsSchema = z.object({
  pool: z.string().min(1).describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** List storage pools */
export const CephPoolListParamsSchema = z.object({
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Get pool statistics */
export const CephPoolStatsParamsSchema = z.object({
  pool: z.string().min(1).describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Create image snapshot */
export const CephSnapshotCreateParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  snapshot: z.string().min(1).describe('Snapshot name'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Delete image snapshot */
export const CephSnapshotDeleteParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  snapshot: z.string().min(1).describe('Snapshot name'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** List image snapshots */
export const CephSnapshotListParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Protect snapshot from deletion */
export const CephSnapshotProtectParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  snapshot: z.string().min(1).describe('Snapshot name'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Rollback image to snapshot */
export const CephSnapshotRollbackParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  snapshot: z.string().min(1).describe('Snapshot name'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Unprotect snapshot for deletion */
export const CephSnapshotUnprotectParamsSchema = z.object({
  image: z.string().optional().describe('Image name (defaults to repository)'),
  snapshot: z.string().min(1).describe('Snapshot name'),
  pool: z.string().default('rbd').optional().describe('Pool name'),
  cluster: z.string().default('rediacc').optional().describe('Cluster name'),
});

/** Check CRIU checkpoint compatibility */
export const CheckpointCheckCompatParamsSchema = z.object({});

/** Clean up checkpoint files */
export const CheckpointCleanupParamsSchema = z.object({});

/** Create checkpoint of running containers */
export const CheckpointCreateParamsSchema = z.object({
  checkpointName: z.string().optional().describe('Checkpoint identifier'),
});

/** Restore containers from checkpoint */
export const CheckpointRestoreParamsSchema = z.object({
  checkpointName: z.string().optional().describe('Checkpoint identifier to restore'),
});

/** Validate checkpoint integrity */
export const CheckpointValidateParamsSchema = z.object({
  checkpointPath: z.string().optional().describe('Path to checkpoint directory'),
});

/** Execute command in container */
export const ContainerExecParamsSchema = z.object({
  container: z.string().min(1).describe('Container name'),
  command: z.string().min(1).describe('Command to run'),
  user: z.string().optional().describe('User to run as'),
  tty: z.boolean().optional().describe('Allocate TTY'),
});

/** Inspect container details */
export const ContainerInspectParamsSchema = z.object({
  container: z.string().min(1).describe('Container name'),
});

/** Kill a container */
export const ContainerKillParamsSchema = z.object({
  container: z.string().min(1).describe('Container name'),
  signal: z.string().default('SIGTERM').optional().describe('Signal to send'),
});

/** List all containers */
export const ContainerListParamsSchema = z.object({
  all: z.boolean().default(true).optional().describe('Show all containers (including stopped)'),
});

/** Get container logs */
export const ContainerLogsParamsSchema = z.object({
  container: z.string().min(1).describe('Container name'),
  lines: z.number().int().default(100).optional().describe('Number of lines to show'),
  follow: z.boolean().optional().describe('Follow log output'),
  timestamps: z.boolean().optional().describe('Show timestamps'),
});

/** Pause a container */
export const ContainerPauseParamsSchema = z.object({
  container: z.string().min(1).describe('Container name'),
});

/** Remove a container */
export const ContainerRemoveParamsSchema = z.object({
  container: z.string().min(1).describe('Container name'),
  force: z.boolean().optional().describe('Force removal'),
});

/** Restart a container */
export const ContainerRestartParamsSchema = z.object({
  container: z.string().min(1).describe('Container name'),
  timeout: z.number().int().optional().describe('Stop timeout in seconds'),
});

/** Start a container */
export const ContainerStartParamsSchema = z.object({
  container: z.string().min(1).describe('Container name'),
});

/** Get container statistics */
export const ContainerStatsParamsSchema = z.object({
  container: z.string().optional().describe('Container name (optional, all if omitted)'),
});

/** Stop a container */
export const ContainerStopParamsSchema = z.object({
  container: z.string().min(1).describe('Container name'),
  timeout: z.number().int().optional().describe('Stop timeout in seconds'),
});

/** Unpause a container */
export const ContainerUnpauseParamsSchema = z.object({
  container: z.string().min(1).describe('Container name'),
});

/** Get daemon logs */
export const DaemonLogsParamsSchema = z.object({
  lines: z.number().int().default(100).optional().describe('Number of lines to show'),
  follow: z.boolean().optional().describe('Follow log output'),
});

/** No operation (test command) */
export const DaemonNopParamsSchema = z.object({
  message: z.string().optional().describe('Optional message'),
});

/** Restart daemon */
export const DaemonRestartParamsSchema = z.object({});

/** Set up and start daemon */
export const DaemonSetupParamsSchema = z.object({});

/** Start daemon */
export const DaemonStartParamsSchema = z.object({});

/** Get daemon status */
export const DaemonStatusParamsSchema = z.object({});

/** Stop daemon */
export const DaemonStopParamsSchema = z.object({});

/** Tear down daemon */
export const DaemonTeardownParamsSchema = z.object({});

/** Wait for Docker to be ready */
export const DaemonWaitDockerParamsSchema = z.object({});

/** Expand datastore size */
export const DatastoreExpandParamsSchema = z.object({
  size: z.string().min(1).describe('Size to add'),
});

/** Initialize datastore on disk */
export const DatastoreInitParamsSchema = z.object({
  size: z.string().min(1).describe('Datastore size'),
  force: z.boolean().optional().describe('Force recreation if exists'),
});

/** Mount datastore */
export const DatastoreMountParamsSchema = z.object({});

/** Resize datastore */
export const DatastoreResizeParamsSchema = z.object({
  size: z.string().min(1).describe('New datastore size'),
});

/** Check datastore status */
export const DatastoreStatusParamsSchema = z.object({});

/** Unmount datastore */
export const DatastoreUnmountParamsSchema = z.object({});

/** Validate datastore integrity */
export const DatastoreValidateParamsSchema = z.object({});

/** Check BTRFS filesystem */
export const MachineCheckBtrfsParamsSchema = z.object({});

/** Check renet CLI installation */
export const MachineCheckCliParamsSchema = z.object({});

/** Check CRIU installation */
export const MachineCheckCriuParamsSchema = z.object({});

/** Check GPU drivers */
export const MachineCheckDriversParamsSchema = z.object({});

/** Check kernel compatibility */
export const MachineCheckKernelParamsSchema = z.object({});

/** Check system memory */
export const MachineCheckMemoryParamsSchema = z.object({});

/** Check renet installation */
export const MachineCheckRenetParamsSchema = z.object({});

/** Check if renet is set up */
export const MachineCheckSetupParamsSchema = z.object({});

/** Check sudo access */
export const MachineCheckSudoParamsSchema = z.object({});

/** Run system checks */
export const MachineCheckSystemParamsSchema = z.object({});

/** Check required tools */
export const MachineCheckToolsParamsSchema = z.object({});

/** Check user configuration */
export const MachineCheckUsersParamsSchema = z.object({
  uid: z.string().optional().describe('User ID to check'),
});

/** Fix user group membership */
export const MachineFixGroupsParamsSchema = z.object({
  uid: z.string().optional().describe('User ID to fix'),
});

/** Test SSH connectivity */
export const MachinePingParamsSchema = z.object({});

/** Test SSH connectivity */
export const MachineSshTestParamsSchema = z.object({});

/** Uninstall renet */
export const MachineUninstallParamsSchema = z.object({});

/** Get renet version */
export const MachineVersionParamsSchema = z.object({});

/** Clean up unused IP addresses */
export const NetworkCleanupIpsParamsSchema = z.object({});

/** Ensure IP addresses are allocated */
export const NetworkEnsureIpsParamsSchema = z.object({
  count: z.number().int().optional().describe('Number of IPs to ensure'),
});

/** Prune unused resources */
export const NetworkPruneParamsSchema = z.object({});

/** Get process status */
export const NetworkPsStatusParamsSchema = z.object({});

/** Start plugins */
export const PluginStartParamsSchema = z.object({});

/** Get plugin status */
export const PluginStatusParamsSchema = z.object({});

/** Stop plugins */
export const PluginStopParamsSchema = z.object({});

/** Create a new repository */
export const RepositoryCreateParamsSchema = z.object({
  size: z.string().min(1).describe('Repository size (e.g., 100G, 1T)'),
  ownerUid: z.string().optional().describe('Owner user ID'),
  tmpl: z.string().optional().describe('Base64 encoded template JSON'),
});

/** Remove a repository */
export const RepositoryDeleteParamsSchema = z.object({
  grand: z.string().optional().describe('Grand repository GUID for tracking'),
});

/** Stop repository services */
export const RepositoryDownParamsSchema = z.object({
  option: z.string().optional().describe('Shutdown options'),
  grand: z.string().optional().describe('Grand repository GUID'),
});

/** Expand a repository */
export const RepositoryExpandParamsSchema = z.object({
  size: z.string().min(1).describe('Size to add'),
});

/** Create a CoW fork of a repository */
export const RepositoryForkParamsSchema = z.object({
  tag: z.string().min(1).describe('Fork repository name'),
});

/** Get repository information */
export const RepositoryInfoParamsSchema = z.object({});

/** List repositories on machine */
export const RepositoryListParamsSchema = z.object({
  kind: z.string().default('repo').optional().describe('List type'),
  format: z.string().optional().describe('Output format'),
  from: z.string().optional().describe('Source machine or storage'),
});

/** Mount a repository */
export const RepositoryMountParamsSchema = z.object({
  checkpoint: z.boolean().optional().describe('Restore from checkpoint'),
});

/** Change repository ownership */
export const RepositoryOwnershipParamsSchema = z.object({
  ownerUid: z.string().optional().describe('New owner user ID'),
});

/** Resize a repository */
export const RepositoryResizeParamsSchema = z.object({
  size: z.string().min(1).describe('New repository size'),
});

/** Get repository status */
export const RepositoryStatusParamsSchema = z.object({});

/** Apply template to repository */
export const RepositoryTemplateApplyParamsSchema = z.object({
  tmpl: z.string().min(1).describe('Base64 encoded template JSON'),
  grand: z.string().min(1).describe('Grand repository GUID'),
});

/** Unmount a repository */
export const RepositoryUnmountParamsSchema = z.object({
  checkpoint: z.boolean().optional().describe('Create checkpoint before unmount'),
});

/** Start repository services */
export const RepositoryUpParamsSchema = z.object({
  option: z.string().optional().describe('Startup options'),
  grand: z.string().optional().describe('Grand repository GUID'),
});

/** Validate repository configuration */
export const RepositoryValidateParamsSchema = z.object({
  skipPrep: z.boolean().default(false).optional().describe('Skip preparation step'),
  skipDown: z.boolean().default(false).optional().describe('Skip down step'),
  cleanup: z.boolean().default(true).optional().describe('Cleanup after validation'),
  timeout: z.number().int().default(300).optional().describe('Validation timeout in seconds'),
});

/** Install and configure renet */
export const SetupParamsSchema = z.object({
  datastoreSize: z
    .string()
    .regex(/^\d+(%|G|T)$/)
    .default('95%')
    .optional()
    .describe('Datastore size'),
  from: z
    .enum(['apt-repo', 'tar-static', 'deb-local'])
    .default('apt-repo')
    .optional()
    .describe('Installation source'),
  rcloneSource: z
    .enum(['install-script', 'package-manager', 'manual'])
    .default('install-script')
    .optional()
    .describe('Rclone installation source'),
  dockerSource: z
    .enum(['docker-repo', 'package-manager', 'snap', 'manual'])
    .default('docker-repo')
    .optional()
    .describe('Docker installation source'),
  installAmdDriver: z
    .enum(['auto', 'true', 'false'])
    .default('auto')
    .optional()
    .describe('Install AMD driver'),
  installCriu: z
    .enum(['auto', 'true', 'false', 'manual'])
    .default('auto')
    .optional()
    .describe('Install CRIU'),
  installNvidiaDriver: z
    .enum(['auto', 'true', 'false'])
    .default('auto')
    .optional()
    .describe('Install NVIDIA driver'),
});

export const FUNCTION_SCHEMAS = {
  backup_pull: BackupPullParamsSchema,
  backup_push: BackupPushParamsSchema,
  ceph_bootstrap_cluster: CephBootstrapClusterParamsSchema,
  ceph_client_mount: CephClientMountParamsSchema,
  ceph_client_unmount: CephClientUnmountParamsSchema,
  ceph_clone_cleanup: CephCloneCleanupParamsSchema,
  ceph_clone_delete: CephCloneDeleteParamsSchema,
  ceph_clone_flatten: CephCloneFlattenParamsSchema,
  ceph_clone_image: CephCloneImageParamsSchema,
  ceph_clone_list: CephCloneListParamsSchema,
  ceph_clone_mount: CephCloneMountParamsSchema,
  ceph_clone_unmount: CephCloneUnmountParamsSchema,
  ceph_cluster_create: CephClusterCreateParamsSchema,
  ceph_cluster_dashboard: CephClusterDashboardParamsSchema,
  ceph_cluster_destroy: CephClusterDestroyParamsSchema,
  ceph_cluster_status: CephClusterStatusParamsSchema,
  ceph_health: CephHealthParamsSchema,
  ceph_image_create: CephImageCreateParamsSchema,
  ceph_image_delete: CephImageDeleteParamsSchema,
  ceph_image_format: CephImageFormatParamsSchema,
  ceph_image_info: CephImageInfoParamsSchema,
  ceph_image_list: CephImageListParamsSchema,
  ceph_image_map: CephImageMapParamsSchema,
  ceph_image_resize: CephImageResizeParamsSchema,
  ceph_image_unmap: CephImageUnmapParamsSchema,
  ceph_install_prerequisites: CephInstallPrerequisitesParamsSchema,
  ceph_pool_create: CephPoolCreateParamsSchema,
  ceph_pool_delete: CephPoolDeleteParamsSchema,
  ceph_pool_info: CephPoolInfoParamsSchema,
  ceph_pool_list: CephPoolListParamsSchema,
  ceph_pool_stats: CephPoolStatsParamsSchema,
  ceph_snapshot_create: CephSnapshotCreateParamsSchema,
  ceph_snapshot_delete: CephSnapshotDeleteParamsSchema,
  ceph_snapshot_list: CephSnapshotListParamsSchema,
  ceph_snapshot_protect: CephSnapshotProtectParamsSchema,
  ceph_snapshot_rollback: CephSnapshotRollbackParamsSchema,
  ceph_snapshot_unprotect: CephSnapshotUnprotectParamsSchema,
  checkpoint_check_compat: CheckpointCheckCompatParamsSchema,
  checkpoint_cleanup: CheckpointCleanupParamsSchema,
  checkpoint_create: CheckpointCreateParamsSchema,
  checkpoint_restore: CheckpointRestoreParamsSchema,
  checkpoint_validate: CheckpointValidateParamsSchema,
  container_exec: ContainerExecParamsSchema,
  container_inspect: ContainerInspectParamsSchema,
  container_kill: ContainerKillParamsSchema,
  container_list: ContainerListParamsSchema,
  container_logs: ContainerLogsParamsSchema,
  container_pause: ContainerPauseParamsSchema,
  container_remove: ContainerRemoveParamsSchema,
  container_restart: ContainerRestartParamsSchema,
  container_start: ContainerStartParamsSchema,
  container_stats: ContainerStatsParamsSchema,
  container_stop: ContainerStopParamsSchema,
  container_unpause: ContainerUnpauseParamsSchema,
  daemon_logs: DaemonLogsParamsSchema,
  daemon_nop: DaemonNopParamsSchema,
  daemon_restart: DaemonRestartParamsSchema,
  daemon_setup: DaemonSetupParamsSchema,
  daemon_start: DaemonStartParamsSchema,
  daemon_status: DaemonStatusParamsSchema,
  daemon_stop: DaemonStopParamsSchema,
  daemon_teardown: DaemonTeardownParamsSchema,
  daemon_wait_docker: DaemonWaitDockerParamsSchema,
  datastore_expand: DatastoreExpandParamsSchema,
  datastore_init: DatastoreInitParamsSchema,
  datastore_mount: DatastoreMountParamsSchema,
  datastore_resize: DatastoreResizeParamsSchema,
  datastore_status: DatastoreStatusParamsSchema,
  datastore_unmount: DatastoreUnmountParamsSchema,
  datastore_validate: DatastoreValidateParamsSchema,
  machine_check_btrfs: MachineCheckBtrfsParamsSchema,
  machine_check_cli: MachineCheckCliParamsSchema,
  machine_check_criu: MachineCheckCriuParamsSchema,
  machine_check_drivers: MachineCheckDriversParamsSchema,
  machine_check_kernel: MachineCheckKernelParamsSchema,
  machine_check_memory: MachineCheckMemoryParamsSchema,
  machine_check_renet: MachineCheckRenetParamsSchema,
  machine_check_setup: MachineCheckSetupParamsSchema,
  machine_check_sudo: MachineCheckSudoParamsSchema,
  machine_check_system: MachineCheckSystemParamsSchema,
  machine_check_tools: MachineCheckToolsParamsSchema,
  machine_check_users: MachineCheckUsersParamsSchema,
  machine_fix_groups: MachineFixGroupsParamsSchema,
  machine_ping: MachinePingParamsSchema,
  machine_ssh_test: MachineSshTestParamsSchema,
  machine_uninstall: MachineUninstallParamsSchema,
  machine_version: MachineVersionParamsSchema,
  network_cleanup_ips: NetworkCleanupIpsParamsSchema,
  network_ensure_ips: NetworkEnsureIpsParamsSchema,
  network_prune: NetworkPruneParamsSchema,
  network_ps_status: NetworkPsStatusParamsSchema,
  plugin_start: PluginStartParamsSchema,
  plugin_status: PluginStatusParamsSchema,
  plugin_stop: PluginStopParamsSchema,
  repository_create: RepositoryCreateParamsSchema,
  repository_delete: RepositoryDeleteParamsSchema,
  repository_down: RepositoryDownParamsSchema,
  repository_expand: RepositoryExpandParamsSchema,
  repository_fork: RepositoryForkParamsSchema,
  repository_info: RepositoryInfoParamsSchema,
  repository_list: RepositoryListParamsSchema,
  repository_mount: RepositoryMountParamsSchema,
  repository_ownership: RepositoryOwnershipParamsSchema,
  repository_resize: RepositoryResizeParamsSchema,
  repository_status: RepositoryStatusParamsSchema,
  repository_template_apply: RepositoryTemplateApplyParamsSchema,
  repository_unmount: RepositoryUnmountParamsSchema,
  repository_up: RepositoryUpParamsSchema,
  repository_validate: RepositoryValidateParamsSchema,
  setup: SetupParamsSchema,
} satisfies Record<BridgeFunctionName, z.ZodType<FunctionParamsMap[BridgeFunctionName]>>;

export function validateFunctionParams<F extends BridgeFunctionName>(
  functionName: F,
  params: unknown
): FunctionParamsMap[F] {
  const schema = FUNCTION_SCHEMAS[functionName];
  return schema.parse(params) as FunctionParamsMap[F];
}

export function safeValidateFunctionParams<F extends BridgeFunctionName>(
  functionName: F,
  params: unknown
): ZodSafeParseResult<FunctionParamsMap[F]> {
  const schema = FUNCTION_SCHEMAS[functionName];
  return schema.safeParse(params) as ZodSafeParseResult<FunctionParamsMap[F]>;
}

export function getValidationErrors<T>(result: ZodSafeParseResult<T>): string | null {
  if (result.success) return null;
  return result.error.issues
    .map((issue) => `${String(issue.path.join('.'))}: ${issue.message}`)
    .join('; ');
}

export function isValidParams<F extends BridgeFunctionName>(
  functionName: F,
  params: unknown
): params is FunctionParamsMap[F] {
  return safeValidateFunctionParams(functionName, params).success;
}
