// AUTO-GENERATED by renet bridge generate-types - DO NOT EDIT
// Run: ./go deploy prep
// Source: renet/pkg/list/types.go

// ============================================
// Machine status types from 'renet list all --json'
// ============================================

export const LIST_TYPES_VERSION = 'v0.4.92-15-g9ff518a8';

/** Storage/memory capacity information */
export interface DiskInfo {
  available: string;
  path?: string;
  total: string;
  use_percent?: string;
  used: string;
}

/** Container health check log entry */
export interface HealthLog {
  end: string;
  exit_code: number;
  output: string;
  start: string;
}

/** Container exposed port */
export interface PortInfo {
  port: string;
  protocol: string;
}

/** Container port mapping */
export interface PortMapping {
  container_port: string;
  host?: string;
  host_port?: string;
  protocol: string;
}

/** Disk partition information */
export interface Partition {
  filesystem?: string;
  mountpoint?: string;
  name: string;
  path: string;
  size_bytes: number;
  size_human: string;
}

/** Container health status */
export interface HealthInfo {
  failing_streak: number;
  log?: HealthLog[];
  status: string;
}

/** Network interface details */
export interface NetworkInterface {
  default_gateway?: string;
  ipv4_addresses: string[];
  ipv6_addresses: string[];
  mac_address: string;
  mtu: number;
  name: string;
  state: string;
}

/** Storage device information */
export interface BlockDevice {
  discard_granularity: number;
  logical_sector_size: number;
  model: string;
  name: string;
  partitions: Partition[];
  path: string;
  physical_sector_size: number;
  removable: boolean;
  serial?: string;
  size_bytes: number;
  size_human: string;
  smart_health: string;
  temperature?: number;
  type: string;
  vendor: string;
}

/** Systemd service information */
export interface ServiceInfo {
  active_since: string;
  active_state: string;
  description: string;
  load_state: string;
  main_pid: number;
  memory_current: string;
  memory_human: string;
  name: string;
  repository: string;
  restart_count: number;
  service_name: string;
  sub_state: string;
}

/** Docker container information */
export interface ContainerInfo {
  block_io?: string;
  command: string;
  cpu_percent?: string;
  created: string;
  exposed_ports?: PortInfo[];
  health?: HealthInfo;
  id: string;
  image: string;
  labels?: string;
  memory_percent?: string;
  memory_usage?: string;
  mounts?: string;
  name: string;
  net_io?: string;
  networks?: string;
  pids?: string;
  port_mappings: PortMapping[];
  ports: string;
  repository: string;
  size?: string;
  state: string;
  status: string;
}

/** Repository status information */
export interface RepositoryInfo {
  accessible: boolean;
  container_count: number;
  disk_space?: DiskInfo;
  docker_available: boolean;
  docker_running: boolean;
  external_volume_names: string[];
  external_volumes: number;
  has_rediaccfile: boolean;
  has_services: boolean;
  image_path: string;
  internal_volumes: number;
  modified: number;
  modified_human: string;
  mount_path: string;
  mounted: boolean;
  name: string;
  service_count: number;
  size: number;
  size_human: string;
  total_volumes: number;
  volume_status: string;
}

/** Network configuration */
export interface NetworkInfo {
  default_gateway?: string;
  default_interface?: string;
  interfaces: NetworkInterface[];
}

/** Systemd services summary */
export interface ServicesResult {
  active_count: number;
  failed_count: number;
  services: ServiceInfo[];
  total_count: number;
}

/** Docker containers summary */
export interface ContainersResult {
  containers: ContainerInfo[];
  docker_version?: string;
  running_count: number;
  stopped_count: number;
  total_count: number;
}

/** System information (CPU, memory, disk) */
export interface SystemInfo {
  cpu_count: number;
  cpu_model: string;
  datastore: DiskInfo;
  disk: DiskInfo;
  hostname: string;
  kernel: string;
  memory: DiskInfo;
  os_name: string;
  system_time: number;
  system_time_human: string;
  timezone: string;
  uptime: string;
}

/** Complete machine status from 'renet list all --json' */
export interface ListResult {
  block_devices: BlockDevice[];
  containers?: ContainersResult;
  network?: NetworkInfo;
  repositories: RepositoryInfo[];
  services?: ServicesResult;
  system?: SystemInfo;
  system_containers?: ContainersResult;
}

// ============================================
// Type guards and utilities
// ============================================

/**
 * Check if an object is a valid ListResult.
 * Used to detect raw format (Go bridge) vs wrapped format (previous).
 */
export function isListResult(obj: unknown): obj is ListResult {
  if (typeof obj !== 'object' || obj === null) {
    return false;
  }
  const data = obj as Record<string, unknown>;
  // ListResult has at least one of these top-level keys
  return (
    'repositories' in data ||
    'system' in data ||
    'network' in data ||
    'containers' in data ||
    'services' in data ||
    'block_devices' in data
  );
}

/**
 * Safely extract repositories from ListResult.
 */
export function getRepositories(result: ListResult): RepositoryInfo[] {
  return result.repositories ?? [];
}

/**
 * Safely extract system info from ListResult.
 */
export function getSystemInfo(result: ListResult): SystemInfo | null {
  return result.system ?? null;
}

/**
 * Safely extract containers from ListResult.
 */
export function getContainers(result: ListResult): ContainerInfo[] {
  return result.containers?.containers ?? [];
}

/**
 * Safely extract system containers from ListResult.
 */
export function getSystemContainers(result: ListResult): ContainerInfo[] {
  return result.system_containers?.containers ?? [];
}

/**
 * Safely extract services from ListResult.
 */
export function getServices(result: ListResult): ServiceInfo[] {
  return result.services?.services ?? [];
}

/**
 * Safely extract block devices from ListResult.
 */
export function getBlockDevices(result: ListResult): BlockDevice[] {
  return result.block_devices ?? [];
}

/**
 * Safely extract network interfaces from ListResult.
 */
export function getNetworkInterfaces(result: ListResult): NetworkInterface[] {
  return result.network?.interfaces ?? [];
}

/**
 * Calculate health summary from ListResult.
 */
export function getHealthSummary(result: ListResult): {
  containersHealthy: number;
  containersUnhealthy: number;
  containersNoHealth: number;
  servicesActive: number;
  servicesFailed: number;
  repositoriesMounted: number;
  repositoriesTotal: number;
} {
  const containers = getContainers(result);
  const services = getServices(result);
  const repositories = getRepositories(result);

  return {
    containersHealthy: containers.filter((c) => c.health?.status === 'healthy').length,
    containersUnhealthy: containers.filter((c) => c.health?.status === 'unhealthy').length,
    containersNoHealth: containers.filter((c) => !c.health || c.health.status === 'none').length,
    servicesActive: services.filter((s) => s.active_state === 'active').length,
    servicesFailed: services.filter((s) => s.active_state === 'failed').length,
    repositoriesMounted: repositories.filter((r) => r.mounted).length,
    repositoriesTotal: repositories.length,
  };
}
