// AUTO-GENERATED by renet bridge generate-types - DO NOT EDIT
// Run: ./go deploy prep
// Source: renet/pkg/bridge/vault/

// ============================================
// Vault structure type definitions
// ============================================

export const VAULT_SCHEMA = 'queue-vault-v2' as const;
export const VAULT_VERSION = '2.0' as const;

/** Task identification and routing */
export interface TaskSection {
  /** Function to execute */
  function: string;
  /** Target machine name */
  machine: string;
  /** Team name */
  team: string;
  /** Repository name */
  repository?: string;
}

/** SSH credentials for remote execution */
export interface SSHSection {
  /** SSH private key (plain text) */
  private_key: string;
  /** SSH public key (plain text) */
  public_key: string;
  /** Known hosts entries */
  known_hosts?: string;
  /** SSH password */
  password?: string | null;
}

/** Target machine connection details */
export interface MachineSection {
  /** IP address or hostname */
  ip: string;
  /** SSH username */
  user: string;
  /** SSH port */
  port?: number;
  /** Datastore path */
  datastore?: string;
  /** SSH known_hosts entries for this machine */
  known_hosts?: string;
}

/** Storage system configuration (rclone backends) */
export interface StorageSection {
  /** Storage backend type (s3, b2, azure, etc.) */
  backend: string;
  /** Bucket name */
  bucket?: string;
  /** Region */
  region?: string;
  /** Folder path */
  folder?: string;
  /** Additional parameters */
  parameters?: Record<string, unknown>;
}

/** Repository name and GUID mapping */
export interface RepositoryInfo {
  /** Repository GUID */
  guid: string;
  /** Repository name */
  name: string;
  /** Network ID */
  network_id?: number;
}

/** Organization and API context */
export interface ContextSection {
  /** Organization ID */
  organization_id?: string;
  /** API base URL */
  api_url?: string;
  /** Universal user ID */
  universal_user_id?: string;
  /** Universal user name */
  universal_user_name?: string;
}

/** Locale-related preferences */
export interface LocalePreferences {
  /** User's preferred language (en, de, es, fr, ja, ar, ru, tr, zh) */
  language?: string;
}

/** User preferences for task execution */
export interface PreferencesSection {
  /** Locale preferences */
  locale?: LocalePreferences;
}

/** Queue Vault V2 - Complete vault structure for queue items */
export interface QueueVaultV2 {
  $schema: typeof VAULT_SCHEMA;
  version: typeof VAULT_VERSION;
  /** Task identification and routing */
  task: TaskSection;
  /** SSH credentials for remote execution */
  ssh: SSHSection;
  /** Target machine connection details */
  machine: MachineSection;
  /** Function parameters */
  params?: Record<string, string | number | boolean>;
  /** Additional machines for multi-machine operations */
  extra_machines?: Record<string, MachineSection>;
  /** Storage system configurations */
  storage_systems?: Record<string, StorageSection>;
  /** Repository credentials by GUID */
  repository_credentials?: Record<string, string>;
  /** Repository info by name */
  repositories?: Record<string, RepositoryInfo>;
  /** Organization and API context */
  context?: ContextSection;
  /** User preferences for task execution */
  preferences?: PreferencesSection;
}

/**
 * Type guard to check if a value is a valid QueueVaultV2.
 * Performs a shallow check of schema and version.
 */
export function isQueueVaultV2(value: unknown): value is QueueVaultV2 {
  if (typeof value !== 'object' || value === null) return false;
  const v = value as Record<string, unknown>;
  return v.$schema === VAULT_SCHEMA && v.version === VAULT_VERSION;
}

/**
 * Asserts that a value is a valid QueueVaultV2.
 * Throws if the assertion fails.
 */
export function assertQueueVaultV2(value: unknown): asserts value is QueueVaultV2 {
  if (!isQueueVaultV2(value)) {
    throw new Error('Invalid QueueVaultV2: $schema or version mismatch');
  }
}
