// AUTO-GENERATED by renet bridge generate-types - DO NOT EDIT
// Run: ./go deploy prep
// Source: renet/pkg/bridge/vault/

import { z, type ZodSafeParseResult } from 'zod';
import { VAULT_SCHEMA, VAULT_VERSION } from './vault.generated';

// ============================================
// Zod schemas for vault validation
// ============================================

/** Task identification and routing */
export const TaskSectionSchema = z.object({
  function: z.string().min(1).describe('Function to execute'),
  machine: z.string().min(1).describe('Target machine name'),
  team: z.string().min(1).describe('Team name'),
  repository: z.string().optional().describe('Repository name'),
});

/** SSH credentials for remote execution */
export const SSHSectionSchema = z.object({
  private_key: z.string().min(1).describe('SSH private key (plain text)'),
  public_key: z.string().min(1).describe('SSH public key (plain text)'),
  known_hosts: z.string().optional().describe('Known hosts entries'),
  password: z.string().nullable().optional().describe('SSH password'),
});

/** Target machine connection details */
export const MachineSectionSchema = z.object({
  ip: z.string().min(1).describe('IP address or hostname'),
  user: z.string().min(1).describe('SSH username'),
  port: z.number().int().min(1).max(65535).default(22).optional().describe('SSH port'),
  datastore: z.string().optional().describe('Datastore path'),
  known_hosts: z.string().optional().describe('SSH known_hosts entries for this machine'),
});

/** Storage system configuration (rclone backends) */
export const StorageSectionSchema = z.object({
  backend: z.string().min(1).describe('Storage backend type (s3, b2, azure, etc.)'),
  bucket: z.string().optional().describe('Bucket name'),
  region: z.string().optional().describe('Region'),
  folder: z.string().optional().describe('Folder path'),
  parameters: z.record(z.string(), z.unknown()).optional().describe('Additional parameters'),
});

/** Repository name and GUID mapping */
export const RepositoryInfoSchema = z.object({
  guid: z.string().min(1).describe('Repository GUID'),
  name: z.string().min(1).describe('Repository name'),
  network_id: z.number().int().optional().describe('Network ID'),
});

/** Organization and API context */
export const ContextSectionSchema = z.object({
  organization_id: z.string().optional().describe('Organization ID'),
  api_url: z.url().optional().describe('API base URL'),
  universal_user_id: z.string().optional().describe('Universal user ID'),
  universal_user_name: z.string().optional().describe('Universal user name'),
});

/** Locale-related preferences */
export const LocalePreferencesSchema = z.object({
  language: z
    .string()
    .optional()
    .describe("User's preferred language (en, de, es, fr, ja, ar, ru, tr, zh)"),
});

/** User preferences for task execution */
export const PreferencesSectionSchema = z.object({
  locale: LocalePreferencesSchema.optional().describe('Locale preferences'),
});

/** Complete QueueVaultV2 schema */
export const QueueVaultV2Schema = z.object({
  $schema: z.literal(VAULT_SCHEMA),
  version: z.literal(VAULT_VERSION),
  task: TaskSectionSchema,
  ssh: SSHSectionSchema,
  machine: MachineSectionSchema,
  params: z
    .record(z.string(), z.union([z.string(), z.number(), z.boolean()]))
    .optional()
    .describe('Function parameters'),
  extra_machines: z
    .record(z.string(), MachineSectionSchema)
    .optional()
    .describe('Additional machines for multi-machine operations'),
  storage_systems: z
    .record(z.string(), StorageSectionSchema)
    .optional()
    .describe('Storage system configurations'),
  repository_credentials: z
    .record(z.string(), z.string())
    .optional()
    .describe('Repository credentials by GUID'),
  repositories: z
    .record(z.string(), RepositoryInfoSchema)
    .optional()
    .describe('Repository info by name'),
  context: ContextSectionSchema.optional(),
  preferences: PreferencesSectionSchema.optional(),
});

export type QueueVaultV2Type = z.infer<typeof QueueVaultV2Schema>;

export type VaultValidationResult = ZodSafeParseResult<QueueVaultV2Type>;

/**
 * Validates a queue vault object against the schema.
 * Returns a Zod SafeParseResult.
 */
export function validateQueueVault(vault: unknown): VaultValidationResult {
  return QueueVaultV2Schema.safeParse(vault);
}

/**
 * Parses and validates a queue vault, throwing on error.
 */
export function parseQueueVault(vault: unknown): QueueVaultV2Type {
  return QueueVaultV2Schema.parse(vault);
}

/**
 * Extracts validation errors from a SafeParseResult.
 */
export function getVaultValidationErrors(result: VaultValidationResult): string | null {
  if (result.success) return null;
  return result.error.issues.map((issue) => `${issue.path.join('.')}: ${issue.message}`).join('; ');
}
