export const endpoints = {
  auth: {
    createAuthenticationRequest: '/CreateAuthenticationRequest',
    forkAuthenticationRequest: '/ForkAuthenticationRequest',
    privilegeAuthenticationRequest: '/PrivilegeAuthenticationRequest',
    getRequestAuthenticationStatus: '/GetRequestAuthenticationStatus',
    isRegistered: '/IsRegistered',
    activateUserAccount: '/ActivateUserAccount',
  },
  company: {
    createCompany: '/CreateNewCompany',
    getCompanyDashboard: '/GetCompanyDashboardJson',
    getCompanyDataGraph: '/GetCompanyDataGraphJson',
    getCompanyUsers: '/GetCompanyUsers',
    getCompanyPermissionGroups: '/GetCompanyPermissionGroups',
    getCompanyRegions: '/GetCompanyRegions',
    getCompanyTeams: '/GetCompanyTeams',
    getCompanyVault: '/GetCompanyVault',
    getCompanyVaults: '/GetCompanyVaults',
    updateCompanyVault: '/UpdateCompanyVault',
    updateCompanyVaults: '/UpdateCompanyVaults',
    updateCompanyVaultProtocol: '/UpdateCompanyVaultProtocol',
    updateCompanyBlockUserRequests: '/UpdateCompanyBlockUserRequests',
    exportCompanyData: '/ExportCompanyData',
    importCompanyData: '/ImportCompanyData',
    getLookupData: '/GetLookupData',
    getUserCompany: '/GetUserCompany',
  },
  users: {
    createUser: '/CreateNewUser',
    updateUserAssignedPermissions: '/UpdateUserAssignedPermissions',
    updateUserEmail: '/UpdateUserEmail',
    updateUserLanguage: '/UpdateUserLanguage',
    updateUserPassword: '/UpdateUserPassword',
    updateUserToActivated: '/UpdateUserToActivated',
    updateUserToDeactivated: '/UpdateUserToDeactivated',
    updateUserVault: '/UpdateUserVault',
    getUserVault: '/GetUserVault',
    getUserRequests: '/GetUserRequests',
    updateUserTfa: '/UpdateUserTFA',
    deleteUserRequest: '/DeleteUserRequest',
  },
  permissions: {
    createPermissionGroup: '/CreatePermissionGroup',
    deletePermissionGroup: '/DeletePermissionGroup',
    createPermissionInGroup: '/CreatePermissionInGroup',
    deletePermissionFromGroup: '/DeletePermissionFromGroup',
    getPermissionGroupDetails: '/GetPermissionGroupDetails',
  },
  teams: {
    createTeam: '/CreateTeam',
    deleteTeam: '/DeleteTeam',
    updateTeamName: '/UpdateTeamName',
    updateTeamVault: '/UpdateTeamVault',
    createTeamMembership: '/CreateTeamMembership',
    deleteUserFromTeam: '/DeleteUserFromTeam',
    getTeamMembers: '/GetTeamMembers',
  },
  regions: {
    createRegion: '/CreateRegion',
    deleteRegion: '/DeleteRegion',
    updateRegionName: '/UpdateRegionName',
    updateRegionVault: '/UpdateRegionVault',
    getRegionBridges: '/GetRegionBridges',
  },
  bridges: {
    createBridge: '/CreateBridge',
    deleteBridge: '/DeleteBridge',
    updateBridgeName: '/UpdateBridgeName',
    updateBridgeVault: '/UpdateBridgeVault',
    resetBridgeAuthorization: '/ResetBridgeAuthorization',
  },
  machines: {
    createMachine: '/CreateMachine',
    deleteMachine: '/DeleteMachine',
    updateMachineName: '/UpdateMachineName',
    updateMachineVault: '/UpdateMachineVault',
    getTeamMachines: '/GetTeamMachines',
    getMachineAssignmentStatus: '/GetMachineAssignmentStatus',
    updateMachineAssignedBridge: '/UpdateMachineAssignedBridge',
    updateMachineClusterAssignment: '/UpdateMachineClusterAssignment',
    updateMachineClusterRemoval: '/UpdateMachineClusterRemoval',
    updateMachineCloneAssignment: '/UpdateMachineCloneAssignment',
    updateCloneMachineAssignments: '/UpdateCloneMachineAssignments',
    updateCloneMachineRemovals: '/UpdateCloneMachineRemovals',
    updateMachineDistributedStorage: '/UpdateMachineDistributedStorage',
    updateImageMachineAssignment: '/UpdateImageMachineAssignment',
    getCloneMachines: '/GetCloneMachines',
    getCloneMachineAssignmentValidation: '/GetCloneMachineAssignmentValidation',
    getAvailableMachinesForClone: '/GetAvailableMachinesForClone',
  },
  repos: {
    getTeamRepos: '/GetTeamRepositories',
    createRepo: '/CreateRepository',
    updateRepoName: '/UpdateRepositoryName',
    updateRepoTag: '/UpdateRepositoryTag',
    updateRepoVault: '/UpdateRepositoryVault',
    deleteRepo: '/DeleteRepository',
    promoteRepoToGrand: '/PromoteRepositoryToGrand',
  },
  storage: {
    getTeamStorages: '/GetTeamStorages',
    createStorage: '/CreateStorage',
    updateStorageName: '/UpdateStorageName',
    updateStorageVault: '/UpdateStorageVault',
    deleteStorage: '/DeleteStorage',
  },
  queue: {
    createQueueItem: '/CreateQueueItem',
    getTeamQueueItems: '/GetTeamQueueItems',
    getQueueItemsNext: '/GetQueueItemsNext',
    updateQueueItemResponse: '/UpdateQueueItemResponse',
    updateQueueItemToCompleted: '/UpdateQueueItemToCompleted',
    updateQueueItemPriority: '/UpdateQueueItemPriority',
    updateQueueItemProtection: '/UpdateQueueItemProtection',
    cancelQueueItem: '/CancelQueueItem',
    deleteQueueItem: '/DeleteQueueItem',
    retryFailedQueueItem: '/RetryFailedQueueItem',
    getQueueItemTrace: '/GetQueueItemTrace',
  },
  distributedStorage: {
    createCluster: '/CreateDistributedStorageCluster',
    deleteCluster: '/DeleteDistributedStorageCluster',
    getClusters: '/GetDistributedStorageClusters',
    getClusterMachines: '/GetDistributedStorageClusterMachines',
    updateClusterVault: '/UpdateDistributedStorageClusterVault',
    createPool: '/CreateDistributedStoragePool',
    deletePool: '/DeleteDistributedStoragePool',
    getPools: '/GetDistributedStoragePools',
    updatePoolVault: '/UpdateDistributedStoragePoolVault',
    createRbdImage: '/CreateDistributedStorageRbdImage',
    deleteRbdImage: '/DeleteDistributedStorageRbdImage',
    getRbdImages: '/GetDistributedStorageRbdImages',
    createRbdSnapshot: '/CreateDistributedStorageRbdSnapshot',
    deleteRbdSnapshot: '/DeleteDistributedStorageRbdSnapshot',
    getRbdSnapshots: '/GetDistributedStorageRbdSnapshots',
    createRbdClone: '/CreateDistributedStorageRbdClone',
    deleteRbdClone: '/DeleteDistributedStorageRbdClone',
    getRbdClones: '/GetDistributedStorageRbdClones',
  },
  audit: {
    getAuditLogs: '/GetAuditLogs',
    getEntityAuditTrace: '/GetEntityAuditTrace',
    getEntityHistory: '/GetEntityHistory',
  },
  base: {
    storedProcedure: '/StoredProcedure',
  },
} as const;

export type EndpointCategories = typeof endpoints;
