name: Generate GitHub App Token
description: >
  Generates a short-lived GitHub App installation token with preset-based
  permission scoping. Replaces long-lived GH_PAT for CI/CD operations.

inputs:
  app-id:
    description: GitHub App ID
    required: true
  private-key:
    description: GitHub App private key (PEM)
    required: true
  preset:
    description: >
      Permission preset: readonly (contents:read), ci (contents:write +
      pull_requests:read + actions:write), cd (contents:write +
      pull_requests:write + actions:write)
    required: false
    default: readonly
  repositories:
    description: >
      Comma-separated list of repository names (without owner) to scope the
      token to. If not set, the token is scoped to all repositories the app
      is installed on. Use the narrowest scope needed for the job.
    required: false

outputs:
  token:
    description: GitHub App installation token
    value: ${{ steps.token.outputs.token }}

runs:
  using: composite
  steps:
    - name: Resolve permissions from preset
      id: perms
      shell: bash
      run: |
        case "${{ inputs.preset }}" in
          readonly)
            echo "perm-contents=read" >> "$GITHUB_OUTPUT"
            ;;
          ci)
            echo "perm-contents=write" >> "$GITHUB_OUTPUT"
            echo "perm-pull-requests=read" >> "$GITHUB_OUTPUT"
            echo "perm-actions=write" >> "$GITHUB_OUTPUT"
            echo "perm-statuses=write" >> "$GITHUB_OUTPUT"
            ;;
          cd)
            echo "perm-contents=write" >> "$GITHUB_OUTPUT"
            echo "perm-pull-requests=write" >> "$GITHUB_OUTPUT"
            echo "perm-actions=write" >> "$GITHUB_OUTPUT"
            ;;
          *)
            echo "::error::Unknown preset: ${{ inputs.preset }}"
            exit 1
            ;;
        esac

    - name: Generate token
      id: token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ github.repository_owner }}
        repositories: ${{ inputs.repositories }}
        permission-contents: ${{ steps.perms.outputs.perm-contents }}
        permission-pull-requests: ${{ steps.perms.outputs.perm-pull-requests }}
        permission-actions: ${{ steps.perms.outputs.perm-actions }}
        permission-statuses: ${{ steps.perms.outputs.perm-statuses }}
