#!/bin/bash
# Check that license schema is up-to-date between TypeScript and Go
# With integrated autofix for PRs
#
# Usage:
#   .ci/scripts/quality/check-license-schema.sh
#
# Environment variables:
#   GITHUB_EVENT_NAME - GitHub event type (e.g., 'pull_request')
#   GITHUB_HEAD_REF - PR branch name (set by GitHub Actions)
#   PR_AUTHOR - GitHub username of the PR author (optional, falls back to github-actions[bot])
#
# Exit codes:
#   0 - Schema is up-to-date (or auto-fixed on PR)
#   1 - Stale schema detected (and could not auto-fix)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

REPO_ROOT="$(get_repo_root)"
SCHEMA_FILE="$REPO_ROOT/packages/shared/src/license/schema.generated.json"
RENET_DIR="$REPO_ROOT/private/renet"

cd "$REPO_ROOT"

# Phase 1: Generate fresh schema and check for changes
log_step "Generating fresh license schema..."
TEMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TEMP_DIR"' EXIT

# Copy current schema for comparison
if [[ -f "$SCHEMA_FILE" ]]; then
    cp "$SCHEMA_FILE" "$TEMP_DIR/schema.before.json"
fi

# Generate fresh schema
npx tsx packages/shared/scripts/generate-license-schema.ts

# Format the generated schema to match biome's style
npx biome format --write "$SCHEMA_FILE" >/dev/null 2>&1 || true

# Check if schema changed
if [[ -f "$TEMP_DIR/schema.before.json" ]] && diff -q "$SCHEMA_FILE" "$TEMP_DIR/schema.before.json" >/dev/null 2>&1; then
    log_info "License schema is up-to-date"
else
    log_warn "License schema was regenerated (file changed)"
fi

# Phase 2: Run Go tests to validate schema consistency
if [[ ! -d "$RENET_DIR" ]]; then
    log_warn "Renet submodule not available, skipping Go validation"
    exit 0
fi

log_step "Running Go schema validation tests..."
cd "$RENET_DIR"

if ! go test ./pkg/license/... -run 'TestGoTypesMatchTypeScriptSchema|TestGoConstantsMatchTypeScriptSchema|TestSchemaVersion|TestPlanResourcesConsistency|TestPlanFeaturesConsistency' -v; then
    log_error "Go types do not match TypeScript schema!"
    log_error ""
    log_error "This means the license types are out of sync between TypeScript and Go."
    log_error "To fix:"
    log_error "  1. Update Go types in private/renet/pkg/license/types.go to match TypeScript"
    log_error "  2. Run: npm run generate:license-schema"
    log_error "  3. Run: cd private/renet && go test ./pkg/license/... -run TestGoTypesMatchTypeScriptSchema -v"
    exit 1
fi

log_info "Go types match TypeScript schema"

# Phase 3: Check if schema file needs to be committed
cd "$REPO_ROOT"
if ! git diff --quiet "$SCHEMA_FILE" 2>/dev/null; then
    log_warn "Schema file has uncommitted changes"

    # Check if we can auto-fix
    if [[ "${GITHUB_EVENT_NAME:-}" != "pull_request" ]] || [[ -z "${GITHUB_HEAD_REF:-}" ]]; then
        log_error "Cannot auto-fix outside PR context"
        log_error "Run: npm run generate:license-schema"
        log_error "Then commit the changes"
        exit 1
    fi

    # Check for recent autofix commits to prevent loops
    RECENT_AUTOFIX=$(git log --oneline -5 --grep="auto-regenerate license schema" 2>/dev/null | head -1 || true)
    if [[ -n "$RECENT_AUTOFIX" ]]; then
        log_error "Recent license schema autofix commit detected, cannot auto-fix again: $RECENT_AUTOFIX"
        log_error "Please manually regenerate schema with: npm run generate:license-schema"
        exit 1
    fi

    # Phase 4: Commit the fix
    log_step "Committing schema fix..."
    if [[ -n "${PR_AUTHOR:-}" ]]; then
        git config user.name "$PR_AUTHOR"
        git config user.email "${PR_AUTHOR}@users.noreply.github.com"
    else
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    fi
    git add "$SCHEMA_FILE"
    git commit -m "$(cat <<'EOF'
chore(license): auto-regenerate license schema

Automatically regenerated by CI.
EOF
)"
    git push origin "HEAD:${GITHUB_HEAD_REF}"

    log_info "Schema fixed and committed"
fi

exit 0
