#!/bin/bash
# Check that renet-generated TypeScript types are up-to-date
# With integrated autofix for PRs
#
# Usage:
#   .ci/scripts/quality/check-renet-types.sh
#
# Environment variables:
#   GITHUB_EVENT_NAME - GitHub event type (e.g., 'pull_request')
#   GITHUB_HEAD_REF - PR branch name (set by GitHub Actions)
#
# Exit codes:
#   0 - Types are up-to-date (or auto-fixed on PR)
#   1 - Stale types detected (and could not auto-fix)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

REPO_ROOT="$(get_repo_root)"
RENET_DIR="$REPO_ROOT/private/renet"
OUTPUT_DIR="$REPO_ROOT/packages/shared/src/queue-vault/data"

cd "$REPO_ROOT"

if [[ ! -d "$RENET_DIR" ]]; then
    log_warn "Renet submodule not available, skipping"
    exit 0
fi

# Build renet
log_step "Building renet..."
(cd "$RENET_DIR" && go build -o bin/renet ./cmd/renet)

# Helper function - compare files ignoring version string
compare_ignoring_version() {
    local file1="$1"
    local file2="$2"
    diff -q <(grep -v '_VERSION = ' "$file1") <(grep -v '_VERSION = ' "$file2") >/dev/null 2>&1
}

FILES=(
    "functions.generated.ts"
    "functions.schema.ts"
    "vault.generated.ts"
    "vault.schema.ts"
    "list-types.generated.ts"
)

# Phase 1: Check types
log_step "Checking types freshness..."
TEMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TEMP_DIR"' EXIT

VERSION=$(cd "$REPO_ROOT" && git describe --tags --always 2>/dev/null || echo "dev")
"$RENET_DIR/bin/renet" bridge generate-types --output "$TEMP_DIR" --version "$VERSION"

STALE=()
for file in "${FILES[@]}"; do
    if [[ -f "$TEMP_DIR/$file" ]] && ! compare_ignoring_version "$OUTPUT_DIR/$file" "$TEMP_DIR/$file"; then
        STALE+=("$file")
    fi
done

if [[ ${#STALE[@]} -eq 0 ]]; then
    log_info "Renet types are up-to-date"
    exit 0
fi

# Check failed
log_warn "Stale types detected: ${STALE[*]}"

# Phase 2: Check if fixable context
if [[ "${GITHUB_EVENT_NAME:-}" != "pull_request" ]] || [[ -z "${GITHUB_HEAD_REF:-}" ]]; then
    log_error "Cannot auto-fix outside PR context"
    log_error "Run: ./go deploy prep"
    exit 1
fi

# Check for recent autofix commits to prevent loops (specific to renet types)
RECENT_AUTOFIX=$(git log --oneline -5 --author="github-actions\[bot\]" --grep="auto-regenerate renet bridge types" 2>/dev/null | head -1 || true)
if [[ -n "$RECENT_AUTOFIX" ]]; then
    log_error "Recent renet types autofix commit detected, cannot auto-fix again: $RECENT_AUTOFIX"
    log_error "Please manually regenerate types with: ./go deploy prep"
    exit 1
fi

# Phase 3: Apply fix (regenerate to actual output dir)
log_step "Regenerating types..."
"$RENET_DIR/bin/renet" bridge generate-types --output "$OUTPUT_DIR" --version "$VERSION"

# Phase 4: Verify fix
log_step "Verifying fix..."
rm -rf "$TEMP_DIR"
TEMP_DIR="$(mktemp -d)"
"$RENET_DIR/bin/renet" bridge generate-types --output "$TEMP_DIR" --version "$VERSION"

STILL_STALE=()
for file in "${FILES[@]}"; do
    if [[ -f "$TEMP_DIR/$file" ]] && ! compare_ignoring_version "$OUTPUT_DIR/$file" "$TEMP_DIR/$file"; then
        STILL_STALE+=("$file")
    fi
done

if [[ ${#STILL_STALE[@]} -gt 0 ]]; then
    log_error "Types still stale after fix: ${STILL_STALE[*]}"
    exit 1
fi

# Phase 5: Commit if changes
if git diff --quiet "$OUTPUT_DIR/" 2>/dev/null; then
    log_info "Fix verified, no commit needed"
    exit 0
fi

log_step "Committing fix..."
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add "$OUTPUT_DIR/"
git commit -m "$(cat <<'EOF'
chore(types): auto-regenerate renet bridge types

Automatically regenerated by CI.
EOF
)"
git push origin "HEAD:${GITHUB_HEAD_REF}"

log_info "Types fixed and committed"
exit 0
