#!/usr/bin/env python3
"""Port of `.ci/scripts/pr/sync-epic-block.sh`.

Syncs the worklist epic block into a PR description. Reads the published
snapshot (`agent/pr/<branch>.md`, written by `worklist.py --publish`) and
rebuilds a delimited block in the PR body between `<!-- worklist-epics:begin
-->` and `<!-- worklist-epics:end -->`, stripping any previous instance of the
same block first. See the twin's own header for why the marker pair is
distinct from the other two writers that append a block to this repo's PR
bodies (`refresh-pr-body.sh`, `submodule-prs.sh`).

Usage: sync_epic_block.py <pr-number> <branch> [--dry-run]

PORT NOTES.

EVERY EXTERNAL CALL'S STREAMS ARE ROUTED EXACTLY AS THE TWIN ROUTES THEM, not
uniformly captured, because the twin's own error handling depends on which
stream is redirected where:

  * `git rev-parse --show-toplevel`: only stdout is captured (`$(...)`);
    stderr is inherited. A failure (not a git repo) prints git's OWN fatal
    message directly to the real stderr and the script exits with git's exit
    code under `set -e` -- nothing here fabricates that message, so it reads
    identically on both sides because it is the identical `git` binary.
  * `gh pr view ... --jq '.body // ""'`: stdout is captured (redirected to a
    file in the twin); stderr is inherited. Same failure shape as above.
  * `gh pr edit ... --body-file ...`: NEITHER stream is redirected in the
    twin. Its own success output (a PR URL, typically) reaches the real
    stdout exactly where the twin's final `echo` would otherwise be the last
    line -- a port that captured this call's output would silently swallow
    that, the same defect class the `ci_stop_elite` port paid for with
    `docker stop`/`rm`'s echoed name.

`_section` TRANSLITERATES `sed '1{/^<!-- generated by worklist.py/d;}; /^# Work
in /d' "$SNAP"` AS CAPTURED INTO A SHELL VARIABLE, not as sed's own raw file
output. The twin assigns sed's result with `SECTION="$(sed ...)"`, and command
substitution strips ALL trailing newlines regardless of how many sed produced
or whether the source file's last line was itself newline-terminated -- so
this function returns a string with its line-filtering applied and no
trailing newline, never mind what sed literally emitted byte for byte.

`_strip_existing_block` TRANSLITERATES THE awk MARKER STRIP AS A RAW FILE,
by contrast, because the twin's `cat "$work/body-stripped.md"` reads that
file's actual bytes with no variable capture in between. AWK's default record
handling means a file that ends with a real trailing newline and one that
does not both yield the SAME set of records, and `print` appends the output
record separator (a newline) after every record it emits -- so the return
value here always ends with exactly one trailing newline when any lines
survive the strip, and is the empty string when none do, independent of the
input's own trailing-newline state.

`argv[2]` (`DRY`) MIRRORS `"${3:-}"`: absent third argument reads as the
empty string, not `None`, and only the literal string `--dry-run` arms the
dry-run path -- any other third argument is silently ignored, same as the
twin (`"${DRY}" == "--dry-run"` is the only comparison, there is no `else`
branch that rejects an unrecognised value).
"""

from __future__ import annotations

import pathlib
import shutil
import subprocess
import sys
import tempfile

BEGIN = "<!-- worklist-epics:begin -->"
END = "<!-- worklist-epics:end -->"

USAGE = """usage: sync-epic-block.sh <pr-number> <branch> [--dry-run]

Rebuilds the worklist epic block in a PR description from
agent/pr/<branch>.md. With --dry-run the new body goes to stdout and
nothing is written.
"""


def _section(snap_text: str) -> str:
    """`sed '1{/^<!-- generated by worklist.py/d;}; /^# Work in /d'`, captured
    into a shell-variable-shaped value (all trailing newlines stripped)."""
    lines = snap_text.splitlines()
    if lines and lines[0].startswith("<!-- generated by worklist.py"):
        lines = lines[1:]
    lines = [line for line in lines if not line.startswith("# Work in ")]
    return "\n".join(lines)


def _strip_existing_block(body: str) -> str:
    """`awk -v b=BEGIN -v e=END '$0==b{skip=1;next} $0==e{skip=0;next}
    !skip{print}'`, as the RAW file awk would have written: each kept line
    followed by a newline, empty string if nothing survives."""
    kept = []
    skip = False
    for line in body.splitlines():
        if line == BEGIN:
            skip = True
            continue
        if line == END:
            skip = False
            continue
        if not skip:
            kept.append(line)
    return "".join(line + "\n" for line in kept)


def _relative_to(path: pathlib.Path, root: pathlib.Path) -> str:
    """`${SNAP#"$REPO_ROOT"/}` -- strip the exact `<root>/` prefix; if the
    path does not start with it (should not happen), the twin's parameter
    expansion is a no-op and the original string passes through unchanged."""
    return str(path).removeprefix(str(root) + "/")


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        sys.stderr.write(USAGE)
        return 2

    pr = argv[0]
    branch = argv[1]
    dry = argv[2] if len(argv) > 2 else ""

    toplevel = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        stdout=subprocess.PIPE,
        stderr=None,
        text=True,
        check=False,
    )
    if toplevel.returncode != 0:
        return toplevel.returncode
    repo_root = pathlib.Path(toplevel.stdout.rstrip("\n"))

    snap = repo_root / "agent" / "pr" / f"{branch.replace('/', '-')}.md"

    if not snap.is_file():
        print(f"✗ no snapshot at {_relative_to(snap, repo_root)}", file=sys.stderr)
        print(f"  run: worklist.py --publish <me> {branch}", file=sys.stderr)
        return 1

    section = _section(snap.read_text(encoding="utf-8"))

    work = pathlib.Path(tempfile.mkdtemp())
    try:
        if dry == "--dry-run":
            body_old = ""
        else:
            view = subprocess.run(
                ["gh", "pr", "view", pr, "--json", "body", "--jq", '.body // ""'],
                stdout=subprocess.PIPE,
                stderr=None,
                text=True,
                check=False,
            )
            if view.returncode != 0:
                return view.returncode
            body_old = view.stdout

        body_stripped = _strip_existing_block(body_old)

        body_new = (
            body_stripped
            + "\n"
            + BEGIN
            + "\n"
            + "## Work in this PR\n\n"
            + section
            + "\n"
            + END
            + "\n"
        )

        if dry == "--dry-run":
            sys.stdout.write(body_new)
            return 0

        body_new_path = work / "body-new.md"
        body_new_path.write_text(body_new, encoding="utf-8")

        edit = subprocess.run(
            ["gh", "pr", "edit", pr, "--body-file", str(body_new_path)],
            stdout=None,
            stderr=None,
            check=False,
        )
        if edit.returncode != 0:
            return edit.returncode

        print(f"✓ epic block synced into PR #{pr} from {_relative_to(snap, repo_root)}")
        return 0
    finally:
        # `trap 'rm -rf "$work"' EXIT` in the twin.
        shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
