#!/bin/bash
# Service environment setup
# Generates secrets for the rediacc/web service mode
#
# Usage:
#   source .ci/docker/service/env.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONSOLE_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Source common utilities
source "$CONSOLE_ROOT/.ci/scripts/lib/common.sh"

# =============================================================================
# SECRET GENERATION (same patterns as ci-env.sh)
# =============================================================================

# Generate Ed25519 key pair for subscription signing
if [[ -z "${ED25519_PRIVATE_KEY:-}" ]]; then
    log_step "Generating Ed25519 key pair..."
    KEYS=$(node -e "
        const crypto = require('crypto');
        const { privateKey, publicKey } = crypto.generateKeyPairSync('ed25519');
        console.log(JSON.stringify({
            private: privateKey.export({type:'pkcs8',format:'der'}).toString('base64'),
            public: publicKey.export({type:'spki',format:'der'}).toString('base64')
        }));
    ")
    ED25519_PRIVATE_KEY=$(echo "$KEYS" | node -e "process.stdout.write(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8')).private)")
    ED25519_PUBLIC_KEY=$(echo "$KEYS" | node -e "process.stdout.write(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8')).public)")
fi
export ED25519_PRIVATE_KEY ED25519_PUBLIC_KEY

# Account server API key (min 32 chars)
export ACCOUNT_SERVER_API_KEY="${ACCOUNT_SERVER_API_KEY:-$(openssl rand -base64 48 | tr -d '/+=' | cut -c1-64)}"

# JWT secret (min 32 chars)
export JWT_SECRET="${JWT_SECRET:-$(openssl rand -base64 48 | tr -d '/+=' | cut -c1-64)}"

# RustFS credentials
export RUSTFS_ACCESS_KEY="${RUSTFS_ACCESS_KEY:-rustfsadmin}"
export RUSTFS_SECRET_KEY="${RUSTFS_SECRET_KEY:-rustfsadmin}"

# Account admin (first user to register with this email gets admin role)
export ADMIN_EMAIL="${ADMIN_EMAIL:-admin@rediacc.io}"

# Service configuration
export SERVICE_HTTP_PORT="${SERVICE_HTTP_PORT:-8080}"
export SERVICE_RUSTFS_CONSOLE_PORT="${SERVICE_RUSTFS_CONSOLE_PORT:-9001}"
export SERVICE_TAG="${SERVICE_TAG:-local}"
export SYSTEM_DOMAIN="${SYSTEM_DOMAIN:-localhost}"

# =============================================================================
# PERSIST TO .env FILE
# =============================================================================
{
    echo "# Auto-generated by env.sh -- do not edit"
    echo "ED25519_PRIVATE_KEY=${ED25519_PRIVATE_KEY}"
    echo "ED25519_PUBLIC_KEY=${ED25519_PUBLIC_KEY}"
    echo "ACCOUNT_SERVER_API_KEY=${ACCOUNT_SERVER_API_KEY}"
    echo "JWT_SECRET=${JWT_SECRET}"
    echo "RUSTFS_ACCESS_KEY=${RUSTFS_ACCESS_KEY}"
    echo "RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY}"
    echo "SERVICE_HTTP_PORT=${SERVICE_HTTP_PORT}"
    echo "SERVICE_RUSTFS_CONSOLE_PORT=${SERVICE_RUSTFS_CONSOLE_PORT}"
    echo "SERVICE_TAG=${SERVICE_TAG}"
    echo "SYSTEM_DOMAIN=${SYSTEM_DOMAIN}"
    echo "ADMIN_EMAIL=${ADMIN_EMAIL}"
} >"$SCRIPT_DIR/.env"

log_info "Service environment configured"
log_info "  Web port: $SERVICE_HTTP_PORT"
log_info "  RustFS console port: $SERVICE_RUSTFS_CONSOLE_PORT"
