name: 'Cancel Workflow on Failure'
description: 'Cancels the entire workflow run if the current job fails'

runs:
  using: 'composite'
  steps:
    - name: Cancel workflow run
      if: failure()
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd  # v8
      with:
        script: |
          console.log('Job failed - cancelling workflow run...');
          await github.rest.actions.cancelWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          });
