name: Security Vulnerability Report
description: Report a security issue in the Rediacc Console (Please consider responsible disclosure)
title: "[Security] "
labels: ["security", "priority-critical"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ IMPORTANT: Security Notice**
        
        Thank you for helping us keep Rediacc Console secure! 
        
        Please DO NOT include:
        - Actual exploit code
        - Sensitive data or credentials
        - Production URLs or API endpoints
        
        For critical vulnerabilities, consider contacting the security team directly before public disclosure.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Assessment
      description: CVSS severity level
      options:
        - Critical (9.0-10.0) - Remote code execution, data breach
        - High (7.0-8.9) - Privilege escalation, significant data exposure
        - Medium (4.0-6.9) - Limited data exposure, requires user interaction
        - Low (0.1-3.9) - Minor information disclosure
    validations:
      required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: Category of the security issue
      options:
        - Authentication Bypass
        - Authorization/Access Control
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - SQL Injection
        - API Security
        - Sensitive Data Exposure
        - Cryptography/Encryption Issue
        - Session Management
        - Input Validation
        - Other
      multiple: true
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security issue
      placeholder: |
        The application allows...
        An attacker could...
        This vulnerability permits...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What could an attacker achieve?
      placeholder: |
        An attacker could:
        - Access unauthorized data
        - Modify user permissions
        - Execute arbitrary code
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How to trigger the vulnerability (be general, avoid specifics)
      value: |
        1. Login as a regular user
        2. Navigate to affected component
        3. Perform action that triggers vulnerability
        4. Observe security issue
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the console are affected?
      placeholder: |
        - Authentication system
        - API client (src/api/client.ts)
        - Vault encryption
        - State management
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: How could this be fixed?
      placeholder: |
        - Implement input validation
        - Add authorization checks
        - Update encryption method

  - type: input
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which console versions are affected?
      placeholder: e.g., 1.0.0 - 1.2.3

  - type: dropdown
    id: disclosure-timeline
    attributes:
      label: Disclosure Timeline
      description: Have you disclosed this elsewhere?
      options:
        - This is the first disclosure
        - Planning to disclose publicly in 90 days
        - Already disclosed privately to team
        - Urgent - Active exploitation detected
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Responsible Disclosure
      options:
        - label: I have not included exploit code or sensitive data
          required: true
        - label: I agree to coordinated disclosure
          required: true
        - label: I have reviewed existing security advisories
          required: true