#!/bin/bash
# Account service development functions
# Sourced lazily by run.sh when 'account' command is invoked
#
# Provides: account_dev, account_stop, account_test, account_reset

# Prevent re-sourcing
[[ -n "${ACCOUNT_LIB_LOADED:-}" ]] && return 0
readonly ACCOUNT_LIB_LOADED=1

# Source port utilities
source "$CI_LIB_DIR/find-port.sh"

# =============================================================================
# INTERNAL HELPERS
# =============================================================================

ACCOUNT_DIR="$CONSOLE_ROOT_DIR/private/account"
ACCOUNT_PIDS=()

account_cleanup() {
    local exit_code=$?
    for pid in "${ACCOUNT_PIDS[@]}"; do
        kill "$pid" 2>/dev/null || true
        wait "$pid" 2>/dev/null || true
    done
    ACCOUNT_PIDS=()
    exit "$exit_code"
}

# Find 3 consecutive free ports starting from preferred base
account_allocate_ports() {
    local base
    base=$(find_preferred_port "$ACCOUNT_DEV_PORT_PREFERRED" \
        "$ACCOUNT_DEV_PORT_PREFERRED" "$ACCOUNT_DEV_PORT_RANGE_END")

    # Verify next 2 ports are also free; if not, scan for 3 consecutive
    if is_port_in_use $((base + 1)) || is_port_in_use $((base + 2)); then
        local found=false
        for candidate in $(seq "$ACCOUNT_DEV_PORT_PREFERRED" "$ACCOUNT_DEV_PORT_RANGE_END"); do
            if ! is_port_in_use "$candidate" &&
                ! is_port_in_use $((candidate + 1)) &&
                ! is_port_in_use $((candidate + 2)); then
                base=$candidate
                found=true
                break
            fi
        done
        if [[ "$found" != "true" ]]; then
            log_error "Cannot find 3 consecutive free ports in range ${ACCOUNT_DEV_PORT_PREFERRED}-${ACCOUNT_DEV_PORT_RANGE_END}"
            exit 1
        fi
    fi

    GATEWAY_PORT=$base
    VITE_PORT=$((base + 1))
    ASTRO_PORT=$((base + 2))
    export GATEWAY_PORT VITE_PORT ASTRO_PORT
}

# Wait for a port to become active (max timeout seconds)
account_wait_port() {
    local port="$1"
    local name="$2"
    local timeout="${3:-30}"
    local elapsed=0

    while [[ $elapsed -lt $timeout ]]; do
        if is_port_in_use "$port"; then
            return 0
        fi
        sleep 1
        elapsed=$((elapsed + 1))
    done

    log_error "$name failed to start on port $port within ${timeout}s"
    log_info "Check logs: $ACCOUNT_LOG_DIR/"
    return 1
}

# =============================================================================
# ENSURE .ENV
# =============================================================================

account_generate_crypto_keys() {
    # Ed25519
    local keys
    keys=$(node --eval "
        const crypto = require('crypto');
        const { privateKey, publicKey } = crypto.generateKeyPairSync('ed25519');
        const priv = privateKey.export({ type: 'pkcs8', format: 'der' }).toString('base64');
        const pub = publicKey.export({ type: 'spki', format: 'der' }).toString('base64');
        process.stdout.write(priv + '\n' + pub);
    ")
    ED25519_PRIV=$(echo "$keys" | head -1)
    ED25519_PUB=$(echo "$keys" | tail -1)

    # X25519
    local x25519_keys
    x25519_keys=$(node --eval "
        const crypto = require('crypto');
        const { privateKey, publicKey } = crypto.generateKeyPairSync('x25519');
        const priv = privateKey.export({ type: 'pkcs8', format: 'der' }).toString('base64');
        const pub = publicKey.export({ type: 'spki', format: 'der' }).toString('base64');
        process.stdout.write(priv + '\n' + pub);
    ")
    X25519_PRIV=$(echo "$x25519_keys" | head -1)
    X25519_PUB=$(echo "$x25519_keys" | tail -1)

    # Random secrets
    JWT_SEC=$(openssl rand -base64 48 | tr -d '/+=' | cut -c1-64)
    API_K=$(openssl rand -base64 48 | tr -d '/+=' | cut -c1-64)
}

account_generate_fresh_env() {
    log_step "Generating account .env..."
    account_generate_crypto_keys

    cat >"$ACCOUNT_DIR/.env" <<EOF
# Auto-generated by ./run.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Account server URL (used by rdc CLI for subscription commands)
# Updated automatically by dev-gateway on startup with the actual port
REDIACC_ACCOUNT_SERVER=http://localhost:4800

# SQLite database path
DATABASE_PATH=account.db

# Ed25519 key pair (for subscription/license signing)
ED25519_PRIVATE_KEY=${ED25519_PRIV}
ED25519_PUBLIC_KEY=${ED25519_PUB}

# X25519 key pair (for E2E encryption)
X25519_PRIVATE_KEY=${X25519_PRIV}
X25519_PUBLIC_KEY=${X25519_PUB}

# Admin API key
API_KEY=${API_K}

# JWT secret for session tokens
JWT_SECRET=${JWT_SEC}

# Stripe sandbox (uncomment and fill to enable Stripe features)
# STRIPE_SANDBOX_SECRET_KEY=sk_test_...
# STRIPE_SANDBOX_WEBHOOK_SECRET is auto-captured from stripe listen

# Fixed webhook secret for E2E webhook simulation tests
STRIPE_WEBHOOK_SECRET=whsec_e2e_test_webhook_secret_for_simulation_only

# Admin email (receives alerts for disputes, refunds, etc.)
ADMIN_EMAIL=admin@example.com

# Telemetry auth token (for OTLP basic auth — set via OTLP_AUTH_TOKEN env var or manually)
# REDIACC_TELEMETRY_AUTH_TOKEN=

# Server port (used by standalone node entry, not the dev gateway)
PORT=3000
EOF

    log_info "Generated private/account/.env with fresh keys"
}

# Append a key=value to .env if the key doesn't already exist
account_env_add_if_missing() {
    local key="$1" value="$2" comment="${3:-}"
    local env_file="$ACCOUNT_DIR/.env"
    if ! grep -q "^${key}=" "$env_file" 2>/dev/null; then
        [[ -n "$comment" ]] && echo -e "\n# ${comment}" >>"$env_file"
        echo "${key}=${value}" >>"$env_file"
        return 0
    fi
    return 1
}

# Ensure all required keys exist in .env, adding any that are missing
account_ensure_env_keys() {
    local env_file="$ACCOUNT_DIR/.env"
    local added=0

    # Generate keys only if we actually need them
    local need_gen=false
    for key in ED25519_PRIVATE_KEY ED25519_PUBLIC_KEY X25519_PRIVATE_KEY X25519_PUBLIC_KEY API_KEY JWT_SECRET; do
        if ! grep -q "^${key}=" "$env_file" 2>/dev/null; then
            need_gen=true
            break
        fi
    done

    if [[ "$need_gen" == "true" ]]; then
        account_generate_crypto_keys

        account_env_add_if_missing "ED25519_PRIVATE_KEY" "$ED25519_PRIV" "Ed25519 key pair (for subscription/license signing)" && added=1
        account_env_add_if_missing "ED25519_PUBLIC_KEY" "$ED25519_PUB" && added=1
        account_env_add_if_missing "X25519_PRIVATE_KEY" "$X25519_PRIV" "X25519 key pair (for E2E encryption)" && added=1
        account_env_add_if_missing "X25519_PUBLIC_KEY" "$X25519_PUB" && added=1
        account_env_add_if_missing "API_KEY" "$API_K" "Admin API key" && added=1
        account_env_add_if_missing "JWT_SECRET" "$JWT_SEC" "JWT secret for session tokens" && added=1
    fi

    # Non-crypto defaults (only added if missing, never overridden)
    account_env_add_if_missing "REDIACC_ACCOUNT_SERVER" "http://localhost:4800" "Account server URL" && added=1
    account_env_add_if_missing "DATABASE_PATH" "account.db" "SQLite database path" && added=1
    account_env_add_if_missing "STRIPE_WEBHOOK_SECRET" "whsec_e2e_test_webhook_secret_for_simulation_only" "Fixed webhook secret for E2E tests" && added=1
    account_env_add_if_missing "PORT" "3000" "Server port" && added=1
    # Telemetry: CLI auth token + account server OTel config
    account_env_add_if_missing "OTEL_ENDPOINT" "https://otlp.rediacc.io" "OTel OTLP endpoint" && added=1
    if [[ -n "${OTLP_AUTH_TOKEN:-}" ]]; then
        account_env_add_if_missing "REDIACC_TELEMETRY_AUTH_TOKEN" "$OTLP_AUTH_TOKEN" \
            "Telemetry auth token (for CLI OTLP basic auth)" && added=1
        account_env_add_if_missing "OTEL_AUTH_TOKEN" "$OTLP_AUTH_TOKEN" \
            "OTel auth token (for account server OTLP basic auth)" && added=1
    fi
    # Note: ADMIN_EMAIL, STRIPE_SANDBOX_SECRET_KEY, AWS_SES_* are user-set values
    # — only created in fresh generation, never added/overridden on ensure/reset

    if [[ $added -gt 0 ]]; then
        log_info "Added missing keys to existing .env"
    fi
}

account_ensure_env() {
    if [[ ! -f "$ACCOUNT_DIR/.env" ]]; then
        account_generate_fresh_env
        return 0
    fi

    # Ensure any newly added keys are present
    account_ensure_env_keys
}

# =============================================================================
# STRIPE AUTO-SETUP
# =============================================================================

account_stripe_auto() {
    local stripe_key="${STRIPE_SANDBOX_SECRET_KEY:-}"
    if [[ -z "$stripe_key" ]]; then
        return 0
    fi

    # Check stripe CLI
    if ! command -v stripe &>/dev/null; then
        log_warn "STRIPE_SANDBOX_SECRET_KEY is set but stripe CLI not found"
        log_info "Install from: https://docs.stripe.com/stripe-cli"
        log_info "Continuing without webhook forwarding"
        return 0
    fi

    log_step "Setting up Stripe sandbox..."

    # Kill any orphaned stripe listen forwarding to this worktree's gateway port.
    # This handles cases where a previous session crashed without cleanup.
    local stale_pids
    stale_pids=$(pgrep -f "stripe listen.*--forward-to http://localhost:${GATEWAY_PORT}/" 2>/dev/null || true)
    if [[ -n "$stale_pids" ]]; then
        log_info "Cleaning up stale stripe listen (PIDs: $stale_pids)"
        echo "$stale_pids" | xargs kill 2>/dev/null || true
        sleep 1
    fi

    # Sync products/prices (idempotent)
    log_info "Syncing Stripe products/prices..."
    (cd "$ACCOUNT_DIR" && STRIPE_SECRET_KEY="$stripe_key" npx tsx scripts/stripe-sync.ts 2>&1 | tail -5)

    # Start stripe listen in background
    local stripe_log
    stripe_log=$(mktemp)

    stripe listen \
        --api-key "$stripe_key" \
        --forward-to "http://localhost:${GATEWAY_PORT}/account/api/v1/webhooks/stripe" \
        >"$stripe_log" 2>&1 &
    local stripe_pid=$!
    ACCOUNT_PIDS+=("$stripe_pid")

    # Wait for webhook secret
    local webhook_secret=""
    local elapsed=0
    while [[ $elapsed -lt 30 ]]; do
        webhook_secret=$(grep -oE 'whsec_[^[:space:]]+' "$stripe_log" 2>/dev/null || true)
        if [[ -n "$webhook_secret" ]]; then
            break
        fi
        sleep 1
        elapsed=$((elapsed + 1))
    done
    rm -f "$stripe_log"

    if [[ -z "$webhook_secret" ]]; then
        log_warn "stripe listen did not output webhook secret within 30s"
        log_info "Stripe features may not work — check stripe CLI auth"
        return 0
    fi

    export STRIPE_SANDBOX_WEBHOOK_SECRET="$webhook_secret"
    log_info "Stripe webhook forwarding active (secret: ${webhook_secret:0:12}...)"
}

# =============================================================================
# PUBLIC COMMANDS
# =============================================================================

account_dev() {
    check_node_version

    log_step "Starting account development environment"

    # Allocate dynamic ports
    account_allocate_ports
    log_info "Ports: gateway=$GATEWAY_PORT vite=$VITE_PORT astro=$ASTRO_PORT"

    # Generate .env if needed
    account_ensure_env

    # Load environment
    set -a
    source "$ACCOUNT_DIR/.env"
    set +a

    # Dependencies
    ensure_deps

    # Install account + web deps if needed
    if [[ ! -d "$ACCOUNT_DIR/node_modules" ]] ||
        [[ "$ACCOUNT_DIR/package-lock.json" -nt "$ACCOUNT_DIR/node_modules" ]]; then
        log_step "Installing account dependencies..."
        (cd "$ACCOUNT_DIR" && npm install --prefer-offline --no-audit --no-fund 2>&1 | tail -1)
    fi

    if [[ ! -d "$ACCOUNT_DIR/web/node_modules" ]] ||
        [[ "$ACCOUNT_DIR/web/package-lock.json" -nt "$ACCOUNT_DIR/web/node_modules" ]]; then
        log_step "Installing account web dependencies..."
        (cd "$ACCOUNT_DIR/web" && npm install --prefer-offline --no-audit --no-fund 2>&1 | tail -1)
    fi

    # Ensure shared packages are built (account depends on @rediacc/shared)
    ensure_packages_built

    # Setup cleanup trap
    trap account_cleanup EXIT INT TERM

    # Create log directory
    mkdir -p "$ACCOUNT_LOG_DIR"

    # Start Astro dev server (marketing site)
    log_step "Starting Astro dev server on :${ASTRO_PORT}..."
    (cd "$CONSOLE_ROOT_DIR/packages/www" && npx astro dev --port "$ASTRO_PORT" --host 127.0.0.1) \
        >"$ACCOUNT_LOG_DIR/astro.log" 2>&1 &
    ACCOUNT_PIDS+=($!)

    # Start Vite dev server (account portal SPA)
    log_step "Starting Vite dev server on :${VITE_PORT}..."
    (cd "$ACCOUNT_DIR/web" && npx vite --port "$VITE_PORT" --host 127.0.0.1) \
        >"$ACCOUNT_LOG_DIR/vite.log" 2>&1 &
    ACCOUNT_PIDS+=($!)

    # Wait for both to be ready
    account_wait_port "$ASTRO_PORT" "Astro" 30 || exit 1
    account_wait_port "$VITE_PORT" "Vite" 30 || exit 1

    # Auto-setup Stripe if key is configured
    account_stripe_auto

    # Start gateway (foreground — keeps terminal alive)
    log_step "Starting dev gateway on :${GATEWAY_PORT}..."
    (cd "$ACCOUNT_DIR" &&
        GATEWAY_PORT=$GATEWAY_PORT \
            VITE_PORT=$VITE_PORT \
            ASTRO_PORT=$ASTRO_PORT \
            npx tsx src/entry/dev-gateway.ts)
}

account_stop() {
    log_step "Stopping account containers"
    (cd "$ACCOUNT_DIR" && docker compose down --remove-orphans) 2>/dev/null || true

    # Force remove if still around
    local container="account-server"
    if docker ps -a --format "{{.Names}}" 2>/dev/null | grep -q "^${container}$"; then
        docker stop "$container" 2>/dev/null || true
        docker rm "$container" 2>/dev/null || true
    fi

    rm -f "$ACCOUNT_STATE_FILE"
    log_info "Account containers stopped"
}

account_test() {
    check_node_version

    ensure_packages_built

    log_step "Running account tests"
    (cd "$ACCOUNT_DIR" && npx vitest run "$@")
}

account_test_e2e() {
    check_node_version

    # Load backend .env to extract secrets for E2E tests
    local account_env="$ACCOUNT_DIR/.env"
    if [[ ! -f "$account_env" ]]; then
        log_error "Account .env not found. Run: ./run.sh account reset"
        exit 1
    fi

    set -a
    source "$account_env"
    set +a

    # Check dev gateway is running
    local gateway_port="${GATEWAY_PORT:-}"
    if [[ -z "$gateway_port" ]]; then
        # Try to detect from REDIACC_ACCOUNT_SERVER
        gateway_port=$(echo "${REDIACC_ACCOUNT_SERVER:-}" | grep -oP ':\K[0-9]+' || echo "")
    fi

    if [[ -z "$gateway_port" ]]; then
        log_error "Cannot determine gateway port"
        log_info "Start the dev gateway first: ./run.sh account dev"
        exit 1
    fi

    if ! is_port_in_use "$gateway_port"; then
        log_error "Dev gateway not running on port $gateway_port"
        log_info "Start it first: ./run.sh account dev"
        exit 1
    fi

    # Wire backend secrets → E2E env vars
    export E2E_PORT="$gateway_port"
    export E2E_BASE_URL="http://localhost:${gateway_port}/account/"
    export ADMIN_EMAIL="${ADMIN_EMAIL:-}"

    # Webhook simulation secret (matches backend's STRIPE_WEBHOOK_SECRET)
    if [[ -n "${STRIPE_WEBHOOK_SECRET:-}" ]]; then
        export E2E_WEBHOOK_SECRET="$STRIPE_WEBHOOK_SECRET"
        log_info "Webhook simulation: enabled (STRIPE_WEBHOOK_SECRET)"
    else
        log_warn "Webhook simulation: disabled (STRIPE_WEBHOOK_SECRET not set)"
    fi

    # Stripe sandbox key (for real Stripe E2E tests)
    if [[ -n "${STRIPE_SANDBOX_SECRET_KEY:-}" ]]; then
        export STRIPE_SANDBOX_SECRET_KEY
        log_info "Stripe sandbox E2E: enabled"
    else
        log_warn "Stripe sandbox E2E: disabled (STRIPE_SANDBOX_SECRET_KEY not set)"
    fi

    ensure_packages_built

    # Install E2E deps if needed
    local e2e_dir="$ACCOUNT_DIR/e2e"
    if [[ ! -d "$e2e_dir/node_modules" ]] ||
        [[ "$e2e_dir/package-lock.json" -nt "$e2e_dir/node_modules" ]]; then
        log_step "Installing E2E dependencies..."
        (cd "$e2e_dir" && npm install --prefer-offline --no-audit --no-fund 2>&1 | tail -1)
    fi

    log_step "Running account E2E tests (gateway on :${gateway_port})"
    (cd "$e2e_dir" && npx playwright test --project=chromium --reporter=list "$@")
}

account_reset() {
    check_node_version

    log_step "Resetting account development environment"

    local env_file="$ACCOUNT_DIR/.env"

    if [[ -f "$env_file" ]]; then
        # Regenerate crypto keys in-place, preserving user-added values
        log_info "Regenerating crypto keys (preserving user values)..."
        account_generate_crypto_keys

        sed -i "s|^ED25519_PRIVATE_KEY=.*|ED25519_PRIVATE_KEY=${ED25519_PRIV}|" "$env_file"
        sed -i "s|^ED25519_PUBLIC_KEY=.*|ED25519_PUBLIC_KEY=${ED25519_PUB}|" "$env_file"
        sed -i "s|^X25519_PRIVATE_KEY=.*|X25519_PRIVATE_KEY=${X25519_PRIV}|" "$env_file"
        sed -i "s|^X25519_PUBLIC_KEY=.*|X25519_PUBLIC_KEY=${X25519_PUB}|" "$env_file"
        sed -i "s|^JWT_SECRET=.*|JWT_SECRET=${JWT_SEC}|" "$env_file"
        sed -i "s|^API_KEY=.*|API_KEY=${API_K}|" "$env_file"

        # Ensure any newly added keys exist
        account_ensure_env_keys
    else
        account_generate_fresh_env
    fi

    # Reset database
    local db_path="$ACCOUNT_DIR/account.db"
    for f in "$db_path" "$db_path-shm" "$db_path-wal" "$db_path-journal"; do
        if [[ -f "$f" ]]; then
            log_info "Removing $(basename "$f")"
            rm -f "$f"
        fi
    done

    echo ""
    log_info "Account reset complete!"
    log_info ""
    log_info "Start dev server with: ./run.sh account dev"
}
