#!/bin/bash
# Devbox: one browser-reachable dev container per worktree.
#
# Why a container and not the host: the toolchain (node, go, playwright deps,
# openvscode-server) is already built and pinned in ghcr.io/rediacc/devcontainer,
# so a new machine needs Docker and nothing else.
#
# Why per WORKTREE: each checkout gets its own container, its own port block and
# its own state file, so two worktrees never fight over a port or a container
# name. The block is derived from the worktree's absolute path, so it is the
# same after a reboot and a bookmarked URL keeps working.

[[ -n "${DEVBOX_LIB_LOADED:-}" ]] && return 0
readonly DEVBOX_LIB_LOADED=1

DEVBOX_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$DEVBOX_LIB_DIR/find-port.sh"

DEVBOX_LABEL_KEY="com.rediacc.devbox.worktree"

# =============================================================================
# IDENTITY
# =============================================================================

# The worktree this checkout is, resolved absolutely (the label/port key).
devbox_worktree() {
    (cd "${CONSOLE_ROOT_DIR:-$PWD}" && pwd -P)
}

# The directory that must be bind-mounted.
#
# NOT simply the worktree: a git worktree's .git file holds an ABSOLUTE gitdir
# path back into the main checkout, so mounting only the worktree gives a
# container where every git command fails. Mounting the main checkout covers
# both, because worktrees live under it (scripts/dev/worktree.sh:22).
devbox_mount_root() {
    local common_dir
    if common_dir="$(git -C "$(devbox_worktree)" rev-parse --git-common-dir 2>/dev/null)"; then
        # --git-common-dir may be relative to the worktree.
        case "$common_dir" in
            /*) : ;;
            *) common_dir="$(devbox_worktree)/$common_dir" ;;
        esac
        (cd "$common_dir/.." && pwd -P)
        return 0
    fi
    devbox_worktree
}

devbox_container_name() {
    local wt slot
    wt="$(devbox_worktree)"
    slot="$(derive_slot "$wt" 100)"
    printf 'rediacc-devbox-%s-%s\n' "$slot" "$(basename "$wt")"
}

# docker, or sudo docker when the group is not active in this shell yet.
devbox_docker() {
    if docker version &>/dev/null; then
        echo docker
    elif sudo -n docker version &>/dev/null || sudo docker version &>/dev/null; then
        echo "sudo docker"
    else
        echo docker
    fi
}

# =============================================================================
# STATE
# =============================================================================

devbox_state_write() {
    local base_port="$1" container="$2" digest="$3" docker_gid="$4"
    cat >"$DEVBOX_STATE_FILE" <<EOF
# Generated by ./run.sh setup - do not edit
worktree=$(devbox_worktree)
container=$container
base_port=$base_port
image=$DEVBOX_IMAGE
image_digest=$digest
docker_gid=$docker_gid
uid=$(id -u)
gid=$(id -g)
EOF
}

devbox_state_get() {
    local key="$1"
    [[ -f "$DEVBOX_STATE_FILE" ]] || return 1
    sed -n "s/^${key}=//p" "$DEVBOX_STATE_FILE" | head -1
}

# =============================================================================
# PORTS
# =============================================================================

# Stable base port for this worktree. A previously allocated base is reused from
# state so a temporarily busy neighbour cannot shuffle an established devbox.
devbox_base_port() {
    local saved

    # The state file is the record: the container publishes NO ports, so there
    # is nothing to ask the daemon for. (An earlier version inspected the
    # published HostPort; that branch became unreachable when the proxy became
    # the only ingress.)
    if saved="$(devbox_state_get base_port)" && [[ -n "$saved" ]]; then
        echo "$saved"
        return 0
    fi

    # First time: derive from the worktree path.
    find_port_block "$(devbox_worktree)" \
        "$DEVBOX_PORT_RANGE_START" "$DEVBOX_PORT_RANGE_END" "$DEVBOX_PORT_BLOCK"
}

# A short, URL-safe name for this worktree. It IS the hostname, so it is what
# the operator types and remembers -- the branch-name-in-the-URL idea that a
# numeric port block could not express.
devbox_slug() {
    basename "$(devbox_worktree)" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g; s/^-*//; s/-*$//'
}

devbox_url() { # devbox_url [suffix]
    local suffix="${1:-}"
    local slug
    slug="$(devbox_slug)"
    [[ -n "$suffix" ]] && slug="${slug}-${suffix}"
    echo "http://${slug}.${DEVBOX_DOMAIN}:${DEVBOX_PROXY_PORT}"
}

# =============================================================================
# REVERSE PROXY (one per machine, shared by every worktree)
# =============================================================================

devbox_network_ensure() {
    local d
    d="$(devbox_docker)"
    $d network inspect "$DEVBOX_NETWORK" &>/dev/null && return 0
    log_step "Creating docker network $DEVBOX_NETWORK"
    $d network create "$DEVBOX_NETWORK" >/dev/null
}

devbox_proxy_running() {
    local d
    d="$(devbox_docker)"
    [[ "$($d inspect -f '{{.State.Running}}' "$DEVBOX_PROXY_NAME" 2>/dev/null)" == "true" ]]
}

devbox_proxy_ensure() {
    local d
    d="$(devbox_docker)"

    devbox_network_ensure || return 1
    devbox_proxy_running && return 0

    # A stopped leftover: start it rather than fighting over the name.
    if $d inspect "$DEVBOX_PROXY_NAME" &>/dev/null; then
        $d start "$DEVBOX_PROXY_NAME" >/dev/null && return 0
    fi

    log_step "Starting the devbox proxy on :$DEVBOX_PROXY_PORT"
    # The docker provider reads labels off the containers themselves, so adding a
    # worktree needs no proxy config change. exposedByDefault=false means a
    # container is only routed when it opts in with traefik.enable=true.
    $d run -d \
        --name "$DEVBOX_PROXY_NAME" \
        --restart unless-stopped \
        --network "$DEVBOX_NETWORK" \
        -p "$DEVBOX_PROXY_PORT:80" \
        -v /var/run/docker.sock:/var/run/docker.sock:ro \
        "$DEVBOX_PROXY_IMAGE" \
        --providers.docker=true \
        --providers.docker.exposedByDefault=false \
        --providers.docker.network="$DEVBOX_NETWORK" \
        --entrypoints.web.address=:80 \
        --log.level=WARN >/dev/null || {
        log_error "Could not start the devbox proxy"
        return 1
    }

    local i
    for ((i = 0; i < 30; i++)); do
        # 404 is a healthy Traefik with no matching route; connection refused is not.
        if curl -s -o /dev/null --max-time 2 "http://127.0.0.1:$DEVBOX_PROXY_PORT/"; then
            return 0
        fi
        sleep 1
    done
    log_error "Proxy started but is not answering on :$DEVBOX_PROXY_PORT"
    $d logs --tail 20 "$DEVBOX_PROXY_NAME" >&2 || true
    return 1
}

devbox_proxy_stop() {
    local d
    d="$(devbox_docker)"
    devbox_proxy_running || {
        log_warn "Proxy is not running"
        return 0
    }
    $d stop "$DEVBOX_PROXY_NAME" >/dev/null && log_info "Proxy stopped"
}

# =============================================================================
# IMAGE
# =============================================================================

devbox_image_present() {
    local d
    d="$(devbox_docker)"
    $d image inspect "$DEVBOX_IMAGE" &>/dev/null
}

devbox_image_digest() {
    local d
    d="$(devbox_docker)"
    $d image inspect --format '{{index .RepoDigests 0}}' "$DEVBOX_IMAGE" 2>/dev/null || echo unknown
}

devbox_ensure_image() {
    local force_pull="${1:-false}"
    local d
    d="$(devbox_docker)"

    if devbox_image_present && [[ "$force_pull" != true ]]; then
        log_debug "Image present: $DEVBOX_IMAGE"
        return 0
    fi

    log_step "Pulling $DEVBOX_IMAGE"
    log_info "This image carries node, go, playwright deps and a desktop; the first pull is several GB and takes a while."
    if $d pull "$DEVBOX_IMAGE"; then
        return 0
    fi

    # ghcr.io/rediacc/* is private. A GitHub token needs the read:packages
    # scope to pull it -- repo+workflow is NOT enough, and the registry's only
    # signal is the word "denied", which reads like the image does not exist.
    log_warn "Could not pull $DEVBOX_IMAGE"
    log_info "That registry is private. To pull it, a GitHub token needs the read:packages scope:"
    log_info "    echo \$PAT | docker login ghcr.io -u <user> --password-stdin"
    log_info "Falling back to building the image locally from .devcontainer/Dockerfile."
    devbox_build_image
}

# Build the devcontainer image from source.
#
# The fallback for a machine with no registry access. Slower than a pull (this
# Dockerfile installs a Go toolchain, Node, a desktop and Playwright deps), but
# it needs no credentials, which is the whole point.
devbox_build_image() {
    local d dockerfile_dir
    d="$(devbox_docker)"
    dockerfile_dir="$(devbox_mount_root)/.devcontainer"

    [[ -f "$dockerfile_dir/Dockerfile" ]] || {
        log_error "No Dockerfile at $dockerfile_dir"
        return 1
    }

    log_step "Building $DEVBOX_IMAGE locally (this takes a while)"
    $d build -t "$DEVBOX_IMAGE" -f "$dockerfile_dir/Dockerfile" "$dockerfile_dir" || {
        log_error "Local image build failed"
        return 1
    }
    log_info "Built $DEVBOX_IMAGE"
}

# =============================================================================
# CONTAINER
# =============================================================================

# Find this worktree's container by LABEL, not by name: two different checkouts
# can each contain a worktree called 0824-1, and the daemon is the truth while
# the state file is only a cache.
devbox_container_id() {
    local d
    d="$(devbox_docker)"
    $d ps -aq --filter "label=${DEVBOX_LABEL_KEY}=$(devbox_worktree)" 2>/dev/null | head -1
}

devbox_container_running() {
    local d cid
    d="$(devbox_docker)"
    cid="$(devbox_container_id)"
    [[ -n "$cid" ]] || return 1
    [[ "$($d inspect -f '{{.State.Running}}' "$cid" 2>/dev/null)" == "true" ]]
}

_devbox_bind_if_present() {
    # Only bind paths that already exist. Docker CREATES a missing source as a
    # root-owned directory on the host, which is how a bind mount silently turns
    # into an unwritable ~/.claude.
    local src="$1" dst="$2" mode="${3:-}"
    [[ -e "$src" ]] || return 0
    if [[ -n "$mode" ]]; then
        printf -- '-v\n%s:%s:%s\n' "$src" "$dst" "$mode"
    else
        printf -- '-v\n%s:%s\n' "$src" "$dst"
    fi
}

devbox_up() {
    local force_pull="${1:-false}"
    local d base_port mount_root workspace name docker_gid cid
    d="$(devbox_docker)"

    if devbox_container_running; then
        log_info "Devbox already running for this worktree"
        devbox_status
        return 0
    fi

    cid="$(devbox_container_id)"
    if [[ -n "$cid" ]]; then
        log_step "Starting existing devbox container"
        $d start "$cid" >/dev/null
        devbox_status
        return 0
    fi

    devbox_ensure_image "$force_pull" || return 1
    devbox_proxy_ensure || return 1

    base_port="$(devbox_base_port)" || {
        log_error "No free port block in ${DEVBOX_PORT_RANGE_START}-${DEVBOX_PORT_RANGE_END}"
        return 1
    }
    mount_root="$(devbox_mount_root)"
    workspace="$(devbox_worktree)"
    name="$(devbox_container_name)"
    docker_gid="$(getent group docker 2>/dev/null | cut -d: -f3)"

    local vscode_port=$((base_port + DEVBOX_OFFSET_VSCODE))
    local studio_port=$((base_port + DEVBOX_OFFSET_STUDIO))

    local -a binds=()
    # The repo at its IDENTICAL path. Non-negotiable: worktree gitdir links are
    # absolute, and a nested `docker -v $(pwd)` is resolved by the host daemon,
    # so only an identical path is correct in both.
    binds+=(-v "$mount_root:$mount_root")
    binds+=(-v "$DEVBOX_LIB_DIR/../../.devcontainer/devbox-entrypoint.sh:/usr/local/bin/devbox-entrypoint.sh:ro")
    [[ -S /var/run/docker.sock ]] && binds+=(-v /var/run/docker.sock:/var/run/docker.sock)

    # Credentials and agent config, named rather than the whole $HOME: ~/.ssh
    # and cloud credentials stay out of the container.
    local container_home="/home/vscode"
    while IFS= read -r line; do [[ -n "$line" ]] && binds+=("$line"); done < <(
        _devbox_bind_if_present "$HOME/.gitconfig" "$container_home/.gitconfig" ro
        _devbox_bind_if_present "$HOME/.git-credentials" "$container_home/.git-credentials" ro
        _devbox_bind_if_present "$HOME/.config/gh" "$container_home/.config/gh"
        _devbox_bind_if_present "$HOME/.claude" "$container_home/.claude"
        _devbox_bind_if_present "$HOME/.claude.json" "$container_home/.claude.json"
        _devbox_bind_if_present "$HOME/.config/rediacc" "$container_home/.config/rediacc"
    )

    local slug
    slug="$(devbox_slug)"

    # Traefik labels. Routing is by Host header, so every service keeps its own
    # root path and none of them need base-path configuration.
    local -a labels=(
        --label "traefik.enable=true"
        --label "traefik.docker.network=$DEVBOX_NETWORK"
        # VS Code
        --label "traefik.http.routers.${slug}-code.rule=Host(\`${slug}.${DEVBOX_DOMAIN}\`)"
        --label "traefik.http.routers.${slug}-code.entrypoints=web"
        --label "traefik.http.routers.${slug}-code.service=${slug}-code"
        --label "traefik.http.services.${slug}-code.loadbalancer.server.port=$vscode_port"
        # The account gateway is the ONLY app door: it serves the marketing
        # site at /, the portal at /account/ and the API at /account/api/, all
        # proxying to the same live dev servers. A second hostname pointed
        # straight at Astro used to exist; it cost no CPU (both doors reach
        # processes `account dev` starts anyway) but it 404'd on /account, which
        # is the half of the app people actually want.
        --label "traefik.http.routers.${slug}-account.rule=Host(\`${slug}-account.${DEVBOX_DOMAIN}\`)"
        --label "traefik.http.routers.${slug}-account.entrypoints=web"
        --label "traefik.http.routers.${slug}-account.service=${slug}-account"
        --label "traefik.http.services.${slug}-account.loadbalancer.server.port=4800"
        # Database browser. `account db` serves sqlite_web here, whose UI comes
        # from this same origin -- so there is no hosted third-party page and no
        # Local Network Access permission to grant. (An earlier version
        # redirected this route's root to local.drizzle.studio; a real browser
        # showed Chrome blocking that page from reaching the local server, and
        # the redirect also 307'd Drizzle's own `POST /` API.)
        --label "traefik.http.routers.${slug}-db.rule=Host(\`${slug}-db.${DEVBOX_DOMAIN}\`)"
        --label "traefik.http.routers.${slug}-db.entrypoints=web"
        --label "traefik.http.routers.${slug}-db.service=${slug}-db"
        --label "traefik.http.services.${slug}-db.loadbalancer.server.port=$studio_port"
    )

    log_step "Creating devbox for $workspace"
    log_info "container: $name"
    log_info "hostname:  ${slug}.${DEVBOX_DOMAIN}"
    log_info "reachable ONLY through the proxy on :${DEVBOX_PROXY_PORT}; the container publishes no ports"

    # Published on 0.0.0.0, not 127.0.0.1: on ChromeOS the browser is outside
    # this VM and reaches it by address, so a loopback-only publish is invisible.
    $d run -d \
        --name "$name" \
        --label "${DEVBOX_LABEL_KEY}=$workspace" \
        --restart unless-stopped \
        --init \
        --shm-size=1g \
        --hostname "$(basename "$workspace")-devbox" \
        --network "$DEVBOX_NETWORK" \
        "${labels[@]}" \
        "${binds[@]}" \
        ${docker_gid:+--group-add "$docker_gid"} \
        -e HOST_UID="$(id -u)" \
        -e HOST_GID="$(id -g)" \
        -e DOCKER_GID="${docker_gid:-}" \
        -e DEVBOX_PORT="$vscode_port" \
        -e DEVBOX_WORKSPACE="$workspace" \
        -e REDIACC_NPM_RUNTIME=devbox \
        -e REDIACC_DEV_BIND=0.0.0.0 \
        -e REDIACC_DEV_PORT_BASE=4800 \
        -w "$workspace" \
        --entrypoint /usr/local/bin/devbox-entrypoint.sh \
        "$DEVBOX_IMAGE" >/dev/null || {
        log_error "docker run failed"
        return 1
    }

    devbox_state_write "$base_port" "$name" "$(devbox_image_digest)" "${docker_gid:-}"

    # Confirm it actually SERVES.
    #
    # is_port_in_use is useless here: docker-proxy binds the published port the
    # instant the container starts, so the port is "in use" even when the
    # process inside crashed on startup. Ask for an HTTP response instead.
    local i
    for ((i = 0; i < 60; i++)); do
        if curl -fsS -o /dev/null --max-time 2 \
            -H "Host: $(devbox_slug).${DEVBOX_DOMAIN}" \
            "http://127.0.0.1:${DEVBOX_PROXY_PORT}/" 2>/dev/null; then
            devbox_status
            return 0
        fi
        if ! devbox_container_running; then
            log_error "Devbox container exited during startup. Last output:"
            $d logs --tail 30 "$(devbox_container_id)" >&2 || true
            return 1
        fi
        sleep 1
    done

    log_error "Devbox started but nothing is listening on $vscode_port after 60s"
    $d logs --tail 30 "$(devbox_container_id)" >&2 || true
    return 1
}

# Turn a probe's HTTP code into the line the operator reads.
#
# Extracted from devbox_status so it can be tested without docker, a proxy or a
# network. The invariant it carries: the WORD must never contradict the CODE.
# "OK (404)" was shipped for one commit and is exactly the failure this guards --
# Drizzle Studio answers 404 at / by design, so the temptation is to call that
# success, which then hides a genuine 404 on any other route behind the same
# label. Reachability and success are different claims; this says "live".
devbox_route_label() {
    local code="$1" hint="${2:-}"
    case "$code" in
        000) echo "proxy unreachable" ;;
        502) echo "no backend yet${hint:+ -- $hint}" ;;
        *) echo "live (HTTP $code)" ;;
    esac
}

devbox_status() {
    local base_port
    base_port="$(devbox_base_port 2>/dev/null)"

    if devbox_container_running; then
        log_info "Devbox running: $(devbox_container_name)"
        echo ""
        # PROBE each route rather than listing URLs and hoping. Traefik answers a
        # bare 502 when a router matches but nothing is listening behind it, and
        # that page names neither the service nor the reason -- so an operator
        # reads "Bad Gateway" for a backend that was simply never started, or was
        # started on the HOST instead of inside the devbox.
        # The 5th field is the PROBE PATH. It exists for the db route: a
        # higher-priority router redirects its bare "/" to the hosted Studio UI,
        # so probing "/" would report 302 whether or not Studio is running.
        # Probing any other path bypasses the redirect and reaches the backend.
        local _svc _label _code _probe
        for _svc in "code:VS Code::" \
            "account:Account:account:./run.sh account dev (INSIDE the devbox)" \
            "db:Database:db:./run.sh account db (INSIDE the devbox)"; do
            IFS=: read -r _ _label _suffix _hint _probe <<<"$_svc"
            # `|| true` is load-bearing under `set -e`: curl exits non-zero on a
            # timeout (28) or refused connection (7), and a failing command
            # substitution makes the ASSIGNMENT fail, which kills the whole
            # script. A probe that cannot reach a route must report "000", not
            # abort the status command. Observed as `setup --check` exiting 28
            # when the box was loaded enough for one probe to time out.
            _code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 \
                -H "Host: $(devbox_slug)${_suffix:+-$_suffix}.${DEVBOX_DOMAIN}" \
                "http://127.0.0.1:${DEVBOX_PROXY_PORT}${_probe:-/}" 2>/dev/null || true)"
            [[ -z "$_code" ]] && _code=000
            printf '  %-9s %-46s %s\n' "$_label:" "$(devbox_url "$_suffix")" \
                "$(devbox_route_label "$_code" "$_hint")"
        done
        echo ""
        if ! devbox_proxy_running; then
            log_warn "The proxy is not running, so those hostnames will not resolve."
            log_info "Start it with: ./run.sh devbox up"
        fi
        echo "  On ChromeOS forward ONE port -- ${DEVBOX_PROXY_PORT} -- in"
        echo "  Settings > Linux > Port forwarding. Chrome resolves *.localhost itself,"
        echo "  so every worktree and service is reachable through it."
        echo ""
        return 0
    fi
    if [[ -n "$(devbox_container_id)" ]]; then
        log_warn "Devbox container exists but is stopped. Start it with: ./run.sh devbox up"
        return 1
    fi
    log_warn "No devbox for this worktree. Create it with: ./run.sh setup"
    return 1
}

devbox_stop() {
    local d cid
    d="$(devbox_docker)"
    cid="$(devbox_container_id)"
    [[ -n "$cid" ]] || {
        log_warn "No devbox container for this worktree"
        return 0
    }
    log_step "Stopping devbox"
    $d stop "$cid" >/dev/null && log_info "Stopped"
}

devbox_remove() {
    local d cid
    d="$(devbox_docker)"
    cid="$(devbox_container_id)"
    [[ -n "$cid" ]] || {
        log_warn "No devbox container for this worktree"
        return 0
    }
    log_step "Removing devbox"
    $d rm -f "$cid" >/dev/null && rm -f "$DEVBOX_STATE_FILE" && log_info "Removed"
}

devbox_logs() {
    local d
    d="$(devbox_docker)"
    local cid
    cid="$(devbox_container_id)"
    [[ -n "$cid" ]] || {
        log_error "No devbox container for this worktree"
        return 1
    }
    $d logs "${1:---tail=100}" "$cid"
}

devbox_shell() {
    local d cid
    d="$(devbox_docker)"
    cid="$(devbox_container_id)"
    devbox_container_running || {
        log_error "Devbox is not running. Start it with: ./run.sh devbox up"
        return 1
    }
    $d exec -it -u "$(id -u):$(id -g)" -w "$(devbox_worktree)" "$cid" bash
}
