#!/bin/bash
# Devbox: one browser-reachable dev container per worktree.
#
# Why a container and not the host: the toolchain (node, go, playwright deps,
# openvscode-server) is already built and pinned in ghcr.io/rediacc/devcontainer,
# so a new machine needs Docker and nothing else.
#
# Why per WORKTREE: each checkout gets its own container, its own port block and
# its own state file, so two worktrees never fight over a port or a container
# name. The block is derived from the worktree's absolute path, so it is the
# same after a reboot.
#
# THE URL IS NOT STABLE ANY MORE, and the old text here promised it was. The
# hostname is derived from the BRANCH, so `git checkout` changes it -- that is
# the whole point of putting the branch in the URL, and it is the cost. The
# PORT block stays path-derived, and the container is still found by its path
# label, so identity and ports are unaffected; only the name people type moves.

[[ -n "${DEVBOX_LIB_LOADED:-}" ]] && return 0
readonly DEVBOX_LIB_LOADED=1

DEVBOX_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Port utilities. `.ci/lib/find-port.sh`, the bash shim that used to wrap
# rediacc_ci.core.ports, is DELETED (W7P5-b): a shim is a delay, not an exit.
# `derive_slot` and `find_port_block` below name the module directly.
#
# The shim's LOAD-TIME refusal is kept deliberately. This file's slot decides
# which URL a bookmark resolves to, so a missing interpreter must be a named
# failure rather than a plausible wrong number. REDIACC_CI_ROOT is the
# package's single environment override (see .ci/rediacc_ci/paths.py).
DEVBOX_CI_DIR="${REDIACC_CI_ROOT:+$REDIACC_CI_ROOT/.ci}"
DEVBOX_CI_DIR="${DEVBOX_CI_DIR:-$(cd "$DEVBOX_LIB_DIR/.." && pwd)}"
if [[ ! -d "$DEVBOX_CI_DIR/rediacc_ci/core" ]]; then
    echo "devbox.sh: cannot find rediacc_ci under '$DEVBOX_CI_DIR' (set REDIACC_CI_ROOT)" >&2
    return 1
fi
if ! command -v python3 >/dev/null 2>&1; then
    echo "devbox.sh: python3 is required; the port logic lives in rediacc_ci.core.ports" >&2
    return 1
fi

DEVBOX_LABEL_KEY="com.rediacc.devbox.worktree"
# The hostname the container was BUILT with, baked in as a label so it can be
# read back. The worktree label above is the identity key (a path never changes
# under a container); this one is a fact about the routers already created, and
# it is allowed to disagree with what this checkout would compute today.
DEVBOX_SLUG_LABEL_KEY="com.rediacc.devbox.slug"

# =============================================================================
# IDENTITY
# =============================================================================

# The worktree this checkout is, resolved absolutely (the label/port key).
devbox_worktree() {
    local path="${CONSOLE_ROOT_DIR:-$PWD}"
    # Fall back to the literal value when the directory is gone. `cd` into a
    # deleted worktree fails, the substitution yields EMPTY, and every caller
    # then builds `label=com.rediacc.devbox.worktree=` -- a filter that matches
    # nothing, so a removed worktree's container can never be found again.
    (cd "$path" 2>/dev/null && pwd -P) || printf '%s\n' "$path"
}

# The directory that must be bind-mounted.
#
# NOT simply the worktree: a git worktree's .git file holds an ABSOLUTE gitdir
# path back into the main checkout, so mounting only the worktree gives a
# container where every git command fails. Mounting the main checkout covers
# both, because worktrees live under it (scripts/dev/worktree.sh:22).
devbox_mount_root() {
    local common_dir
    if common_dir="$(git -C "$(devbox_worktree)" rev-parse --git-common-dir 2>/dev/null)"; then
        # --git-common-dir may be relative to the worktree.
        case "$common_dir" in
            /*) : ;;
            *) common_dir="$(devbox_worktree)/$common_dir" ;;
        esac
        (cd "$common_dir/.." && pwd -P)
        return 0
    fi
    devbox_worktree
}

devbox_container_name() {
    local wt slot
    wt="$(devbox_worktree)"
    slot="$(PYTHONPATH="$DEVBOX_CI_DIR${PYTHONPATH:+:$PYTHONPATH}" \
        python3 -m rediacc_ci.core.ports derive-slot "$wt" 100)"
    printf 'rediacc-devbox-%s-%s\n' "$slot" "$(basename "$wt")"
}

# docker, or sudo docker when the group is not active in this shell yet.
devbox_docker() {
    if docker version &>/dev/null; then
        echo docker
    elif sudo -n docker version &>/dev/null || sudo docker version &>/dev/null; then
        echo "sudo docker"
    else
        echo docker
    fi
}

# =============================================================================
# STATE
# =============================================================================

devbox_state_write() {
    local base_port="$1" container="$2" digest="$3" docker_gid="$4" slug="${5:-}"
    cat >"$DEVBOX_STATE_FILE" <<EOF
# Generated by ./run.sh setup - do not edit
worktree=$(devbox_worktree)
container=$container
base_port=$base_port
slug=$slug
image=$DEVBOX_IMAGE
image_digest=$digest
docker_gid=$docker_gid
uid=$(id -u)
gid=$(id -g)
gate_lane=${REDIACC_GATE_LANE:-devbox}
EOF
}

devbox_state_get() {
    local key="$1"
    [[ -f "$DEVBOX_STATE_FILE" ]] || return 1
    sed -n "s/^${key}=//p" "$DEVBOX_STATE_FILE" | head -1
}

# =============================================================================
# PORTS
# =============================================================================

# Stable base port for this worktree. A previously allocated base is reused from
# state so a temporarily busy neighbour cannot shuffle an established devbox.
devbox_base_port() {
    local saved

    # The state file is the record: the container publishes NO ports, so there
    # is nothing to ask the daemon for. (An earlier version inspected the
    # published HostPort; that branch became unreachable when the proxy became
    # the only ingress.)
    if saved="$(devbox_state_get base_port)" && [[ -n "$saved" ]]; then
        echo "$saved"
        return 0
    fi

    # First time: derive from the worktree path.
    PYTHONPATH="$DEVBOX_CI_DIR${PYTHONPATH:+:$PYTHONPATH}" \
        python3 -m rediacc_ci.core.ports find-port-block "$(devbox_worktree)" \
        "$DEVBOX_PORT_RANGE_START" "$DEVBOX_PORT_RANGE_END" "$DEVBOX_PORT_BLOCK"
}

# =============================================================================
# HOSTNAME
# =============================================================================
#
# The slug IS the hostname -- the branch-name-in-the-URL idea a numeric port
# block could not express -- and it also names the traefik ROUTERS themselves
# (`traefik.http.routers.${slug}-code`), so it is not merely cosmetic: two
# checkouts producing one slug produce duplicate router and service names, and
# traefik drops one of them at --log.level=WARN without saying so.
#
# It is deliberately NOT an identity key. The container is found by its worktree
# PATH label, and the port block is derived from that path: both must survive a
# branch rename, which the hostname does not.

# The checked-out branch, or empty.
#
# symbolic-ref --quiet, NOT `rev-parse --abbrev-ref HEAD`. The latter prints the
# literal string HEAD when detached, which sanitises to the perfectly valid
# hostname `head.localhost` -- so every detached worktree on the machine would
# converge on ONE hostname and ONE router name. symbolic-ref answers empty for
# detached, mid-rebase and mid-bisect alike, and empty is what the callers here
# are built to handle.
devbox_branch() {
    git -C "$(devbox_worktree)" symbolic-ref --quiet --short HEAD 2>/dev/null || true
}

# Turn an arbitrary string into a DNS label. Pure: no git, no docker, no
# filesystem, so it is hermetically testable.
#
# Output matches ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$ or is empty. Runs of
# dashes are COLLAPSED, which the old basename-only rule did not do: `feat//x`
# used to become `feat--x`.
devbox_slugify() { # devbox_slugify <string>
    local s
    # LC_ALL=C so the byte-level classes mean the same thing everywhere; a
    # multibyte branch name (feat/uber with an umlaut) becomes one dash, not a
    # locale-dependent number of them.
    s="$(LC_ALL=C printf '%s' "${1:-}" |
        LC_ALL=C tr '[:upper:]' '[:lower:]' |
        LC_ALL=C sed 's/[^a-z0-9-]/-/g; s/--*/-/g; s/^-*//; s/-*$//')"
    LC_ALL=C printf '%s\n' "${s:0:40}" | LC_ALL=C sed 's/^-*//; s/-*$//'
}

# The pre-branch rule, kept EXACTLY as it was: it is the fallback, and being the
# old behaviour verbatim is what makes existing containers keep their names.
devbox_slug_basename() {
    basename "$(devbox_worktree)" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g; s/^-*//; s/-*$//'
}

# What THIS checkout would be hosted as right now.
devbox_slug() {
    local s
    if [[ -n "${DEVBOX_SLUG:-}" ]]; then
        # The manual escape hatch for two checkouts on one branch. Still
        # sanitised: an invalid Host rule is a route traefik silently ignores.
        s="$(devbox_slugify "$DEVBOX_SLUG")"
        [[ -n "$s" ]] && {
            printf '%s\n' "$s"
            return 0
        }
    fi
    s="$(devbox_slugify "$(devbox_branch)")"
    [[ -n "$s" ]] || s="$(devbox_slug_basename)"
    printf '%s\n' "$s"
}

# What the RUNNING container was built with -- the name its routers actually
# carry. Everything the operator is shown, and every probe, must use this and
# not a freshly computed slug: after a branch rename the two disagree, and a
# probe against the recomputed name reaches no router at all.
devbox_slug_active() {
    local d cid s
    cid="$(devbox_container_id)"
    if [[ -z "$cid" ]]; then
        devbox_slug
        return 0
    fi
    d="$(devbox_docker)"
    s="$($d inspect -f "{{index .Config.Labels \"$DEVBOX_SLUG_LABEL_KEY\"}}" "$cid" 2>/dev/null || true)"
    [[ "$s" == "<no value>" ]] && s=""
    # A container created before this label existed is hosted under the old
    # basename rule, which is exactly what it was created with.
    [[ -n "$s" ]] || s="$(devbox_slug_basename)"
    printf '%s\n' "$s"
}

# The disagreements worth telling the operator about. Pure, for testability:
# the caller supplies the three names.
devbox_slug_drift() { # devbox_slug_drift <wanted> <baked> [<recorded>]
    local want="$1" baked="${2:-}" recorded="${3:-}"
    if [[ -n "$baked" && -n "$want" && "$baked" != "$want" ]]; then
        printf 'drift: the container serves %s, this checkout would use %s\n' "$baked" "$want"
    fi
    if [[ -n "$recorded" && -n "$baked" && "$recorded" != "$baked" ]]; then
        printf 'drift: .devbox-state records %s, the container serves %s\n' "$recorded" "$baked"
    fi
    return 0
}

# Other checkouts' containers already claiming this hostname. Prints their
# worktree paths; empty output means no conflict.
devbox_slug_conflicts() { # devbox_slug_conflicts [slug]
    local d slug wt cid other
    slug="${1:-}"
    [[ -n "$slug" ]] || slug="$(devbox_slug)"
    [[ -n "$slug" ]] || return 0
    wt="$(devbox_worktree)"
    d="$(devbox_docker)"
    while read -r cid; do
        [[ -n "$cid" ]] || continue
        other="$($d inspect -f "{{index .Config.Labels \"$DEVBOX_LABEL_KEY\"}}" "$cid" 2>/dev/null || true)"
        [[ "$other" == "<no value>" ]] && other=""
        [[ -n "$other" && "$other" != "$wt" ]] && printf '%s\n' "$other"
    done < <($d ps -aq --filter "label=${DEVBOX_SLUG_LABEL_KEY}=$slug" 2>/dev/null || true)
    return 0
}

# Every hostname the running container actually declares a router for. The
# authority for "is this 404 traefik saying no-such-router, or the backend
# saying not-found?" -- a question the status code alone cannot answer.
devbox_router_hosts() {
    local d cid
    cid="$(devbox_container_id)"
    [[ -n "$cid" ]] || return 0
    d="$(devbox_docker)"
    $d inspect -f '{{range $k, $v := .Config.Labels}}{{$v}}{{"\n"}}{{end}}' "$cid" 2>/dev/null |
        sed -n 's/.*Host(`\([^`]*\)`).*/\1/p'
}

devbox_url() { # devbox_url [suffix] [slug]
    local suffix="${1:-}" slug="${2:-}"
    # Default to the CONTAINER's name, never a recomputed one: printing a URL
    # this checkout would use, for a container hosted under another name, is the
    # exact lie this parameter exists to prevent.
    [[ -n "$slug" ]] || slug="$(devbox_slug_active)"
    [[ -n "$suffix" ]] && slug="${slug}-${suffix}"
    echo "http://${slug}.${DEVBOX_DOMAIN}:${DEVBOX_PROXY_PORT}"
}

# =============================================================================
# REVERSE PROXY (one per machine, shared by every worktree)
# =============================================================================

devbox_network_ensure() {
    local d
    d="$(devbox_docker)"
    $d network inspect "$DEVBOX_NETWORK" &>/dev/null && return 0
    log_step "Creating docker network $DEVBOX_NETWORK"
    $d network create "$DEVBOX_NETWORK" >/dev/null
}

devbox_proxy_running() {
    local d
    d="$(devbox_docker)"
    [[ "$($d inspect -f '{{.State.Running}}' "$DEVBOX_PROXY_NAME" 2>/dev/null)" == "true" ]]
}

devbox_proxy_ensure() {
    local d
    d="$(devbox_docker)"

    devbox_network_ensure || return 1
    devbox_proxy_running && return 0

    # A stopped leftover: start it rather than fighting over the name.
    if $d inspect "$DEVBOX_PROXY_NAME" &>/dev/null; then
        $d start "$DEVBOX_PROXY_NAME" >/dev/null && return 0
    fi

    log_step "Starting the devbox proxy on :$DEVBOX_PROXY_PORT"
    # The docker provider reads labels off the containers themselves, so adding a
    # worktree needs no proxy config change. exposedByDefault=false means a
    # container is only routed when it opts in with traefik.enable=true.
    $d run -d \
        --name "$DEVBOX_PROXY_NAME" \
        --restart unless-stopped \
        --network "$DEVBOX_NETWORK" \
        -p "$DEVBOX_PROXY_PORT:80" \
        -v /var/run/docker.sock:/var/run/docker.sock:ro \
        "$DEVBOX_PROXY_IMAGE" \
        --providers.docker=true \
        --providers.docker.exposedByDefault=false \
        --providers.docker.network="$DEVBOX_NETWORK" \
        --entrypoints.web.address=:80 \
        --log.level=WARN >/dev/null || {
        log_error "Could not start the devbox proxy"
        return 1
    }

    local i
    for ((i = 0; i < 30; i++)); do
        # 404 is a healthy Traefik with no matching route; connection refused is not.
        if curl -s -o /dev/null --max-time 2 "http://127.0.0.1:$DEVBOX_PROXY_PORT/"; then
            return 0
        fi
        sleep 1
    done
    log_error "Proxy started but is not answering on :$DEVBOX_PROXY_PORT"
    $d logs --tail 20 "$DEVBOX_PROXY_NAME" >&2 || true
    return 1
}

devbox_proxy_stop() {
    local d
    d="$(devbox_docker)"
    devbox_proxy_running || {
        log_warn "Proxy is not running"
        return 0
    }
    $d stop "$DEVBOX_PROXY_NAME" >/dev/null && log_info "Proxy stopped"
}

# =============================================================================
# IMAGE
# =============================================================================

devbox_image_present() {
    local d
    d="$(devbox_docker)"
    $d image inspect "$DEVBOX_IMAGE" &>/dev/null
}

devbox_image_digest() {
    local d
    d="$(devbox_docker)"
    $d image inspect --format '{{index .RepoDigests 0}}' "$DEVBOX_IMAGE" 2>/dev/null || echo unknown
}

devbox_ensure_image() {
    local force_pull="${1:-false}"
    local d
    d="$(devbox_docker)"

    if devbox_image_present && [[ "$force_pull" != true ]]; then
        log_debug "Image present: $DEVBOX_IMAGE"
        return 0
    fi

    log_step "Pulling $DEVBOX_IMAGE"
    log_info "This image carries node, go, playwright deps and a desktop; the first pull is several GB and takes a while."
    if $d pull "$DEVBOX_IMAGE"; then
        return 0
    fi

    # ghcr.io/rediacc/* is private. A GitHub token needs the read:packages
    # scope to pull it -- repo+workflow is NOT enough, and the registry's only
    # signal is the word "denied", which reads like the image does not exist.
    log_warn "Could not pull $DEVBOX_IMAGE"
    log_info "That registry is private. To pull it, a GitHub token needs the read:packages scope:"
    log_info "    echo \$PAT | docker login ghcr.io -u <user> --password-stdin"
    log_info "Falling back to building the image locally from .devcontainer/Dockerfile."
    devbox_build_image
}

# Build the devcontainer image from source.
#
# The fallback for a machine with no registry access. Slower than a pull (this
# Dockerfile installs a Go toolchain, Node, a desktop and Playwright deps), but
# it needs no credentials, which is the whole point.
devbox_build_image() {
    local d dockerfile_dir
    d="$(devbox_docker)"
    dockerfile_dir="$(devbox_mount_root)/.devcontainer"

    [[ -f "$dockerfile_dir/Dockerfile" ]] || {
        log_error "No Dockerfile at $dockerfile_dir"
        return 1
    }

    log_step "Building $DEVBOX_IMAGE locally (this takes a while)"
    $d build -t "$DEVBOX_IMAGE" -f "$dockerfile_dir/Dockerfile" "$dockerfile_dir" || {
        log_error "Local image build failed"
        return 1
    }
    log_info "Built $DEVBOX_IMAGE"
}

# =============================================================================
# CONTAINER
# =============================================================================

# Find this worktree's container by LABEL, not by name: two different checkouts
# can each contain a worktree called 0824-1, and the daemon is the truth while
# the state file is only a cache.
devbox_container_id() {
    local d
    d="$(devbox_docker)"
    $d ps -aq --filter "label=${DEVBOX_LABEL_KEY}=$(devbox_worktree)" 2>/dev/null | head -1
}

devbox_container_running() {
    local d cid
    d="$(devbox_docker)"
    cid="$(devbox_container_id)"
    [[ -n "$cid" ]] || return 1
    [[ "$($d inspect -f '{{.State.Running}}' "$cid" 2>/dev/null)" == "true" ]]
}

_devbox_bind_if_present() {
    # Only bind paths that already exist. Docker CREATES a missing source as a
    # root-owned directory on the host, which is how a bind mount silently turns
    # into an unwritable ~/.claude.
    local src="$1" dst="$2" mode="${3:-}"
    [[ -e "$src" ]] || return 0
    if [[ -n "$mode" ]]; then
        printf -- '-v\n%s:%s:%s\n' "$src" "$dst" "$mode"
    else
        printf -- '-v\n%s:%s\n' "$src" "$dst"
    fi
}

# The tracked scripts bound into every devbox, one "<source under .devcontainer/>:<container path>" pair per line. Data rather than inline `-v` flags so devbox_up and devbox_missing_binds read ONE list: a bind exists only from `docker run` on, so a container created before a line was added lacks it forever, and devbox_missing_binds is how devbox_up notices and recreates.
#
# devbox-bws.sh is the login-shell hook that exports BWS_ACCESS_TOKEN from the host's private/account/.env (reached through the repo bind, never copied), so `bws` works inside the devbox without the token entering the image, Config.Env, a label or a log.
devbox_script_binds() {
    printf '%s\n' \
        "devbox-entrypoint.sh:/usr/local/bin/devbox-entrypoint.sh" \
        "devbox-autostart.sh:/usr/local/bin/devbox-autostart.sh" \
        "start-ttyd.sh:/usr/local/bin/start-ttyd.sh" \
        "devbox-bws.sh:/etc/profile.d/zz-devbox-bws.sh"
}

# Host files bound by NAME into the container user's home, one "<path relative to $HOME>:<mode>" pair per line (mode empty for read-write). Each is bound only when it exists on the host (_devbox_bind_if_present says why).
#
# .config/rediacc-console holds the console's own bootstrap credential, the token-only file bws-access-token that devbox-bws.sh reads first. Read-only, and deliberately NOT inside .config/rediacc: that directory is the rdc CLI's read-write state, and a CLI or E2E run must not be able to delete the console's root credential.
DEVBOX_CONTAINER_HOME="/home/vscode"
devbox_home_binds() {
    printf '%s\n' \
        ".gitconfig:ro" \
        ".git-credentials:ro" \
        ".config/gh:" \
        ".config/rediacc-console:ro" \
        ".claude:" \
        ".claude.json:" \
        ".config/rediacc:"
}

# Print each bind destination the existing container does NOT have mounted, one per line: every devbox_script_binds entry, plus every devbox_home_binds entry whose host source exists now (one created on the host after the container was, such as .config/rediacc-console, is drift too). Empty when there is no container, or when docker cannot inspect it: an unanswerable probe must never be the reason a container is destroyed.
devbox_missing_binds() {
    local d cid mounts pair dest
    d="$(devbox_docker)"
    cid="$(devbox_container_id)"
    [[ -n "$cid" ]] || return 0
    mounts="$($d inspect -f '{{range .Mounts}}{{.Destination}}{{"\n"}}{{end}}' "$cid" 2>/dev/null)" || return 0
    [[ -n "$mounts" ]] || return 0
    while IFS= read -r pair; do
        dest="${pair#*:}"
        if ! grep -qxF -- "$dest" <<<"$mounts"; then
            printf '%s\n' "$dest"
        fi
    done < <(devbox_script_binds)
    while IFS= read -r pair; do
        pair="${pair%%:*}"
        [[ -e "$HOME/$pair" ]] || continue
        dest="$DEVBOX_CONTAINER_HOME/$pair"
        if ! grep -qxF -- "$dest" <<<"$mounts"; then
            printf '%s\n' "$dest"
        fi
    done < <(devbox_home_binds)
}

devbox_up() { # devbox_up [force_pull] [--no-rehost]
    local force_pull="${1:-false}"
    # The opt-out, honoured from either side: the positional flag for a direct
    # caller, and DEVBOX_NO_REHOST as an env alternative. The dispatch in run.sh
    # NOW FORWARDS its args, so `./run.sh devbox up --no-rehost` works -- until
    # that was wired the flag existed here and nothing could reach it, which is
    # why the drift banner used to advise the env form instead.
    local rehost=true
    case "${2:-}" in
        --no-rehost | false | no) rehost=false ;;
    esac
    [[ "${DEVBOX_NO_REHOST:-}" == 1 || "${DEVBOX_NO_REHOST:-}" == true ]] && rehost=false
    local d base_port mount_root workspace name docker_gid cid
    d="$(devbox_docker)"

    # REHOST ON DRIFT. The routers are baked at `docker run`, so a container
    # created on another branch keeps serving the old hostname forever. Recreate
    # it, with two guards:
    #
    #  - say exactly what is about to be destroyed BEFORE destroying it; the
    #    container may be running `account dev`, a VS Code session, or an agent.
    #  - never rehost while devbox_branch is EMPTY. Mid-rebase and detached HEAD
    #    both drift the name to the basename fallback, and churning the container
    #    back and forth across a rebase is worse than a stale URL.
    cid="$(devbox_container_id)"
    if [[ -n "$cid" ]]; then
        local want baked branch
        want="$(devbox_slug)"
        baked="$(devbox_slug_active)"
        branch="$(devbox_branch)"
        if [[ -n "$branch" && -n "$baked" && "$baked" != "$want" ]]; then
            if [[ "$rehost" != true ]]; then
                log_warn "Hostname drift: the container serves ${baked}.${DEVBOX_DOMAIN}, this checkout is now ${want}.${DEVBOX_DOMAIN}"
                log_info "--no-rehost given: leaving it alone. Its URLs keep the OLD name."
            else
                log_warn "Hostname drift: the container serves ${baked}.${DEVBOX_DOMAIN}, this checkout is now ${want}.${DEVBOX_DOMAIN}"
                log_warn "About to DESTROY and recreate this container so the URL matches the branch:"
                log_info "  container:  $(devbox_container_name)"
                log_info "  killed:     anything running inside it (account dev, VS Code sessions, agents)"
                log_info "  kept:       the repo itself -- it is a bind mount from the host"
                log_info "  keep the old hostname instead: DEVBOX_NO_REHOST=1 ./run.sh devbox up"
                devbox_remove || return 1
                cid=""
            fi
        fi
    fi

    # RECREATE ON BIND DRIFT, under the same guard and opt-out as the hostname. Without it, a bind added to devbox_script_binds never reaches an existing container: "already running" returns early below and `docker start` keeps the old mount table.
    if [[ -n "$cid" ]]; then
        local missing_binds missing_one
        missing_binds="$(devbox_missing_binds)"
        if [[ -n "$missing_binds" ]]; then
            log_warn "Bind drift: the container predates these bind mounts:"
            while IFS= read -r missing_one; do log_info "  $missing_one"; done <<<"$missing_binds"
            if [[ "$rehost" != true ]]; then
                log_info "--no-rehost given: leaving it alone. Those files stay absent inside it."
            else
                log_warn "About to DESTROY and recreate this container to add them:"
                log_info "  container:  $(devbox_container_name)"
                log_info "  killed:     anything running inside it (account dev, VS Code sessions, agents)"
                log_info "  kept:       the repo itself -- it is a bind mount from the host"
                log_info "  keep the container as it is instead: DEVBOX_NO_REHOST=1 ./run.sh devbox up"
                devbox_remove || return 1
                cid=""
            fi
        fi
    fi

    if devbox_container_running; then
        log_info "Devbox already running for this worktree"
        devbox_status
        return 0
    fi

    cid="$(devbox_container_id)"
    if [[ -n "$cid" ]]; then
        log_step "Starting existing devbox container"
        $d start "$cid" >/dev/null
        devbox_status
        return 0
    fi

    devbox_ensure_image "$force_pull" || return 1
    devbox_proxy_ensure || return 1

    base_port="$(devbox_base_port)" || {
        log_error "No free port block in ${DEVBOX_PORT_RANGE_START}-${DEVBOX_PORT_RANGE_END}"
        return 1
    }
    mount_root="$(devbox_mount_root)"
    workspace="$(devbox_worktree)"
    name="$(devbox_container_name)"
    docker_gid="$(getent group docker 2>/dev/null | cut -d: -f3)"

    # KVM PASSTHROUGH, and why it is conditional rather than unconditional.
    #
    # Until 2026-09-07 this `docker run` passed no `--device` at all, so a devbox
    # on a KVM-capable host had NO /dev/kvm and `rdc ops` could never boot a VM
    # inside it. The image has shipped qemu-kvm, libvirt-daemon-system, virtinst
    # and dnsmasq-base since the beginning (.devcontainer/Dockerfile:148-155), so
    # everything was provisioned for a device that was never bound -- which is
    # why this survived so long: nothing was missing except the one flag.
    #
    # THE GID IS DERIVED, NEVER HARDCODED, and this is the part that makes the
    # difference between a bound device and a usable one. `--device` reproduces
    # the host's owning GROUP inside the container, not the container's own `kvm`
    # group: measured here, the host device is gid 991 while the image's `kvm`
    # group is gid 105. So the Dockerfile's `usermod -aG kvm vscode` grants
    # NOTHING on the bound node, and start-kvm.sh papered over that with
    # `sudo chmod 0666 /dev/kvm` -- world-writable, at runtime, needing sudo.
    # Adding the HOST gid to the container user is the same trick this function
    # already plays for docker two lines up, it needs no sudo, and it widens no
    # permissions beyond what the host already models.
    #
    # WHAT LIBVIRT'S DEFAULT NETWORK NEEDS, measured rather than assumed. It is a
    # NAT bridge, so starting it creates virbr0 and brings it up: that needs
    # NET_ADMIN. It ALSO writes a per-bridge sysctl, and that is the part no
    # capability can grant -- docker mounts /proc/sys read-only, so the real
    # error (recovered only by removing the `2>/dev/null` at start-kvm.sh:136)
    # was:
    #
    #   cannot write to '/proc/sys/net/ipv6/conf/virbr0/disable_ipv6'
    #   on bridge 'virbr0': Read-only file system
    #
    # SYS_ADMIN plus a remount in start-kvm.sh is how /proc/sys becomes writable,
    # and the alternative was measured before it was rejected. Operator ruling
    # 2026-09-07, on these numbers:
    #
    #   --security-opt systempaths=unconfined   works, adds NO capability, but
    #     flips /proc/sysrq-trigger and /proc/sys/kernel/core_pattern from
    #     read-only to WRITABLE. The first can reboot the host; the second is a
    #     documented container-escape vector. (/proc/kcore is readable+writable
    #     either way, so it is not part of the delta.)
    #   --cap-add SYS_ADMIN + remount           works, keeps docker's /proc masks
    #     intact so both of those stay read-only. SYS_ADMIN is a broad capability,
    #     but it widens what the container may DO rather than handing it two
    #     concrete host-damage primitives.
    #   --privileged                            strictly wider than either and
    #     buys nothing more here.
    #
    # TWO ROUTES THAT NEED NO PRIVILEGE AT ALL WERE TRIED AND REFUTED, recorded so
    # nobody repeats the experiments:
    #
    #   network XML with ipv6="yes"                    -> 0 active. libvirt writes
    #     net.ipv6.conf.virbr0.disable_ipv6 regardless of what the network declares.
    #   --sysctl net.ipv6.conf.{all,default}.disable_ipv6=1 -> 0 active. Setting the
    #     namespaced sysctl does not stop libvirt writing the per-bridge one, which
    #     does not exist until virbr0 does.
    #
    # THE MINIMUM WAS MEASURED, not guessed. Three probes on this host, counting
    # active networks after libvirtd came up:
    #
    #   NET_ADMIN + NET_RAW + unconfined -> 1 active
    #   NET_ADMIN           + unconfined -> 1 active
    #   no caps             + unconfined -> 0 active
    #
    # So NET_RAW is NOT required and was dropped: dnsmasq gets its DHCP socket
    # without it here. `--privileged` would also work and is what most guides
    # reach for; it is refused because it grants every capability plus
    # unrestricted device access to a container that already mounts the
    # workspace, when one capability and one unmask are provably enough.
    #
    # Empty on a host without KVM, and every expansion below then vanishes, so a
    # machine with no nested virtualisation still starts a clean devbox.
    local kvm_gid=""
    if [ -e /dev/kvm ]; then
        kvm_gid="$(stat -c '%g' /dev/kvm 2>/dev/null || true)"
    fi

    # /dev/net/tun IS A SECOND DEVICE, and binding only /dev/kvm is a half fix.
    # Found 2026-09-07 by driving the real thing: with /dev/kvm bound, libvirtd
    # running and the default network ACTIVE, `./rdc.sh ops up --basic` still
    # died inside virt-install with
    #
    #   ERROR Unable to open /dev/net/tun, is tun module loaded?
    #
    # because a container gets no /dev/net at all unless the node is passed in.
    # qemu opens /dev/net/tun itself to attach the guest NIC to virbr0, so a
    # devbox with KVM but no tun boots a CPU that cannot be given a network
    # interface: every VM fails at creation.
    #
    # NO --group-add here, deliberately, and the asymmetry with /dev/kvm above
    # is a property of the two nodes rather than an oversight. The host's
    # /dev/kvm is 0660 root:<kvm gid>, so access needs the owning group; the
    # host's /dev/net/tun is 0666 root:root, so it is already world readable and
    # writable and the container user needs nothing. Adding its owning gid would
    # mean adding gid 0.
    #
    # Gated on the node existing rather than on kvm_gid: they are separate host
    # facts (tun is a module, KVM is hardware plus a module), so a host missing
    # either one still starts a clean devbox with the other bound.
    local tun_dev=""
    if [ -e /dev/net/tun ]; then
        tun_dev=/dev/net/tun
    fi

    local vscode_port=$((base_port + DEVBOX_OFFSET_VSCODE))
    local studio_port=$((base_port + DEVBOX_OFFSET_STUDIO))
    local term_port=$((base_port + DEVBOX_OFFSET_TERM))

    local -a binds=()
    # The repo at its IDENTICAL path. Non-negotiable: worktree gitdir links are
    # absolute, and a nested `docker -v $(pwd)` is resolved by the host daemon,
    # so only an identical path is correct in both.
    binds+=(-v "$mount_root:$mount_root")
    # The tracked scripts, from devbox_script_binds, all read-only. The notes below say why autostart and start-ttyd are bound rather than baked; devbox-bws.sh is bound so the token is read from the host file at shell start and never baked.
    local script_pair
    while IFS= read -r script_pair; do
        binds+=(-v "$DEVBOX_LIB_DIR/../../.devcontainer/${script_pair%%:*}:${script_pair#*:}:ro")
    done < <(devbox_script_binds)
    # The entrypoint resolves its helper as `$(dirname "$0")/devbox-autostart.sh`,
    # i.e. /usr/local/bin/. Bind-mounted rather than baked into the image for the
    # same reason as the entrypoint itself: both are edited far more often than
    # the image is rebuilt, and an entrypoint change that needed a rebuild would
    # simply never be tested. Missing this bind is silent -- the entrypoint's
    # `[ -x "$AUTOSTART" ]` guard turns "the file is not there" into "autostart
    # is disabled", which looks exactly like working as intended.
    # start-ttyd.sh, for the third time and the same reason. It is ALSO baked into
    # the image (Dockerfile COPYs it, and the hub invokes that copy by name), so
    # skipping this bind looks harmless -- the file is there either way. It is not:
    # the baked copy is only as new as the last image publish, so every fix to the
    # terminal would be untestable locally and land unverified. Measured while
    # wiring this up: the container was running an August 23 copy whose idempotency
    # guard read a PID file nothing ever wrote.
    [[ -S /var/run/docker.sock ]] && binds+=(-v /var/run/docker.sock:/var/run/docker.sock)

    # Credentials and agent config, named rather than the whole $HOME: ~/.ssh
    # and cloud credentials stay out of the container.
    # The list is devbox_home_binds, shared with devbox_missing_binds.
    local home_pair home_rel
    while IFS= read -r home_pair; do
        home_rel="${home_pair%%:*}"
        while IFS= read -r line; do [[ -n "$line" ]] && binds+=("$line"); done < <(
            _devbox_bind_if_present "$HOME/$home_rel" "$DEVBOX_CONTAINER_HOME/$home_rel" "${home_pair#*:}"
        )
    done < <(devbox_home_binds)

    local slug conflicts line
    slug="$(devbox_slug)"

    # REFUSE a hostname another checkout already owns. The slug names the
    # ROUTERS and SERVICES, not just the Host rules, so a duplicate is not two
    # routes to one name -- it is two definitions of one router, and traefik
    # drops one at --log.level=WARN with nothing on stdout. No automatic suffix:
    # that would silently destroy the memorable URL this whole change exists for.
    conflicts="$(devbox_slug_conflicts "$slug")"
    if [[ -n "$conflicts" ]]; then
        log_error "The hostname ${slug}.${DEVBOX_DOMAIN} is already claimed by another checkout:"
        while IFS= read -r line; do
            [[ -n "$line" ]] && log_info "  $line"
        done <<<"$conflicts"
        log_info "Two checkouts on one branch produce duplicate traefik router names and one route is silently dropped."
        log_info "Give this checkout its own name: DEVBOX_SLUG=<name> ./run.sh devbox up"
        return 1
    fi

    # Traefik labels. Routing is by Host header, so every service keeps its own
    # root path and none of them need base-path configuration.
    local -a labels=(
        --label "traefik.enable=true"
        --label "traefik.docker.network=$DEVBOX_NETWORK"
        # VS Code
        --label "traefik.http.routers.${slug}-code.rule=Host(\`${slug}.${DEVBOX_DOMAIN}\`)"
        --label "traefik.http.routers.${slug}-code.entrypoints=web"
        --label "traefik.http.routers.${slug}-code.service=${slug}-code"
        --label "traefik.http.services.${slug}-code.loadbalancer.server.port=$vscode_port"
        # The account gateway is the ONLY app door: it serves the marketing
        # site at /, the portal at /account/ and the API at /account/api/, all
        # proxying to the same live dev servers. A second hostname pointed
        # straight at Astro used to exist; it cost no CPU (both doors reach
        # processes `account dev` starts anyway) but it 404'd on /account, which
        # is the half of the app people actually want.
        --label "traefik.http.routers.${slug}-account.rule=Host(\`${slug}-account.${DEVBOX_DOMAIN}\`)"
        --label "traefik.http.routers.${slug}-account.entrypoints=web"
        --label "traefik.http.routers.${slug}-account.service=${slug}-account"
        --label "traefik.http.services.${slug}-account.loadbalancer.server.port=4800"
        # Database browser. `account db` serves sqlite_web here, whose UI comes
        # from this same origin -- so there is no hosted third-party page and no
        # Local Network Access permission to grant. (An earlier version
        # redirected this route's root to local.drizzle.studio; a real browser
        # showed Chrome blocking that page from reaching the local server, and
        # the redirect also 307'd Drizzle's own `POST /` API.)
        --label "traefik.http.routers.${slug}-db.rule=Host(\`${slug}-db.${DEVBOX_DOMAIN}\`)"
        --label "traefik.http.routers.${slug}-db.entrypoints=web"
        --label "traefik.http.routers.${slug}-db.service=${slug}-db"
        --label "traefik.http.services.${slug}-db.loadbalancer.server.port=$studio_port"
        # Browser terminal: ttyd serving an attach-or-create tmux session, started
        # by devbox-autostart.sh. A ROUTE and not a published port, for the same
        # reason as the three above -- on ChromeOS every published port needs its
        # own manual forward, and the proxy is the machine's only ingress.
        #
        # ttyd's terminal is a WebSocket upgrade. Traefik v3 proxies Upgrade with
        # no middleware, so there is nothing extra here; the thing to know is that
        # a BROKEN upgrade still answers 200 on `/`, so the status probe below
        # cannot see it and only a browser can.
        --label "traefik.http.routers.${slug}-term.rule=Host(\`${slug}-term.${DEVBOX_DOMAIN}\`)"
        --label "traefik.http.routers.${slug}-term.entrypoints=web"
        --label "traefik.http.routers.${slug}-term.service=${slug}-term"
        --label "traefik.http.services.${slug}-term.loadbalancer.server.port=$term_port"
    )

    log_step "Creating devbox for $workspace"
    log_info "container: $name"
    log_info "hostname:  ${slug}.${DEVBOX_DOMAIN}"
    log_info "reachable ONLY through the proxy on :${DEVBOX_PROXY_PORT}; the container publishes no ports"

    # Published on 0.0.0.0, not 127.0.0.1: on ChromeOS the browser is outside
    # this VM and reaches it by address, so a loopback-only publish is invisible.
    $d run -d \
        --name "$name" \
        --label "${DEVBOX_LABEL_KEY}=$workspace" \
        --label "${DEVBOX_SLUG_LABEL_KEY}=$slug" \
        --restart unless-stopped \
        --init \
        --shm-size=1g \
        --hostname "$(basename "$workspace")-devbox" \
        --network "$DEVBOX_NETWORK" \
        "${labels[@]}" \
        "${binds[@]}" \
        ${docker_gid:+--group-add "$docker_gid"} \
        ${kvm_gid:+--device /dev/kvm} \
        ${tun_dev:+--device /dev/net/tun} \
        ${kvm_gid:+--group-add "$kvm_gid"} \
        ${kvm_gid:+--cap-add NET_ADMIN} \
        ${kvm_gid:+--cap-add SYS_ADMIN} \
        -e HOST_UID="$(id -u)" \
        -e HOST_GID="$(id -g)" \
        -e DOCKER_GID="${docker_gid:-}" \
        -e DEVBOX_PORT="$vscode_port" \
        -e DEVBOX_TERM_PORT="$term_port" \
        -e DEVBOX_WORKSPACE="$workspace" \
        -e REDIACC_NPM_RUNTIME=devbox \
        -e REDIACC_DEV_BIND=0.0.0.0 \
        -e REDIACC_DEV_PORT_BASE=4800 \
        -w "$workspace" \
        --entrypoint /usr/local/bin/devbox-entrypoint.sh \
        "$DEVBOX_IMAGE" >/dev/null || {
        log_error "docker run failed"
        return 1
    }

    devbox_state_write "$base_port" "$name" "$(devbox_image_digest)" "${docker_gid:-}" "$slug"

    # Confirm it actually SERVES.
    #
    # is_port_in_use is useless here: docker-proxy binds the published port the
    # instant the container starts, so the port is "in use" even when the
    # process inside crashed on startup. Ask for an HTTP response instead.
    local i
    for ((i = 0; i < 60; i++)); do
        if curl -fsS -o /dev/null --max-time 2 \
            -H "Host: ${slug}.${DEVBOX_DOMAIN}" \
            "http://127.0.0.1:${DEVBOX_PROXY_PORT}/" 2>/dev/null; then
            devbox_status
            return 0
        fi
        if ! devbox_container_running; then
            log_error "Devbox container exited during startup. Last output:"
            $d logs --tail 30 "$(devbox_container_id)" >&2 || true
            return 1
        fi
        sleep 1
    done

    log_error "Devbox started but nothing is listening on $vscode_port after 60s"
    $d logs --tail 30 "$(devbox_container_id)" >&2 || true
    return 1
}

# Turn a probe's HTTP code into the line the operator reads.
#
# Extracted from devbox_status so it can be tested without docker, a proxy or a
# network. The invariant it carries: the WORD must never contradict the CODE.
# "OK (404)" was shipped for one commit and is exactly the failure this guards --
# Drizzle Studio answers 404 at / by design, so the temptation is to call that
# success, which then hides a genuine 404 on any other route behind the same
# label. Reachability and success are different claims; this says "live".
# The third argument is the SHIP-BLOCKER this function grew for. Traefik answers
# 404 for a Host header no router matches, and the old catch-all printed that as
# "live (HTTP 404)" -- three "live" rows whose URLs all 404 in a browser, which
# is precisely the word-contradicts-code lie the paragraph above forbids. The
# status code alone cannot tell traefik's no-such-router 404 from a backend's own
# not-found, so the CALLER supplies the fact: `yes` when the container really
# declares a router for that host, `no` when it does not, `unknown` when nobody
# asked. (Different context, deliberately untouched: the proxy health probe at
# devbox_proxy_ensure treats any answer including 404 as a healthy traefik. That
# is a claim about the PROXY, not about a route.)
devbox_route_label() {
    local code="$1" hint="${2:-}" routed="${3:-unknown}"
    case "$code" in
        000) echo "proxy unreachable" ;;
        502) echo "no backend yet${hint:+ -- $hint}" ;;
        404)
            case "$routed" in
                no) echo "no such router -- nothing serves this hostname" ;;
                yes) echo "live (HTTP $code)" ;;
                *) echo "no matching route, or a backend 404 (HTTP $code)" ;;
            esac
            ;;
        *) echo "live (HTTP $code)" ;;
    esac
}

devbox_status() {
    local base_port
    base_port="$(devbox_base_port 2>/dev/null)"

    if devbox_container_running; then
        log_info "Devbox running: $(devbox_container_name)"

        # The CONTAINER's name, computed once: every URL and every probe Host
        # below must be the name its routers actually carry.
        local _slug _wanted _recorded _drift _hosts _conflicts _line
        _slug="$(devbox_slug_active)"
        _wanted="$(devbox_slug)"
        _recorded="$(devbox_state_get slug 2>/dev/null || true)"
        _hosts="$(devbox_router_hosts)"
        _conflicts="$(devbox_slug_conflicts "$_slug")"

        _drift="$(devbox_slug_drift "$_wanted" "$_slug" "$_recorded")"
        if [[ -n "$_drift" ]]; then
            while IFS= read -r _line; do
                [[ -n "$_line" ]] && log_warn "$_line"
            done <<<"$_drift"
            log_info "Rehost it (this DESTROYS the container): ./run.sh devbox up"
        fi
        if [[ -n "$_conflicts" ]]; then
            log_warn "Another checkout also claims ${_slug}.${DEVBOX_DOMAIN}, so traefik has duplicate routers:"
            while IFS= read -r _line; do
                [[ -n "$_line" ]] && log_info "  $_line"
            done <<<"$_conflicts"
            log_info "Which container answers is not knowable from here. Give one of them DEVBOX_SLUG=<name>."
        fi
        echo ""
        # PROBE each route rather than listing URLs and hoping. Traefik answers a
        # bare 502 when a router matches but nothing is listening behind it, and
        # that page names neither the service nor the reason -- so an operator
        # reads "Bad Gateway" for a backend that was simply never started, or was
        # started on the HOST instead of inside the devbox.
        local _svc _label _code _host _routed
        # The Terminal row carries NO hint on purpose: ttyd is started by
        # devbox-autostart.sh, so there is no command an operator could run to
        # fix a 502 here -- the answer is the container's ttyd.log, not a verb.
        for _svc in "code:VS Code::" \
            "account:Account:account:./run.sh account dev (INSIDE the devbox)" \
            "db:Database:db:./run.sh account db (INSIDE the devbox)" \
            "term:Terminal:term:"; do
            IFS=: read -r _ _label _suffix _hint <<<"$_svc"
            # `|| true` is load-bearing under `set -e`: curl exits non-zero on a
            # timeout (28) or refused connection (7), and a failing command
            # substitution makes the ASSIGNMENT fail, which kills the whole
            # script. A probe that cannot reach a route must report "000", not
            # abort the status command. Observed as `setup --check` exiting 28
            # when the box was loaded enough for one probe to time out.
            _host="${_slug}${_suffix:+-$_suffix}.${DEVBOX_DOMAIN}"
            _code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 \
                -H "Host: $_host" \
                "http://127.0.0.1:${DEVBOX_PROXY_PORT}/" 2>/dev/null || true)"
            [[ -z "$_code" ]] && _code=000
            if printf '%s\n' "$_hosts" | grep -Fxq "$_host"; then _routed=yes; else _routed=no; fi
            if [[ -n "$_conflicts" ]]; then
                # Two containers define this router. The probe cannot tell which
                # one answered, so no reachability claim is honest here.
                printf '  %-9s %-46s %s\n' "$_label:" "$(devbox_url "$_suffix" "$_slug")" \
                    "ambiguous -- two checkouts claim this hostname"
            else
                printf '  %-9s %-46s %s\n' "$_label:" "$(devbox_url "$_suffix" "$_slug")" \
                    "$(devbox_route_label "$_code" "$_hint" "$_routed")"
            fi
        done
        echo ""
        if ! devbox_proxy_running; then
            log_warn "The proxy is not running, so those hostnames will not resolve."
            log_info "Start it with: ./run.sh devbox up"
        fi
        echo "  On ChromeOS forward ONE port -- ${DEVBOX_PROXY_PORT} -- in"
        echo "  Settings > Linux > Port forwarding. Chrome resolves *.localhost itself,"
        echo "  so every worktree and service is reachable through it."
        echo ""
        return 0
    fi
    if [[ -n "$(devbox_container_id)" ]]; then
        log_warn "Devbox container exists but is stopped. Start it with: ./run.sh devbox up"
        return 1
    fi
    log_warn "No devbox for this worktree. Create it with: ./run.sh setup"
    return 1
}

devbox_stop() {
    local d cid
    d="$(devbox_docker)"
    cid="$(devbox_container_id)"
    [[ -n "$cid" ]] || {
        log_warn "No devbox container for this worktree"
        return 0
    }
    log_step "Stopping devbox"
    $d stop "$cid" >/dev/null && log_info "Stopped"
}

devbox_remove() {
    local d cid
    d="$(devbox_docker)"
    cid="$(devbox_container_id)"
    [[ -n "$cid" ]] || {
        log_warn "No devbox container for this worktree"
        return 0
    }
    log_step "Removing devbox"
    $d rm -f "$cid" >/dev/null && rm -f "$DEVBOX_STATE_FILE" && log_info "Removed"
}

devbox_logs() {
    local d
    d="$(devbox_docker)"
    local cid
    cid="$(devbox_container_id)"
    [[ -n "$cid" ]] || {
        log_error "No devbox container for this worktree"
        return 1
    }
    $d logs "${1:---tail=100}" "$cid"
}

devbox_shell() {
    local d cid
    d="$(devbox_docker)"
    cid="$(devbox_container_id)"
    devbox_container_running || {
        log_error "Devbox is not running. Start it with: ./run.sh devbox up"
        return 1
    }
    # -u vscode BY NAME, for the reason spelled out above devbox_exec: the
    # entrypoint has already renumbered `vscode` to the host identity, so the
    # name is right on Linux, macOS (501:20, where gid 20 is dialout) and WSL2,
    # while a numeric id is right only where the host's numbering means
    # something inside the container. This was the one site still using it.
    $d exec -it -u vscode -w "$(devbox_worktree)" "$cid" bash
}

# -----------------------------------------------------------------------------
# NON-INTERACTIVE EXEC, and the three probes that must pass before it is trusted
# -----------------------------------------------------------------------------
#
# devbox_shell() above is `-it ... bash` and cannot run a command. This is its
# missing sibling, and it is what a gate lane routes through.
#
# -u vscode BY NAME, not `$(id -u):$(id -g)`. devbox-entrypoint.sh has already
# renumbered `vscode` to the host identity, so the name is correct on Linux,
# macOS (where id is 501:20 and gid 20 collides with dialout) and WSL2 alike,
# while a numeric id is correct only where the host's numbering means anything.
# Exec as root instead and git refuses the worktree with "dubious ownership",
# `git ls-files` returns empty, and a gate reports a green over zero files --
# measured live on 2026-08-25 while proving this lane works at all.
devbox_exec() {
    local d cid workdir
    d="$(devbox_docker)"
    cid="$(devbox_container_id)"
    devbox_container_running || {
        log_error "Devbox is not running. Start it with: ./run.sh devbox up"
        return 1
    }
    workdir="$(devbox_worktree)"

    # -t ONLY when both stdin and stdout are TTYs. `docker exec -t` allocates a
    # pty, which injects carriage returns; a piped `--json` gate then receives
    # CRs inside its payload and fails to parse for reasons that name nothing.
    local -a flags=(exec -u vscode -w "$workdir")
    [[ -t 0 ]] && flags+=(-i)
    [[ -t 0 && -t 1 ]] && flags+=(-t)
    flags+=(-e REDIACC_IN_DEVBOX=1)
    local v
    for v in CI NO_COLOR TERM GH_TOKEN GITHUB_TOKEN; do
        [[ -n "${!v:-}" ]] && flags+=(-e "$v")
    done

    # bash -lc, not bash -c: PATH for go and node comes from /etc/environment,
    # which only a login shell reads.
    #
    # THE COST OF THAT, stated because it is invisible and was paid for: the login
    # shell re-sources the profile AFTER any PATH the caller exported, so
    # `devbox exec -- bash -c 'export PATH=/my/bin:$PATH; tool --version'` runs the
    # IMAGE's tool, not yours. On 2026-09-04 a session tried to reproduce a CI failure
    # against a newer agent-browser this way and got the pinned 0.26.0 every time --
    # `command -v` resolved to the nvm copy however PATH was set, and the four runs
    # that "reproduced" the bug were the image's own version talking. To probe an
    # alternative version, invoke its ABSOLUTE path (/tmp/x/node_modules/.bin/tool)
    # rather than trying to win a PATH argument with the login shell.
    # devbox_docker answers TWO WORDS when the docker group is not active in
    # this shell yet ("sudo docker", line 63). Quoting that as one command name
    # produces `sudo docker: command not found` -- measured 2026-08-26 running
    # this very function from a plain shell. Every other caller in this file
    # relies on word-splitting an unquoted $d; do it explicitly with an array so
    # the intent survives the next person who "fixes the quoting".
    local -a dk
    read -r -a dk <<<"$d"

    # TWO CALL SHAPES, and `$*` served only one of them. The in-file probes below
    # pass ONE argument that is already shell syntax ("test -f x && git ...") and
    # need it re-parsed verbatim. The CLI (`./run.sh devbox exec -- <argv...>`)
    # passes real argv, and joining that with spaces re-parses it too: on
    # 2026-09-04 `devbox exec -- bash -c 'npm run -s check:ci-shell-lint'` ran
    # `bash -c npm` inside the box -- npm printed its usage, the gate never ran,
    # and the exit code was npm's, not the gate's. A multi-argument call is
    # therefore re-quoted word by word, so the login shell sees exactly the argv
    # the caller typed.
    local cmd
    if [[ $# -eq 1 ]]; then
        cmd="$1"
    else
        cmd="$(printf '%q ' "$@")"
    fi
    "${dk[@]}" "${flags[@]}" "$cid" bash -lc "$cmd"
}

# THE THREE PROBES. Each catches a different way the container can look healthy
# while producing a green over nothing -- and all three present identically, as
# a gate that passes without reading a file.

# 1. Is the repo actually THERE? Verified by CONTENT, never by existence.
#    macOS Docker Desktop (a path outside its file-sharing list) and WSL2 with
#    Docker Desktop integration both AUTO-CREATE an empty directory for a bind
#    mount whose source they cannot see. The container then has the path, and
#    every gate reads an empty tree.
devbox_mount_ok() {
    local root
    root="$(devbox_mount_root)"
    devbox_exec "test -f '$root/run.sh' && git -C '$(devbox_worktree)' rev-parse --git-dir" >/dev/null 2>&1 || {
        log_error "devbox mount is not usable: $root does not contain this repo inside the container"
        log_info "On macOS the path must be inside Docker Desktop's file sharing list; on WSL2 use docker-ce inside the distro, not Desktop integration."
        return 1
    }
}

# 2. Is the exec identity one git will accept? This is the root-exec trap.
devbox_identity_ok() {
    local out
    out="$(devbox_exec "git -C '$(devbox_worktree)' status --porcelain" 2>&1)" || true
    # `[ -n "$(...)" ]`, not `| grep -q`. $out is `git status --porcelain` over the
    # whole worktree, so it is UNBOUNDED, and this file sets no pipefail of its own
    # but INHERITS it from every sourcer (scripts/dev/worktree.sh:12, and
    # .ci/lib/local-common.sh:937,983 via rdc.sh:11). Losing grep -q's race here is
    # silent in the worst direction: the detector stops seeing "dubious ownership"
    # and devbox_identity_ok returns SUCCESS on a broken exec identity.
    if [ -n "$(printf '%s' "$out" | grep 'dubious ownership')" ]; then
        log_error "devbox exec identity is wrong: git refuses the worktree as another user's"
        log_info "Exec as 'vscode' (the entrypoint renumbers it to your uid), never as root."
        return 1
    fi
}

# 3. Is it writable? colima mounts \$HOME read-only unless started with
#    --mount \$HOME:w, and every stamp write and formatter then fails EROFS.
devbox_writable_ok() {
    devbox_exec "touch '$(devbox_worktree)/.ci/cache/.devbox-write-probe' && rm -f '$(devbox_worktree)/.ci/cache/.devbox-write-probe'" >/dev/null 2>&1 || {
        log_error "devbox cannot write into the repo (read-only mount?)"
        log_info "colima needs: colima start --mount \$HOME:w"
        return 1
    }
}

devbox_doctor() {
    local rc=0
    devbox_mount_ok || rc=1
    devbox_identity_ok || rc=1
    devbox_writable_ok || rc=1
    [[ "$rc" -eq 0 ]] && log_info "devbox is usable: mount, identity and writability all verified"
    return "$rc"
}
