// AUTO-GENERATED by scripts/embed-templates.ts — do not edit manually.
// Regenerate with: npx tsx scripts/embed-templates.ts

export interface EmbeddedTemplate {
  name: string;
  description: string;
  files: Record<string, string>;
}

export const TEMPLATES: Record<string, EmbeddedTemplate> = {
  'app-postgres': {
    name: 'app-postgres',
    description: `App + PostgreSQL with auto-generated credentials`,
    files: {
      'app/server.mjs': `import http from 'node:http';

const PORT = 3000;
const HOST = process.env.SERVICE_IP || '0.0.0.0';

const server = http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({
    status: 'ok',
    host: HOST,
    pid: process.pid,
    uptime: Math.floor(process.uptime()),
  }) + '\\n');
});

server.listen(PORT, HOST, () => {
  console.log(\`Server listening on \${HOST}:\${PORT}\`);
});
`,
      'docker-compose.yml': `services:
  app:
    image: node:20-alpine
    container_name: app
    working_dir: /app
    command: sh -c "npm install --production 2>/dev/null; node server.mjs"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@\${DB_IP}:5432/\${POSTGRES_DB}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app
    labels:
      - "rediacc.service_name=app"
      # Auto-route URL: https://{serviceName}.{repoName}.{machineName}.{baseDomain}
      # Example: rdc repo create myrepo -m server-1 → https://app.myrepo.server-1.example.com
      - "rediacc.service_port=3000"

  db:
    image: postgres:16-alpine
    container_name: db
    command: -c listen_addresses=\${DB_IP}
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $\${POSTGRES_USER} -d $\${POSTGRES_DB} -h \${DB_IP}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      - "rediacc.service_name=db"
`,
      'Rediaccfile': `#!/bin/bash

up() {
  mkdir -p data app

  # Auto-generate credentials on first run
  if [[ ! -f .env ]]; then
    local pg_pass
    pg_pass=$(openssl rand -hex 16)
    cat > .env <<ENVEOF
POSTGRES_USER=app
POSTGRES_DB=app
POSTGRES_PASSWORD=\${pg_pass}
ENVEOF
    echo "Generated .env with database credentials"
  fi

  renet compose -- up -d
}

down() {
  renet compose -- down
}

info() {
  renet compose -- ps
}
`,
    },
  },
  'app-postgres-criu': {
    name: 'app-postgres-criu',
    description: `App + PostgreSQL with CRIU checkpoint/restore and IP rebind`,
    files: {
      'app/server.mjs': `import http from 'node:http';

const PORT = 3000;
let host = process.env.SERVICE_IP || '0.0.0.0';

let server = createServer();

// CRIU restore awareness: after checkpoint/restore the assigned SERVICE_IP
// may have changed (e.g. repo was pushed to another machine). Poll for
// changes and rebind the server to the new IP when detected.
setInterval(() => {
  const currentIP = process.env.SERVICE_IP;
  if (currentIP && currentIP !== host) {
    console.log(\`SERVICE_IP changed: \${host} -> \${currentIP}, rebinding...\`);
    server.close(() => {
      host = currentIP;
      server = createServer();
    });
  }
}, 5000);

function createServer() {
  const s = http.createServer((req, res) => {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status: 'ok',
      host,
      pid: process.pid,
      uptime: Math.floor(process.uptime()),
    }) + '\\n');
  });

  s.listen(PORT, host, () => {
    console.log(\`Server listening on \${host}:\${PORT}\`);
  });

  return s;
}
`,
      'docker-compose.yml': `services:
  app:
    image: node:20-alpine
    container_name: app
    working_dir: /app
    command: sh -c "npm install --production 2>/dev/null; node server.mjs"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@\${DB_IP}:5432/\${POSTGRES_DB}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app
    labels:
      - "rediacc.service_name=app"
      # Auto-route URL: https://{serviceName}.{repoName}.{machineName}.{baseDomain}
      # Example: rdc repo create myrepo -m server-1 → https://app.myrepo.server-1.example.com
      - "rediacc.service_port=3000"
      # CRIU: enables checkpoint/restore for live migration.
      # The app must handle SERVICE_IP changes after restore (see server.mjs).
      - "rediacc.checkpoint=true"

  db:
    image: postgres:16-alpine
    container_name: db
    command: -c listen_addresses=\${DB_IP}
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $\${POSTGRES_USER} -d $\${POSTGRES_DB} -h \${DB_IP}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      - "rediacc.service_name=db"
`,
      'Rediaccfile': `#!/bin/bash

up() {
  mkdir -p data app

  # Auto-generate credentials on first run
  if [[ ! -f .env ]]; then
    local pg_pass
    pg_pass=$(openssl rand -hex 16)
    cat > .env <<ENVEOF
POSTGRES_USER=app
POSTGRES_DB=app
POSTGRES_PASSWORD=\${pg_pass}
ENVEOF
    echo "Generated .env with database credentials"
  fi

  renet compose -- up -d
}

down() {
  renet compose -- down
}

info() {
  renet compose -- ps
}
`,
    },
  },
  'multi-project': {
    name: 'multi-project',
    description: `Multiple sub-projects sharing one encrypted volume`,
    files: {
      'project-a/docker-compose.yml': `services:
  project-a-app:
    image: node:20-alpine
    container_name: project-a-app
    working_dir: /app
    command: sh -c "npm install --production 2>/dev/null; node server.mjs"
    depends_on:
      project-a-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@\${PROJECT_A_DB_IP}:5432/\${POSTGRES_DB}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app
    labels:
      - "rediacc.service_name=project-a-app"
      # Custom subdomain: https://{rediacc.domain}.{baseDomain}
      # Example: rediacc.domain=project-a → https://project-a.example.com
      - "rediacc.domain=project-a"
      - "rediacc.service_port=3000"

  project-a-db:
    image: postgres:16-alpine
    container_name: project-a-db
    command: -c listen_addresses=\${PROJECT_A_DB_IP}
    environment:
      - POSTGRES_USER=\${POSTGRES_USER}
      - POSTGRES_DB=\${POSTGRES_DB}
      - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER} -d \${POSTGRES_DB} -h \${PROJECT_A_DB_IP}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      - "rediacc.service_name=project-a-db"
`,
      'project-a/Rediaccfile': `#!/bin/bash

up() {
  mkdir -p db/data

  if [[ ! -f secrets.env ]]; then
    local pg_pass
    pg_pass=$(openssl rand -hex 16)
    cat > secrets.env <<ENVEOF
POSTGRES_USER=project_a
POSTGRES_DB=project_a
POSTGRES_PASSWORD=\${pg_pass}
ENVEOF
    echo "Generated secrets.env for project-a"
  fi

  set -a; source secrets.env; set +a
  renet compose -- up -d
}

down() {
  renet compose -- down
}
`,
      'project-b/docker-compose.yml': `services:
  project-b-app:
    image: redis:7-alpine
    container_name: project-b-app
    command: redis-server --bind \${PROJECT_B_APP_IP} --requirepass \${ADMIN_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h \${PROJECT_B_APP_IP} -a $\${ADMIN_PASSWORD} ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "rediacc.service_name=project-b-app"
`,
      'project-b/Rediaccfile': `#!/bin/bash

up() {
  mkdir -p data

  if [[ ! -f secrets.env ]]; then
    cat > secrets.env <<ENVEOF
ADMIN_PASSWORD=$(openssl rand -hex 16)
ENVEOF
    echo "Generated secrets.env for project-b"
  fi

  set -a; source secrets.env; set +a
  renet compose -- up -d
}

down() {
  renet compose -- down
}
`,
    },
  },
  'single-service': {
    name: 'single-service',
    description: `Single container with Traefik routing and secrets`,
    files: {
      'docker-compose.yml': `services:
  app:
    image: nginx:alpine
    container_name: app
    env_file:
      - secrets.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/etc/nginx/conf.d:ro
      - ./data:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://\${APP_IP}:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      # ── REQUIRED: service identity (always set this) ──
      - "rediacc.service_name=app"

      # ── ROUTING: pick ONE of the three options below ──

      # OPTION 1: Auto-route (simplest, fork-friendly)
      # Renet auto-generates a URL from the service name and repo name:
      #   https://{serviceName}.{repoName}.{machineName}.{baseDomain}
      # Example: rdc repo create myrepo -m server-1
      #   → https://app.myrepo.server-1.example.com
      # Set rediacc.service_port if your app listens on a port other than 80:
      - "rediacc.service_port=80"

      # OPTION 2: Custom subdomain (still simple, NOT fork-friendly)
      # Assigns a short subdomain directly under your baseDomain:
      #   https://{rediacc.domain}.{baseDomain}
      # Example: rediacc.domain=dashboard → https://dashboard.example.com
      # Uncomment the line below and set rediacc.service_port above:
      #- "rediacc.domain=myapp"

      # OPTION 3: Explicit Traefik labels (full control, NOT fork-friendly)
      # Use when you need: custom domain, middleware (upload buffering, auth),
      # TLS passthrough, path-based routing, or multi-domain rules.
      # Remove rediacc.domain (option 2) if using this.
      # Example: custom domain with Let's Encrypt TLS:
      #- "traefik.enable=true"
      #- "traefik.http.routers.myapp.rule=Host(\`myapp.example.com\`)"
      #- "traefik.http.routers.myapp.entrypoints=websecure,websecure-v6"
      #- "traefik.http.routers.myapp.tls.certresolver=letsencrypt"
      #- "traefik.http.services.myapp.loadbalancer.server.url=http://\${APP_IP}:80"
      # Upload buffering (optional, for large file uploads):
      #- "traefik.http.routers.myapp.middlewares=myapp-buffering"
      #- "traefik.http.middlewares.myapp-buffering.buffering.maxRequestBodyBytes=67108864"
`,
      'Rediaccfile': `#!/bin/bash

up() {
  # Load secrets into environment for compose variable substitution
  if [[ -f secrets.env ]]; then
    set -a
    source secrets.env
    set +a
  fi

  renet compose -- up -d
}

down() {
  renet compose -- down
}

info() {
  renet compose -- ps
}

cleanup() {
  # Restart the service and purge logs
  renet compose -- restart
  renet compose -- exec app sh -c 'find /var/log -name "*.log" -exec truncate -s 0 {} \\; 2>/dev/null' || true
}
`,
      'secrets.env': `# Add your secrets here. This file is sourced by the Rediaccfile
# and passed as env_file to docker-compose.
#
# Example:
# API_KEY=your-api-key-here
# ADMIN_PASSWORD=change-me
`,
    },
  },
};
