import {
  CloudOutlined,
  CloudServerOutlined,
  DashboardOutlined,
  DesktopOutlined,
  HistoryOutlined,
  InboxOutlined,
  SettingOutlined,
  ShopOutlined,
  TeamOutlined,
  ThunderboltOutlined,
} from '@/utils/optimizedIcons';
import type { MenuConfig } from './types';
import type { TFunction } from 'i18next';

export const getMenuItems = (t: TFunction): MenuConfig[] => [
  {
    key: '/dashboard',
    icon: <DashboardOutlined />,
    label: t('navigation.dashboard'),
    showInSimple: false,
    'data-testid': 'main-nav-dashboard',
  },
  {
    key: '/organization',
    icon: <TeamOutlined />,
    label: t('navigation.organization'),
    showInSimple: true,
    'data-testid': 'main-nav-organization',
    children: [
      {
        key: '/organization/users',
        label: t('navigation.organizationUsers'),
        showInSimple: true,
        'data-testid': 'sub-nav-organization-users',
      },
      {
        key: '/organization/teams',
        label: t('navigation.organizationTeams'),
        showInSimple: true,
        'data-testid': 'sub-nav-organization-teams',
      },
      {
        key: '/organization/access',
        label: t('navigation.organizationAccess'),
        showInSimple: false,
        'data-testid': 'sub-nav-organization-access',
      },
    ],
  },
  {
    key: '/machines',
    icon: <DesktopOutlined />,
    label: t('navigation.machines'),
    showInSimple: true,
    'data-testid': 'main-nav-machines',
  },
  {
    key: '/settings',
    icon: <SettingOutlined />,
    label: t('navigation.settings'),
    showInSimple: true,
    'data-testid': 'main-nav-settings',
    children: [
      {
        key: '/settings/profile',
        label: t('navigation.settingsProfile'),
        showInSimple: true,
        'data-testid': 'sub-nav-settings-profile',
      },
      {
        key: '/settings/company',
        label: t('navigation.settingsCompany'),
        showInSimple: false,
        featureFlag: 'companySettings',
        'data-testid': 'sub-nav-settings-company',
      },
      {
        key: '/settings/infrastructure',
        label: t('navigation.settingsInfrastructure'),
        showInSimple: false,
        featureFlag: 'regionsInfrastructure',
        'data-testid': 'sub-nav-settings-infrastructure',
      },
    ],
  },
  {
    key: 'divider-1',
    type: 'divider',
    showInSimple: true,
  },
  {
    key: '/storage',
    icon: <CloudOutlined />,
    label: t('navigation.storage'),
    showInSimple: false,
    'data-testid': 'main-nav-storage',
    children: [
      {
        key: '/storage',
        label: t('navigation.storageCloud'),
        showInSimple: false,
        'data-testid': 'sub-nav-storage-cloud',
      },
    ],
  },
  {
    key: '/ceph',
    icon: <CloudServerOutlined />,
    label: t('navigation.ceph'),
    showInSimple: false,
    requiresPlan: ['ENTERPRISE', 'BUSINESS', 'Enterprise', 'Business'],
    featureFlag: 'ceph',
    'data-testid': 'main-nav-ceph',
    children: [
      {
        key: '/ceph/clusters',
        label: t('navigation.cephClusters'),
        showInSimple: false,
        'data-testid': 'sub-nav-ceph-clusters',
      },
      {
        key: '/ceph/pools',
        label: t('navigation.cephPools'),
        showInSimple: false,
        'data-testid': 'sub-nav-ceph-pools',
      },
      {
        key: '/ceph/machines',
        label: t('navigation.cephMachines'),
        showInSimple: false,
        'data-testid': 'sub-nav-ceph-machines',
      },
    ],
  },
  {
    key: '/credentials',
    icon: <InboxOutlined />,
    label: t('navigation.credentials'),
    showInSimple: false,
    'data-testid': 'main-nav-credentials',
  },
  {
    key: '/queue',
    icon: <ThunderboltOutlined />,
    label: t('navigation.queue'),
    showInSimple: false,
    featureFlag: 'queueManagement',
    'data-testid': 'main-nav-queue',
  },
  {
    key: '/audit',
    icon: <HistoryOutlined />,
    label: t('navigation.audit'),
    showInSimple: false,
    featureFlag: 'auditLogs',
    'data-testid': 'main-nav-audit',
  },
  {
    key: '/marketplace',
    icon: <ShopOutlined />,
    label: t('navigation.marketplace'),
    showInSimple: false,
    featureFlag: 'marketplace',
    'data-testid': 'main-nav-marketplace',
  },
];
