services:
  memcached:
    image: memcached:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    command: ["sh", "-c", "exec memcached -l $${SERVICE_IP:-0.0.0.0} -m ${MEMCACHED_MEMORY} -c ${MEMCACHED_MAX_CONN} -t ${MEMCACHED_THREADS} ${MEMCACHED_VERBOSITY:+-v}"]
    healthcheck:
      test: ["CMD", "timeout", "1", "bash", "-c", "</dev/tcp/$${SERVICE_IP:-127.0.0.1}/11211"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
