#!/usr/bin/env tsx
/**
 * check:ci-pr-epic-block -- the PR body's epic block must match the published work.
 *
 * WHY THIS EXISTS. The PR description now carries a generated section, one
 * heading per epic, so a reviewer can see which change belongs to which task and
 * so the review can run once per epic. A generated section nobody checks is
 * worse than none: it looks authoritative while drifting from the work it claims
 * to describe, and the drift is invisible precisely because the text is
 * plausible.
 *
 * WHY IT COMPARES AGAINST A FILE, NOT THE STORE. The worklist store lives in
 * TMPDIR (`/tmp/claude-worklist/<repo-slug>.events.jsonl`), so CI can never read
 * it. `worklist.py --publish` renders a snapshot to `agent/pr/<branch>.md`, which
 * IS in the repo, and this gate diffs the body block against that. The snapshot
 * is therefore the contract: stale snapshot, red gate.
 *
 * SKIPS ARE LOUD. Without a PR number there is no body to check, and that is a
 * legitimate state (a push to main, a local run). It prints why it skipped. A
 * gate that quietly does nothing is the failure this repo names most often.
 *
 * FAILS CLOSED on an unreadable body, matching check-claude-attribution.sh
 * rather than the pr-description gate which fails open. An unreadable body is
 * not evidence that the block is fine.
 *
 * ---- gate ----
 * step: PR epic block matches the published worklist
 * emit: false
 * blocker: BLOCKER: this step has NO `if:` AT ALL -- it runs unconditionally -- so emitting it would ADD `!cancelled() && steps.setup.outcome == 'success'` and change WHEN the gate runs; its `env:` also carries prose comments.
 *     THE ENV REASON IS DEAD AND THIS LINE USED TO STATE IT. Box A1 taught the
 *     binder `env-<KEY>:` on 2026-09-08, so "gate-bind cannot emit an env block"
 *     stopped being true -- and a BLOCKER whose reason has quietly expired is the
 *     exact shape check:ci-suppression-liveness exists to refuse. Corrected to the
 *     real obstacle rather than deleted, because retiring this one is a BEHAVIOUR
 *     change and needs its own box. check-docker-image-freshness.ts was the one of
 *     the six whose ONLY obstacle was env, and it retired the same day.
 * needs: node
 * selftest: true
 * env-GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 * env-PR_HEAD_REF: ${{ github.event.pull_request.head.ref || github.ref_name }}
 * env-PR_NUMBER: ${{ github.event.pull_request.number }}
 * why: The PR body carries a generated epic block; this asserts it matches the
 *      published snapshot, since a generated section nobody checks drifts while
 *      still looking authoritative.
 * ---- end gate ----
 */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

export const BEGIN = '<!-- worklist-epics:begin -->';
export const END = '<!-- worklist-epics:end -->';

/** Text between the markers, or null when the block is absent. */
export const extractBlock = (body: string): string | null => {
  const lines = body.split('\n');
  const b = lines.indexOf(BEGIN);
  const e = lines.indexOf(END);
  if (b < 0 || e < 0 || e < b) return null;
  return lines
    .slice(b + 1, e)
    .join('\n')
    .trim();
};

/** The `PR-TASK: <id>` ids a rendered section declares, in order. */
export const taskIds = (text: string): string[] => {
  const out: string[] = [];
  // Backticked and bare both accepted: the renderer emits backticks, but a human reading the body will reasonably retype it without them.
  const re = /^`?PR-TASK:\s*([0-9a-f]{6,32})`?\s*$/gim;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) out.push(m[1]);
  return out;
};

/** The snapshot without its file-only header. */
export const snapshotSection = (raw: string): string =>
  raw
    .split('\n')
    .filter((l) => !l.startsWith('<!-- generated by worklist.py') && !l.startsWith('# Work in '))
    .join('\n')
    .trim();

/**
 * THE BACKLOG SECTION IS MANDATORY (operator request 2026-10-07). The block
 * renders this PR's own epics and then `### Open system backlog (<N>)`: every
 * open worklist item outside them, the repository's improvement queue, shown on
 * every PR so it stays visible. `wl_epic.render` writes it even when empty
 * (`_none_`), so a block WITHOUT it was hand-edited or rendered by a regressed
 * renderer, and both are refused here. Keep the title in step with
 * `BACKLOG_TITLE` in .claude/hooks/stop/wl_epic.py.
 *
 * N must equal the entries listed under the heading. A count that disagrees
 * with its own list means the list was truncated (or padded) after rendering,
 * and a section that only has to EXIST would still pass with its body deleted.
 */
export const BACKLOG_TITLE = 'Open system backlog';
const BACKLOG_HEAD = /^### Open system backlog \((\d+)\)\s*$/;

/** "" when `text` carries a well-formed backlog section, else why not. */
export const backlogProblem = (text: string): string => {
  const lines = text.split('\n');
  const heads = lines
    .map((l, i) => ({ i, m: BACKLOG_HEAD.exec(l) }))
    .filter((h): h is { i: number; m: RegExpExecArray } => h.m !== null);
  if (heads.length === 0) return `no "### ${BACKLOG_TITLE} (<N>)" heading`;
  if (heads.length > 1) return `${heads.length} "### ${BACKLOG_TITLE}" headings, expected one`;
  const { i, m } = heads[0];
  const declared = Number(m[1]);
  const rest = lines.slice(i + 1);
  const stop = rest.findIndex((l) => /^#{1,6} /.test(l));
  const body = stop < 0 ? rest : rest.slice(0, stop);
  const listed = body.filter((l) => /^- \[.\] `#[0-9a-f]+`/.test(l)).length;
  const none = body.some((l) => l.trim() === '_none_');
  if (declared === 0)
    return none && listed === 0 ? '' : 'declares 0 open items but is not "_none_"';
  if (listed !== declared) return `declares ${declared} open item(s) but lists ${listed}`;
  return '';
};

const say = (msg: string): void => console.log(msg);
const die = (msg: string[]): number => {
  for (const m of msg) console.error(m);
  return 1;
};

const selftest = (): number => {
  let fail = 0;
  const check = (name: string, ok: boolean): void => {
    if (!ok) fail += 1;
    console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${name}`);
  };

  const body = `intro\n${BEGIN}\n## Work\n\n\`PR-TASK: abc123\`\n${END}\ntail`;
  check('extracts the block', extractBlock(body) === '## Work\n\n`PR-TASK: abc123`');
  check('absent block is null', extractBlock('no markers here') === null);
  check('an unterminated block is null', extractBlock(`x\n${BEGIN}\ny`) === null);
  check('reversed markers are null', extractBlock(`${END}\nx\n${BEGIN}`) === null);

  check('reads a backticked id', taskIds('`PR-TASK: abc123`').length === 1);
  check('reads a bare id', taskIds('PR-TASK: abc123').length === 1);
  check(
    'reads several, in order',
    taskIds('`PR-TASK: aaa111`\nx\n`PR-TASK: bbb222`').join(',') === 'aaa111,bbb222'
  );
  // CONTROL: prose mentioning the token is not a declaration. Without this a gate would count any sentence about PR-TASK as a section.
  check(
    'prose mentioning it is not a declaration',
    taskIds('we use PR-TASK: ids for this').length === 0
  );
  check('a too-short id is not accepted', taskIds('`PR-TASK: ab`').length === 0);

  // The backlog section, both directions. A gate with only the firing cases would happily refuse a well-formed block.
  const item = (id: string): string => `- [ ] \`#${id}\` some open work`;
  const backlog = (n: number, rows: string[]): string =>
    `### E\n\n\`PR-TASK: abc123\`\n\n### ${BACKLOG_TITLE} (${n})\n\n_framing line_\n\n${rows.join('\n')}`;
  check(
    'a well-formed backlog passes',
    backlogProblem(backlog(2, [item('aa11'), item('bb22')])) === ''
  );
  check('an empty backlog saying _none_ passes', backlogProblem(backlog(0, ['_none_'])) === '');
  check(
    'an item tagged with another epic still counts',
    backlogProblem(backlog(1, ['- [?] `#cc33` (epic `dd44ee55`) parked'])) === ''
  );
  check(
    'a section followed by another heading counts only its own rows',
    backlogProblem(`${backlog(1, [item('aa11')])}\n### Later\n${item('ff66')}`) === ''
  );
  // CONTROLS: each must fire.
  check(
    'CONTROL: a block with no backlog section fires',
    backlogProblem('### E\n\n`PR-TASK: abc123`\n\n- [x] `#aa11` done').startsWith('no ')
  );
  check(
    'CONTROL: the retired "Not in any epic" heading is not accepted',
    backlogProblem(`### Not in any epic\n\n${item('aa11')}`) !== ''
  );
  check(
    'CONTROL: a count above the list fires (rows deleted after render)',
    backlogProblem(backlog(3, [item('aa11')])).includes('lists 1')
  );
  check(
    'CONTROL: a count below the list fires (rows added by hand)',
    backlogProblem(backlog(1, [item('aa11'), item('bb22')])).includes('lists 2')
  );
  check('CONTROL: N=0 with no "_none_" fires', backlogProblem(backlog(0, [])) !== '');
  check(
    'CONTROL: two backlog headings fire',
    backlogProblem(`${backlog(0, ['_none_'])}\n${backlog(0, ['_none_'])}`).includes('2 ')
  );

  check(
    'snapshot header is stripped',
    snapshotSection('<!-- generated by worklist.py x -->\n# Work in b\n\n### E\n') === '### E'
  );
  return fail === 0 ? 0 : 1;
};

const main = (): number => {
  if (process.argv.slice(2).includes('--selftest')) return selftest();

  const branch =
    process.env.PR_HEAD_REF ||
    process.env.GITHUB_HEAD_REF ||
    (() => {
      try {
        return execFileSync('git', ['branch', '--show-current'], { encoding: 'utf8' }).trim();
      } catch {
        return '';
      }
    })();

  if (!branch || branch === 'main') {
    say(`- skipped: on ${branch || 'an unknown branch'}; the epic block is a PR artefact`);
    return 0;
  }

  const snapPath = path.join(REPO, 'agent', 'pr', `${branch.replace(/\//g, '-')}.md`);
  if (!fs.existsSync(snapPath)) {
    return die([
      `✗ no published snapshot at agent/pr/${branch.replace(/\//g, '-')}.md`,
      '  The PR body block is generated from it, so without it there is nothing to check',
      '  and nothing for a reviewer to read. Run:',
      `      worklist.py --publish <me> ${branch}`,
    ]);
  }

  const section = snapshotSection(fs.readFileSync(snapPath, 'utf8'));
  const ids = taskIds(section);
  if (ids.length === 0) {
    return die([
      `✗ agent/pr/${branch.replace(/\//g, '-')}.md declares no PR-TASK id.`,
      '  A snapshot with no epic cannot drive a per-epic review, and every commit',
      '  gate keys on those ids. Create one: worklist.py --epic <me> new "<title>"',
    ]);
  }

  const snapBacklog = backlogProblem(section);
  if (snapBacklog) {
    return die([
      `✗ agent/pr/${branch.replace(/\//g, '-')}.md: the "${BACKLOG_TITLE}" section is malformed: ${snapBacklog}.`,
      '  Every PR carries the open system backlog; the renderer always writes it, so a',
      '  snapshot without it was hand-edited or rendered by a regressed wl_epic.render.',
      `  Re-publish, do not hand-edit: worklist.py --publish <me> ${branch}`,
    ]);
  }
  const backlogN = BACKLOG_HEAD.exec(
    section.split('\n').find((l) => BACKLOG_HEAD.test(l)) ?? ''
  )?.[1];

  const prNumber = process.env.PR_NUMBER || '';
  if (!prNumber) {
    say(
      `✓ snapshot ok: ${ids.length} epic(s) declared, ${BACKLOG_TITLE} (${backlogN}) present (no PR_NUMBER, body not checked)`
    );
    return 0;
  }

  let body: string;
  try {
    body = execFileSync('gh', ['pr', 'view', prNumber, '--json', 'body', '--jq', '.body // ""'], {
      encoding: 'utf8',
    });
  } catch (err) {
    // FAIL CLOSED: an unreadable body is not evidence the block is fine.
    return die([
      `✗ could not read PR #${prNumber}'s body: ${(err as Error).message.split('\n')[0]}`,
      '  Treating an unreadable body as a pass would make this gate silently blind.',
    ]);
  }

  const block = extractBlock(body);
  if (block === null) {
    return die([
      `✗ PR #${prNumber} has no ${BEGIN} block.`,
      '  A raw `gh pr edit --body` replaces the whole description and drops it.',
      `  Rebuild it: .ci/scripts/pr/sync-epic-block.sh ${prNumber} ${branch}`,
    ]);
  }

  const bodyBacklog = backlogProblem(block);
  if (bodyBacklog) {
    return die([
      `✗ PR #${prNumber}'s epic block: the "${BACKLOG_TITLE}" section is malformed: ${bodyBacklog}.`,
      '  The section is mandatory on every PR; it was dropped or edited by hand.',
      `  Re-sync: .ci/scripts/pr/sync-epic-block.sh ${prNumber} ${branch}`,
    ]);
  }

  const bodyIds = taskIds(block);
  const missing = ids.filter((i) => !bodyIds.includes(i));
  const extra = bodyIds.filter((i) => !ids.includes(i));
  if (missing.length || extra.length) {
    return die([
      `✗ PR #${prNumber}'s epic block disagrees with the published snapshot:`,
      ...missing.map((i) => `    in the snapshot but not the body: ${i}`),
      ...extra.map((i) => `    in the body but not the snapshot: ${i}`),
      '',
      `  Re-sync: .ci/scripts/pr/sync-epic-block.sh ${prNumber} ${branch}`,
    ]);
  }

  say(
    `✓ PR #${prNumber}'s epic block matches the snapshot (${ids.length} epic(s), ${BACKLOG_TITLE} (${backlogN}) present in both)`
  );
  return 0;
};

process.exit(main());
