#!/bin/bash
# CI Elite Service Startup Script
# Starts the elite on-premise docker-compose stack (web) and waits for the
# web health check. Tests the same image customers deploy before changes ship.
#
# Usage:
#   .ci/scripts/infra/ci-start-elite.sh

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONSOLE_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
ELITE_DIR="$CONSOLE_ROOT/private/elite"

echo "Starting Rediacc Elite CI services..."

# =============================================================================
# SOURCE BASE ENVIRONMENT
# =============================================================================
# ci-env.sh sets DOCKER_REGISTRY, TAG, WEB_TAG, SYSTEM_DOMAIN, etc.
# shellcheck source=ci-env.sh
source "$SCRIPT_DIR/ci-env.sh"

# =============================================================================
# CI WEB OVERRIDES
# =============================================================================
export ENABLE_HTTPS="false"
export HTTP_PORT="80"
export HTTPS_PORT="443"

# =============================================================================
# WRITE .ENV FOR ELITE DOCKER COMPOSE
# =============================================================================
echo "Writing .env to $ELITE_DIR..."
{
    echo "# Auto-generated by ci-start-elite.sh — do not edit"
    echo "DOCKER_REGISTRY=${DOCKER_REGISTRY}"
    echo "TAG=${TAG}"
    echo "WEB_TAG=${WEB_TAG}"
    echo "SYSTEM_DOMAIN=${SYSTEM_DOMAIN}"
    echo "HTTP_PORT=${HTTP_PORT}"
    echo "HTTPS_PORT=${HTTPS_PORT}"
    echo "ENABLE_HTTPS=${ENABLE_HTTPS}"
} >"$ELITE_DIR/.env"

# =============================================================================
# START ELITE SERVICES THROUGH THE ENTRY POINT AN OPERATOR ACTUALLY USES
# =============================================================================
# This used to call `docker compose -f ... -f ... up -d` directly, which meant
# the header's claim just above ("Tests the same image customers deploy before
# changes ship") was only half true: it tested the IMAGE, never the PATH.
#
# Everything run.sh does around compose was therefore unverified by CI:
#   - overlay selection (standalone is inferred from an EMPTY INSTANCE_NAME,
#     run.sh:11-15; hardcoding both -f flags bypassed that inference entirely)
#   - bridge-container cleanup before start
#   - certificate auto-generation when ENABLE_HTTPS is on
#   - the image-existence check and pull
# A change breaking any of them would have shipped with this job green.
#
# `.env` is written above, and run.sh only bootstraps one when it is ABSENT
# (run.sh:68), so the concrete TAG/WEB_TAG set here survive and no registry
# version lookup happens.
echo "Starting Elite services via ./run.sh up (the operator entry point)..."
cd "$ELITE_DIR"

./run.sh up

# =============================================================================
# WAIT FOR HEALTH CHECK
# =============================================================================
echo "Waiting for Elite web service to be ready..."

# 180s, not the original 60s: this repo already has two independent, real
# incidents establishing 180s as the floor for "a container becoming healthy
# on a contended host" -- packages/www's tutorial-player release gate
# (measured an 84s cold boot against a then-60s budget) and
# check_tutorial_healthcheck_headroom.py's MIN_BUDGET_SECONDS (born from an
# 18-tutorial recording run that aborted at tutorial 9 because a 150s
# healthcheck budget wasn't enough on a downclocked host). No incident is
# claimed for THIS script specifically -- this is a preventive alignment to
# the repo's own evidenced floor, not a repro.
wait_for_web() {
    local timeout=180
    local elapsed=0
    local interval=2

    echo "  Waiting for Web (nginx)..."
    while [[ $elapsed -lt $timeout ]]; do
        if curl -sf http://localhost/health &>/dev/null; then
            echo "  Web is ready"
            return 0
        fi
        sleep $interval
        elapsed=$((elapsed + interval))
    done
    echo "  Web failed to start within ${timeout}s"
    # A false failure from a merely-busy shared runner and a genuine defect
    # produce the same symptom here; print what a human would otherwise have
    # to SSH in to find out, so the log itself can distinguish them.
    echo "  load average (1m 5m 15m): $(cut -d' ' -f1-3 /proc/loadavg 2>/dev/null || echo unavailable), cores: $(nproc 2>/dev/null || echo unknown)"
    return 1
}

wait_for_web || {
    echo "Elite startup failed: Web"
    # Through run.sh too, so the diagnostic path is the same one an operator
    # would reach for, and so its own compose-file selection is exercised.
    ./run.sh logs web
    exit 1
}

echo ""
echo "All Elite services are ready!"

# Show running containers
echo ""
echo "Running containers:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep -E "(NAME|rediacc)" || true
