#!/bin/bash
# CI Elite Service Startup Script
# Starts the elite on-premise docker-compose stack (web) and waits for the
# web health check. Tests the same image customers deploy before changes ship.
#
# Usage:
#   .ci/scripts/infra/ci-start-elite.sh

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONSOLE_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
ELITE_DIR="$CONSOLE_ROOT/private/elite"

echo "Starting Rediacc Elite CI services..."

# =============================================================================
# SOURCE BASE ENVIRONMENT
# =============================================================================
# ci-env.sh sets DOCKER_REGISTRY, TAG, WEB_TAG, SYSTEM_DOMAIN, etc.
# shellcheck source=ci-env.sh
source "$SCRIPT_DIR/ci-env.sh"

# =============================================================================
# CI WEB OVERRIDES
# =============================================================================
export ENABLE_HTTPS="false"
export HTTP_PORT="80"
export HTTPS_PORT="443"

# =============================================================================
# WRITE .ENV FOR ELITE DOCKER COMPOSE
# =============================================================================
echo "Writing .env to $ELITE_DIR..."
{
    echo "# Auto-generated by ci-start-elite.sh — do not edit"
    echo "DOCKER_REGISTRY=${DOCKER_REGISTRY}"
    echo "TAG=${TAG}"
    echo "WEB_TAG=${WEB_TAG}"
    echo "SYSTEM_DOMAIN=${SYSTEM_DOMAIN}"
    echo "HTTP_PORT=${HTTP_PORT}"
    echo "HTTPS_PORT=${HTTPS_PORT}"
    echo "ENABLE_HTTPS=${ENABLE_HTTPS}"
} >"$ELITE_DIR/.env"

# =============================================================================
# START ELITE SERVICES
# =============================================================================
echo "Starting Elite Docker Compose services..."
cd "$ELITE_DIR"

docker compose -f docker-compose.yml -f docker-compose.standalone.yml up -d

# =============================================================================
# WAIT FOR HEALTH CHECK
# =============================================================================
echo "Waiting for Elite web service to be ready..."

wait_for_web() {
    local timeout=60
    local elapsed=0
    local interval=2

    echo "  Waiting for Web (nginx)..."
    while [[ $elapsed -lt $timeout ]]; do
        if curl -sf http://localhost/health &>/dev/null; then
            echo "  Web is ready"
            return 0
        fi
        sleep $interval
        elapsed=$((elapsed + interval))
    done
    echo "  Web failed to start within ${timeout}s"
    return 1
}

wait_for_web || {
    echo "Elite startup failed: Web"
    docker compose -f docker-compose.yml -f docker-compose.standalone.yml logs web
    exit 1
}

echo ""
echo "All Elite services are ready!"

# Show running containers
echo ""
echo "Running containers:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep -E "(NAME|rediacc)" || true
