name: 'Provision VMs'
description: 'Provision KVM-based VMs for bridge/worker testing'
author: 'Rediacc'

branding:
  icon: 'server'
  color: 'purple'

inputs:
  vm-image-path:
    description: 'Path to pre-built VM image directory (optional - builds if not provided)'
    required: false
    default: ''
  vm-bridge:
    description: 'Bridge VM ID'
    required: false
    default: '1'
  vm-workers:
    description: 'Worker VM IDs (space-separated)'
    required: false
    default: '11 12'
  vm-net-base:
    description: 'VM network base IP'
    required: false
    default: '192.168.111'
  vm-net-offset:
    description: 'VM network offset'
    required: false
    default: '0'
  bridge-env-output:
    description: 'Path to output bridge environment file'
    required: false
    default: ''
  vm-os:
    description: 'VM OS image (ubuntu-24.04, debian-12, fedora-43, opensuse-15.6)'
    required: false
    default: 'ubuntu-24.04'

outputs:
  kvm-available:
    description: 'Whether KVM is available'
    value: ${{ steps.kvm-check.outputs.kvm_available }}
  bridge-ip:
    description: 'Bridge VM IP address'
    value: ${{ steps.provision.outputs.bridge_ip }}
  worker-ips:
    description: 'Worker VM IP addresses (comma-separated)'
    value: ${{ steps.provision.outputs.worker_ips }}
  vm-image-path:
    description: 'Path to VM image used'
    value: ${{ steps.provision.outputs.vm_image_path }}
  machine-user:
    description: 'Username for VM SSH access'
    value: ${{ steps.provision.outputs.machine_user }}
  machine-password:
    description: 'Password for VM SSH access'
    value: ${{ steps.provision.outputs.machine_password }}

runs:
  using: 'composite'
  steps:
    # Step 1: Check KVM availability
    - name: Check KVM Availability
      id: kvm-check
      shell: bash
      run: |
        if [ -e /dev/kvm ]; then
          echo "kvm_available=true" >> $GITHUB_OUTPUT
          echo "KVM is available"
        else
          echo "kvm_available=false" >> $GITHUB_OUTPUT
          echo "::warning::KVM is NOT available - VM provisioning will be skipped"
        fi

    # Step 2: Create bridge environment file (optional, before provisioning)
    - name: Create Bridge Test Environment
      if: steps.kvm-check.outputs.kvm_available == 'true' && inputs.bridge-env-output != ''
      shell: bash
      env:
        VM_NET_BASE: ${{ inputs.vm-net-base }}
        VM_NET_OFFSET: ${{ inputs.vm-net-offset }}
        VM_BRIDGE: ${{ inputs.vm-bridge }}
        VM_WORKERS: ${{ inputs.vm-workers }}
      run: |
        ${{ github.action_path }}/../../../.ci/scripts/env/create-bridge-env.sh \
          --output "${{ inputs.bridge-env-output }}" \
          --vm-net-base "$VM_NET_BASE" \
          --vm-net-offset "$VM_NET_OFFSET" \
          --vm-bridge "$VM_BRIDGE" \
          --vm-workers "$VM_WORKERS"

    # Step 4: Provision VMs (setup host, build image, run ops up)
    - name: Provision VMs
      id: provision
      if: steps.kvm-check.outputs.kvm_available == 'true'
      shell: bash
      env:
        VM_NET_BASE: ${{ inputs.vm-net-base }}
        VM_NET_OFFSET: ${{ inputs.vm-net-offset }}
        VM_BRIDGE: ${{ inputs.vm-bridge }}
        VM_WORKERS: ${{ inputs.vm-workers }}
        VM_CEPH_NODES: ''
        VM_OS: ${{ inputs.vm-os }}
        VM_IMAGE_DIR: ${{ inputs.vm-image-path || format('{0}/vm-image', runner.temp) }}
      run: ${{ github.action_path }}/../../../.ci/scripts/infra/ci-provision-start.sh
