#!/usr/bin/env tsx
/**
 * check:ci-pr-epic-block -- the PR body's epic block must match the published work.
 *
 * WHY THIS EXISTS. The PR description now carries a generated section, one
 * heading per epic, so a reviewer can see which change belongs to which task and
 * so the review can run once per epic. A generated section nobody checks is
 * worse than none: it looks authoritative while drifting from the work it claims
 * to describe, and the drift is invisible precisely because the text is
 * plausible.
 *
 * WHY IT COMPARES AGAINST A FILE, NOT THE STORE. The worklist store lives in
 * TMPDIR (`/tmp/claude-worklist/<repo-slug>.events.jsonl`), so CI can never read
 * it. `worklist.py --publish` renders a snapshot to `agent/pr/<branch>.md`, which
 * IS in the repo, and this gate diffs the body block against that. The snapshot
 * is therefore the contract: stale snapshot, red gate.
 *
 * SKIPS ARE LOUD. Without a PR number there is no body to check, and that is a
 * legitimate state (a push to main, a local run). It prints why it skipped. A
 * gate that quietly does nothing is the failure this repo names most often.
 *
 * FAILS CLOSED on an unreadable body, matching check-claude-attribution.sh
 * rather than check-pr-description.sh which fails open. An unreadable body is
 * not evidence that the block is fine.
 */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

export const BEGIN = '<!-- worklist-epics:begin -->';
export const END = '<!-- worklist-epics:end -->';

/** Text between the markers, or null when the block is absent. */
export const extractBlock = (body: string): string | null => {
  const lines = body.split('\n');
  const b = lines.indexOf(BEGIN);
  const e = lines.indexOf(END);
  if (b < 0 || e < 0 || e < b) return null;
  return lines
    .slice(b + 1, e)
    .join('\n')
    .trim();
};

/** The `PR-TASK: <id>` ids a rendered section declares, in order. */
export const taskIds = (text: string): string[] => {
  const out: string[] = [];
  // Backticked and bare both accepted: the renderer emits backticks, but a human
  // reading the body will reasonably retype it without them.
  const re = /^`?PR-TASK:\s*([0-9a-f]{6,32})`?\s*$/gim;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) out.push(m[1]);
  return out;
};

/** The snapshot without its file-only header. */
export const snapshotSection = (raw: string): string =>
  raw
    .split('\n')
    .filter((l) => !l.startsWith('<!-- generated by worklist.py') && !l.startsWith('# Work in '))
    .join('\n')
    .trim();

const say = (msg: string): void => console.log(msg);
const die = (msg: string[]): number => {
  for (const m of msg) console.error(m);
  return 1;
};

const selftest = (): number => {
  let fail = 0;
  const check = (name: string, ok: boolean): void => {
    if (!ok) fail += 1;
    console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${name}`);
  };

  const body = `intro\n${BEGIN}\n## Work\n\n\`PR-TASK: abc123\`\n${END}\ntail`;
  check('extracts the block', extractBlock(body) === '## Work\n\n`PR-TASK: abc123`');
  check('absent block is null', extractBlock('no markers here') === null);
  check('an unterminated block is null', extractBlock(`x\n${BEGIN}\ny`) === null);
  check('reversed markers are null', extractBlock(`${END}\nx\n${BEGIN}`) === null);

  check('reads a backticked id', taskIds('`PR-TASK: abc123`').length === 1);
  check('reads a bare id', taskIds('PR-TASK: abc123').length === 1);
  check(
    'reads several, in order',
    taskIds('`PR-TASK: aaa111`\nx\n`PR-TASK: bbb222`').join(',') === 'aaa111,bbb222'
  );
  // CONTROL: prose mentioning the token is not a declaration. Without this a
  // gate would count any sentence about PR-TASK as a section.
  check(
    'prose mentioning it is not a declaration',
    taskIds('we use PR-TASK: ids for this').length === 0
  );
  check('a too-short id is not accepted', taskIds('`PR-TASK: ab`').length === 0);

  check(
    'snapshot header is stripped',
    snapshotSection('<!-- generated by worklist.py x -->\n# Work in b\n\n### E\n') === '### E'
  );
  return fail === 0 ? 0 : 1;
};

const main = (): number => {
  if (process.argv.slice(2).includes('--selftest')) return selftest();

  const branch =
    process.env.PR_HEAD_REF ||
    process.env.GITHUB_HEAD_REF ||
    (() => {
      try {
        return execFileSync('git', ['branch', '--show-current'], { encoding: 'utf8' }).trim();
      } catch {
        return '';
      }
    })();

  if (!branch || branch === 'main') {
    say(`- skipped: on ${branch || 'an unknown branch'}; the epic block is a PR artefact`);
    return 0;
  }

  const snapPath = path.join(REPO, 'agent', 'pr', `${branch.replace(/\//g, '-')}.md`);
  if (!fs.existsSync(snapPath)) {
    return die([
      `✗ no published snapshot at agent/pr/${branch.replace(/\//g, '-')}.md`,
      '  The PR body block is generated from it, so without it there is nothing to check',
      '  and nothing for a reviewer to read. Run:',
      `      worklist.py --publish <me> ${branch}`,
    ]);
  }

  const section = snapshotSection(fs.readFileSync(snapPath, 'utf8'));
  const ids = taskIds(section);
  if (ids.length === 0) {
    return die([
      `✗ agent/pr/${branch.replace(/\//g, '-')}.md declares no PR-TASK id.`,
      '  A snapshot with no epic cannot drive a per-epic review, and every commit',
      '  gate keys on those ids. Create one: worklist.py --epic <me> new "<title>"',
    ]);
  }

  const prNumber = process.env.PR_NUMBER || '';
  if (!prNumber) {
    say(`✓ snapshot ok: ${ids.length} epic(s) declared (no PR_NUMBER, body not checked)`);
    return 0;
  }

  let body: string;
  try {
    body = execFileSync('gh', ['pr', 'view', prNumber, '--json', 'body', '--jq', '.body // ""'], {
      encoding: 'utf8',
    });
  } catch (err) {
    // FAIL CLOSED: an unreadable body is not evidence the block is fine.
    return die([
      `✗ could not read PR #${prNumber}'s body: ${(err as Error).message.split('\n')[0]}`,
      '  Treating an unreadable body as a pass would make this gate silently blind.',
    ]);
  }

  const block = extractBlock(body);
  if (block === null) {
    return die([
      `✗ PR #${prNumber} has no ${BEGIN} block.`,
      '  A raw `gh pr edit --body` replaces the whole description and drops it.',
      `  Rebuild it: .ci/scripts/pr/sync-epic-block.sh ${prNumber} ${branch}`,
    ]);
  }

  const bodyIds = taskIds(block);
  const missing = ids.filter((i) => !bodyIds.includes(i));
  const extra = bodyIds.filter((i) => !ids.includes(i));
  if (missing.length || extra.length) {
    return die([
      `✗ PR #${prNumber}'s epic block disagrees with the published snapshot:`,
      ...missing.map((i) => `    in the snapshot but not the body: ${i}`),
      ...extra.map((i) => `    in the body but not the snapshot: ${i}`),
      '',
      `  Re-sync: .ci/scripts/pr/sync-epic-block.sh ${prNumber} ${branch}`,
    ]);
  }

  say(`✓ PR #${prNumber}'s epic block matches the snapshot (${ids.length} epic(s))`);
  return 0;
};

process.exit(main());
