#!/usr/bin/env node
/**
 * Generate the third-party attribution artifacts from the embed lockfile.
 *
 * private/renet/embed-assets.lock.json is the single source of truth for every
 * binary renet embeds and conveys. Two attribution artifacts are derived from it:
 *
 *   private/renet/pkg/embed/credits_data.go   (renet-side, `renet credits`)
 *   packages/cli/src/data/third-party-credits.json  (CLI-side, `rdc credits`)
 *
 * WHY GENERATED: these two were maintained by hand and had already drifted. The
 * three CSI sidecars carried a generic "run as a host process (spec 09 CSI
 * driver)" licence line in the CLI mirror while credits.go carried three distinct
 * and more accurate ones. check-embed-credits.ts could not see it because it only
 * ever compared the VERSION field against the Dockerfile ARG, never the licence
 * text between the two inventories. One source removes the failure mode instead
 * of adding a third comparison to keep in step.
 *
 * The CLI mirror also carries entries that are NOT embedded binaries (the Node.js
 * runtime, the bundled npm deps). Those are preserved from the existing file
 * untouched; only kind === "embedded-binary" entries are regenerated.
 *
 * Usage:
 *   npx tsx scripts/generate-embed-credits.ts           # write the artifacts
 *   npx tsx scripts/generate-embed-credits.ts --check   # fail if they are stale
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { GREEN, NC, RED, YELLOW } from './utils/console.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CONSOLE_ROOT = path.resolve(__dirname, '..');

export const LOCKFILE = path.join(CONSOLE_ROOT, 'private/renet/embed-assets.lock.json');
// Output paths. The env overrides exist so the gate test can point the staleness
// check at fixtures instead of mutating the tracked artifacts.
export const CREDITS_GO =
  process.env.EMBED_CREDITS_GO_FILE ??
  path.join(CONSOLE_ROOT, 'private/renet/pkg/embed/credits_data.go');
export const CREDITS_JSON =
  process.env.EMBED_CREDITS_JSON_FILE ??
  path.join(CONSOLE_ROOT, 'packages/cli/src/data/third-party-credits.json');

export interface LockComponent {
  name: string;
  version: string;
  class: string;
  goConst: string;
  spdx: string;
  license: string;
  upstreamSourceUrl: string;
  plannedMirrorUrl: string;
  notes?: string;
}

export interface Lockfile {
  gplWrittenOffer: string;
  components: Record<string, LockComponent>;
}

/** Components in a stable, declaration-independent order. */
function orderedComponents(lock: Lockfile): Array<[string, LockComponent]> {
  return Object.entries(lock.components).sort(([a], [b]) => a.localeCompare(b));
}

/** Escape a string for a Go double-quoted literal. */
function goString(s: string): string {
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\t/g, '\\t')}"`;
}

export function renderGo(lock: Lockfile): string {
  const lines: string[] = [];
  lines.push('// Code generated by scripts/generate-embed-credits.ts. DO NOT EDIT.');
  lines.push('//');
  lines.push('// Source of truth: private/renet/embed-assets.lock.json');
  lines.push('// Regenerate with: npx tsx scripts/generate-embed-credits.ts');
  lines.push('');
  lines.push('package embed');
  lines.push('');
  lines.push('// credits is the attribution inventory for the embedded binaries.');
  lines.push('var credits = []Credit{');
  for (const [, c] of orderedComponents(lock)) {
    lines.push('\t{');
    lines.push(`\t\tAsset:             ${c.goConst},`);
    lines.push(`\t\tName:              ${goString(c.name)},`);
    lines.push(`\t\tVersion:           ${goString(c.version)},`);
    lines.push(`\t\tSPDX:              ${goString(c.spdx)},`);
    lines.push(`\t\tLicense:           ${goString(c.license)},`);
    lines.push(`\t\tUpstreamSourceURL: ${goString(c.upstreamSourceUrl)},`);
    lines.push(`\t\tPlannedMirrorURL:  ${goString(c.plannedMirrorUrl)},`);
    if (c.notes) lines.push(`\t\tNotes:             ${goString(c.notes)},`);
    lines.push('\t},');
  }
  lines.push('}');
  lines.push('');
  lines.push('// GPLWrittenOffer is the source-availability statement conveyed alongside the');
  lines.push('// GPL binaries.');
  lines.push(`const GPLWrittenOffer = ${goString(lock.gplWrittenOffer)}`);
  lines.push('');
  return lines.join('\n');
}

export function renderJson(lock: Lockfile): string {
  const existing = JSON.parse(fs.readFileSync(CREDITS_JSON, 'utf-8')) as {
    _comment: string;
    gplWrittenOffer: string;
    components: Array<Record<string, unknown>>;
  };

  // Preserve non-embedded entries (Node.js runtime, bundled npm deps) verbatim
  // and in place; only the embedded-binary set is derived from the lockfile.
  const passthrough = existing.components.filter((c) => c.kind !== 'embedded-binary');

  const embedded = orderedComponents(lock).map(([, c]) => {
    const entry: Record<string, unknown> = {
      kind: 'embedded-binary',
      asset: c.goConst.replace(/^Asset/, '').toLowerCase(),
      name: c.name,
      version: c.version,
      spdx: c.spdx,
      license: c.license,
      upstreamSourceUrl: c.upstreamSourceUrl,
      plannedMirrorUrl: c.plannedMirrorUrl,
    };
    if (c.notes) entry.notes = c.notes;
    return entry;
  });

  return `${JSON.stringify(
    {
      _comment: existing._comment,
      gplWrittenOffer: lock.gplWrittenOffer,
      components: [...embedded, ...passthrough],
    },
    null,
    2
  )}\n`;
}

export function generatedArtifacts(lock: Lockfile): Array<[string, string]> {
  return [
    [CREDITS_GO, renderGo(lock)],
    [CREDITS_JSON, renderJson(lock)],
  ];
}

function main(): void {
  const check = process.argv.includes('--check');
  const lock = JSON.parse(fs.readFileSync(LOCKFILE, 'utf-8')) as Lockfile;

  const artifacts = generatedArtifacts(lock);

  const stale: string[] = [];
  for (const [file, want] of artifacts) {
    const have = fs.existsSync(file) ? fs.readFileSync(file, 'utf-8') : '';
    if (have === want) continue;
    if (check) {
      stale.push(path.relative(CONSOLE_ROOT, file));
    } else {
      fs.writeFileSync(file, want);
      console.log(`${GREEN}✓${NC} wrote ${path.relative(CONSOLE_ROOT, file)}`);
    }
  }

  if (!check) return;

  if (stale.length > 0) {
    console.error(`${RED}✗ generated attribution artifacts are stale:${NC}`);
    for (const f of stale) console.error(`  ${f}`);
    console.error(
      `\n${YELLOW}Regenerate with: npx tsx scripts/generate-embed-credits.ts${NC}\n` +
        'These are derived from private/renet/embed-assets.lock.json; edit the lockfile, not the artifacts.'
    );
    process.exit(1);
  }
  console.log(`${GREEN}✓ attribution artifacts match the embed lockfile${NC}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
