#!/usr/bin/env bash
# Sync the worklist epic block into a PR description.
#
# Reads the published snapshot (agent/pr/<branch>.md, written by
# `worklist.py --publish`) and rebuilds a delimited block in the PR body. The
# store itself lives in TMPDIR and is unreadable from CI, which is exactly why
# the snapshot exists.
#
# THE MARKER PAIR IS DISTINCT ON PURPOSE. Three writers already append a block
# at the end of this repo's PR bodies: refresh-pr-body.sh's `pushed-head`,
# submodule-prs.sh's `autopilot-submodule-prs`, and whatever a human typed.
# submodule-prs.sh warns in its own header that sharing markers with
# refresh-pr-body.sh is fatal, because that hook rewrites the WHOLE body on every
# push and anything inside its markers is destroyed on the next one. Each writer
# strips only its own markers, so all three survive; the price is that block
# ORDER flips depending on who ran last, and nothing may depend on position.
#
# Idiom copied verbatim from .ci/scripts/autopilot/submodule-prs.sh: exact-line
# equality on the markers (not a substring match), `next` on both so the markers
# themselves are dropped, and the block REBUILT rather than appended to.
set -euo pipefail

BEGIN='<!-- worklist-epics:begin -->'
END='<!-- worklist-epics:end -->'

usage() {
    cat >&2 <<'MSG'
usage: sync-epic-block.sh <pr-number> <branch> [--dry-run]

Rebuilds the worklist epic block in a PR description from
agent/pr/<branch>.md. With --dry-run the new body goes to stdout and
nothing is written.
MSG
    exit 2
}

[[ $# -lt 2 ]] && usage
PR="$1"; BRANCH="$2"; DRY="${3:-}"
REPO_ROOT="$(git rev-parse --show-toplevel)"
SNAP="$REPO_ROOT/agent/pr/${BRANCH//\//-}.md"

if [[ ! -f "$SNAP" ]]; then
    echo "✗ no snapshot at ${SNAP#"$REPO_ROOT"/}" >&2
    echo "  run: worklist.py --publish <me> $BRANCH" >&2
    exit 1
fi

# The snapshot's own generated header is for readers of the file, not the PR.
SECTION="$(sed '1{/^<!-- generated by worklist.py/d;}; /^# Work in /d' "$SNAP")"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

if [[ "$DRY" == "--dry-run" ]]; then
    : >"$work/body-old.md"
else
    gh pr view "$PR" --json body --jq '.body // ""' >"$work/body-old.md"
fi

awk -v b="$BEGIN" -v e="$END" '
    $0 == b { skip = 1; next }
    $0 == e { skip = 0; next }
    !skip   { print }
' "$work/body-old.md" >"$work/body-stripped.md"

{
    cat "$work/body-stripped.md"
    printf '\n%s\n' "$BEGIN"
    printf '## Work in this PR\n\n'
    printf '%s\n' "$SECTION"
    printf '%s\n' "$END"
} >"$work/body-new.md"

if [[ "$DRY" == "--dry-run" ]]; then
    cat "$work/body-new.md"
    exit 0
fi

gh pr edit "$PR" --body-file "$work/body-new.md"
echo "✓ epic block synced into PR #$PR from ${SNAP#"$REPO_ROOT"/}"
