/**
 * Reads packages/cli/templates/ and generates src/templates/embedded.generated.ts
 * with all template file contents embedded as string literals.
 *
 * Run: npx tsx scripts/embed-templates.ts
 */

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = join(__dirname, '..', 'templates');
const OUTPUT_FILE = join(__dirname, '..', 'src', 'templates', 'embedded.generated.ts');

interface TemplateMetadata {
  description: string;
}

function collectFiles(dir: string, base: string): Record<string, string> {
  const files: Record<string, string> = {};

  for (const entry of readdirSync(dir)) {
    // Skip template.json metadata, .git, node_modules
    if (entry === 'template.json' || entry === '.git' || entry === 'node_modules') continue;

    const fullPath = join(dir, entry);
    const relPath = relative(base, fullPath).replace(/\\/g, '/');
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      Object.assign(files, collectFiles(fullPath, base));
    } else {
      files[relPath] = readFileSync(fullPath, 'utf-8');
    }
  }

  return files;
}

function escapeString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function main() {
  const templateDirs = readdirSync(TEMPLATES_DIR).filter((name) => {
    const fullPath = join(TEMPLATES_DIR, name);
    return statSync(fullPath).isDirectory() && !name.startsWith('.');
  });

  const lines: string[] = [
    '// AUTO-GENERATED by scripts/embed-templates.ts — do not edit manually.',
    '// Regenerate with: npx tsx scripts/embed-templates.ts',
    '',
    'export interface EmbeddedTemplate {',
    '  name: string;',
    '  description: string;',
    '  files: Record<string, string>;',
    '}',
    '',
    'export const TEMPLATES: Record<string, EmbeddedTemplate> = {',
  ];

  for (const name of templateDirs.sort()) {
    const templateDir = join(TEMPLATES_DIR, name);

    // Read metadata
    const metadataPath = join(templateDir, 'template.json');
    let description = name;
    if (existsSync(metadataPath)) {
      const meta: TemplateMetadata = JSON.parse(readFileSync(metadataPath, 'utf-8'));
      description = meta.description;
    }

    // Collect all files
    const files = collectFiles(templateDir, templateDir);

    lines.push(`  '${name}': {`);
    lines.push(`    name: '${name}',`);
    lines.push(`    description: \`${escapeString(description)}\`,`);
    lines.push('    files: {');

    for (const [filePath, content] of Object.entries(files).sort(([a], [b]) =>
      a.localeCompare(b)
    )) {
      lines.push(`      '${filePath}': \`${escapeString(content)}\`,`);
    }

    lines.push('    },');
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf-8');

  console.log(`✓ Generated ${OUTPUT_FILE}`);
  console.log(`  Templates: ${templateDirs.length}`);
  const totalFiles = templateDirs.reduce((sum, name) => {
    return (
      sum + Object.keys(collectFiles(join(TEMPLATES_DIR, name), join(TEMPLATES_DIR, name))).length
    );
  }, 0);
  console.log(`  Files: ${totalFiles}`);
}

main();
