#!/usr/bin/env node
/**
 * For every (locale, tutorial) pair where `src/content/docs/<lang>/*.md(x)`
 * embeds a `.cast`, asserts that the five files the runtime player loads
 * exist on disk:
 *
 *   public/assets/tutorials/video/<lang>/<castKey>.mp4
 *   public/assets/tutorials/video/<lang>/<castKey>.<lang>.poster.jpg
 *   public/assets/tutorials/video/<lang>/<castKey>.<lang>.vtt
 *   public/assets/tutorials/video/<lang>/<castKey>.<lang>.chapters.vtt
 *   public/assets/tutorials/video/<lang>/<castKey>.<lang>.words.json
 *
 * The URL shape is set by remark-tutorial-embed.ts; the player at
 * TutorialVideoPlayer.tsx loads them via the data-* attributes on the
 * .tutorial-video-container div. Missing any of the five = black-frame player
 * + 404s in the network panel for the affected locale.
 *
 * This script exists because check-tutorial-parity.ts is intentionally
 * en-only (validates the source-of-truth chain: cast ↔ storyboard ↔ EN
 * transcript ↔ EN MDX) and therefore misses translation drift in the
 * downstream asset rollout. See rediacc/console#497 for the diagnosis.
 *
 * Exit 1 on any miss; the gate is intentionally strict because the assets
 * are deterministically generated by tutorials:tts:generate +
 * tutorials:derive-fallback-timeline + generate-tutorial-video.ts. Nothing
 * about "translation in progress" excuses a shipped doc page that
 * black-frames a player.
 */

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const wwwRoot = path.resolve(scriptDir, '..');
const contentDocsDir = path.join(wwwRoot, 'src', 'content', 'docs');
const videoAssetsDir = path.join(wwwRoot, 'public', 'assets', 'tutorials', 'video');

interface Miss {
  locale: string;
  castKey: string;
  docFile: string;
  missing: string[];
}

function listLocales(): string[] {
  if (!fs.existsSync(contentDocsDir)) return [];
  return fs
    .readdirSync(contentDocsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

function walkMarkdown(root: string): string[] {
  const out: string[] = [];
  if (!fs.existsSync(root)) return out;
  const stack: string[] = [root];
  while (stack.length) {
    const dir = stack.pop()!;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
      } else if (entry.isFile() && (entry.name.endsWith('.md') || entry.name.endsWith('.mdx'))) {
        out.push(full);
      }
    }
  }
  return out;
}

// Matches the same shape remark-tutorial-embed.ts:20 recognizes — markdown
// image-syntax pointing at a .cast file. Keep this regex in sync if the
// embed plugin ever broadens what it accepts.
const CAST_REF_RE = /!\[[^\]]*\]\(([^)]+\.cast)\)/g;

function extractCastKeys(mdContent: string): string[] {
  const keys = new Set<string>();
  for (const m of mdContent.matchAll(CAST_REF_RE)) {
    const url = m[1];
    keys.add(path.basename(url, '.cast'));
  }
  return [...keys];
}

function expectedFiles(locale: string, castKey: string): string[] {
  const base = path.join(videoAssetsDir, locale, castKey);
  return [
    `${base}.mp4`,
    `${base}.${locale}.poster.jpg`,
    `${base}.${locale}.vtt`,
    `${base}.${locale}.chapters.vtt`,
    `${base}.${locale}.words.json`,
  ];
}

function checkLocaleTutorial(locale: string, castKey: string, docFile: string): Miss | null {
  const missing = expectedFiles(locale, castKey).filter((p) => !fs.existsSync(p));
  if (missing.length === 0) return null;
  return {
    locale,
    castKey,
    docFile: path.relative(wwwRoot, docFile),
    missing: missing.map((p) => path.relative(wwwRoot, p)),
  };
}

function main(): number {
  const misses: Miss[] = [];
  let pairsChecked = 0;
  const localesSeen = new Set<string>();
  const tutorialsSeen = new Set<string>();

  for (const locale of listLocales()) {
    const localeDir = path.join(contentDocsDir, locale);
    for (const mdPath of walkMarkdown(localeDir)) {
      const content = fs.readFileSync(mdPath, 'utf8');
      const castKeys = extractCastKeys(content);
      for (const castKey of castKeys) {
        pairsChecked++;
        localesSeen.add(locale);
        tutorialsSeen.add(castKey);
        const miss = checkLocaleTutorial(locale, castKey, mdPath);
        if (miss) misses.push(miss);
      }
    }
  }

  if (misses.length === 0) {
    console.log(
      `✓ Locale tutorial assets OK for ${localesSeen.size} locales × ${tutorialsSeen.size} tutorials (${pairsChecked} pairs)`
    );
    return 0;
  }

  const byLocale = new Map<string, Miss[]>();
  for (const m of misses) {
    if (!byLocale.has(m.locale)) byLocale.set(m.locale, []);
    byLocale.get(m.locale)!.push(m);
  }
  console.error(
    `✗ Locale tutorial assets missing (${misses.length} broken pairs across ${byLocale.size} locales)\n`
  );
  for (const [locale, list] of [...byLocale.entries()].sort()) {
    console.error(`[${locale}]`);
    for (const m of list) {
      console.error(`  ${m.docFile} → ${m.castKey}`);
      for (const f of m.missing) console.error(`    missing: ${f}`);
    }
    console.error('');
  }
  console.error(`Generate via:  npm run tutorials:tts:generate -- --lang <code>  (TTS locales)`);
  console.error(
    `              npm run tutorials:derive-fallback-timeline -- --lang <code>  (ar/et/tr)`
  );
  console.error(
    `              npx tsx packages/www/scripts/generate-tutorial-video.ts --cast <slug> --lang <code>`
  );
  return 1;
}

process.exit(main());
