#!/bin/bash
# Sync GitHub variables into private/account/.env
#
# Pulls readable variables from GitHub (org + repo level) and updates the local
# .env file. Secrets are write-only in GitHub and cannot be pulled -- those are
# updated by rotate-secrets.sh during rotation.
#
# Usage:
#   ./scripts/dev/sync-env.sh [--dry-run]
#
# Requires: gh (GitHub CLI, authenticated)
#
# What gets synced (variables, readable):
#   ROOT_EMAIL, AWS_SES_REGION, AWS_SES_FROM, SELLER_* (repo + org level)
#
# What does NOT get synced (secrets, write-only):
#   AWS_SES_ACCESS_KEY_ID, AWS_SES_SECRET_ACCESS_KEY, TURNSTILE_SECRET_KEY,
#   STRIPE_*, ED25519_*, X25519_*, API_KEY, JWT_SECRET
#   These are updated by: ./scripts/dev/rotate-secrets.sh (during rotation)
#   Or generated by: ./run.sh account reset
#
# Exit codes:
#   0 - Success
#   1 - Error

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$ROOT_DIR/.ci/scripts/lib/common.sh"
source "$SCRIPT_DIR/lib/cf-auth.sh"

GITHUB_ORG="rediacc"
GITHUB_REPO="rediacc/console"
ENV_FILE="$ROOT_DIR/private/account/.env"

# =============================================================================
# ARGUMENT PARSING
# =============================================================================

DRY_RUN=false
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        *)
            log_error "Unknown argument: $arg"
            log_error "Usage: sync-env.sh [--dry-run]"
            exit 1
            ;;
    esac
done

# =============================================================================
# PREREQUISITES
# =============================================================================

require_cmd gh

if [[ ! -f "$ENV_FILE" ]]; then
    log_error "$ENV_FILE does not exist"
    log_error "Run './run.sh account reset' to generate it first"
    exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
    log_error "GitHub CLI not authenticated (run 'gh auth login')"
    exit 1
fi

# =============================================================================
# MAIN
# =============================================================================

log_step "Syncing GitHub variables to $ENV_FILE"
if [[ "$DRY_RUN" == "true" ]]; then
    log_warn "DRY-RUN mode: no changes will be written"
fi

# GitHub variables that map to .env keys used by the account server.
# Format: "github_var_name:env_key_name" (same name if colon omitted)
# Source: cd-deploy-worker.yml lines 147-161, env.ts schema
ENV_KEYS=(
    # Repo-level variables
    "ROOT_EMAIL"
    "SELLER_NAME"
    "SELLER_VAT_NUMBER"
    "SELLER_REGISTRATION_NUMBER"
    "SELLER_ADDRESS_LINE1"
    "SELLER_ADDRESS_LINE2"
    "SELLER_CITY"
    "SELLER_POSTAL_CODE"
    "SELLER_COUNTRY"
    "SELLER_EMAIL"
)

ORG_KEYS=(
    # Org-level variables
    "AWS_SES_REGION"
    "AWS_SES_FROM"
)

updated=0
skipped=0

# Fetch repo-level variables
log_step "Fetching repo variables..."
repo_vars=$(gh variable list --repo "$GITHUB_REPO" --json name,value 2>/dev/null || echo "[]")

for key in "${ENV_KEYS[@]}"; do
    value=$(echo "$repo_vars" | jq -r --arg k "$key" '.[] | select(.name == $k) | .value // empty')
    if [[ -z "$value" ]]; then
        skipped=$((skipped + 1))
        continue
    fi
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "  [DRY-RUN] $key=$value"
    else
        update_env_file "$ENV_FILE" "$key" "$value"
    fi
    updated=$((updated + 1))
done

# Fetch org-level variables
log_step "Fetching org variables..."
org_vars=$(gh variable list --org "$GITHUB_ORG" --json name,value 2>/dev/null || echo "[]")

for key in "${ORG_KEYS[@]}"; do
    value=$(echo "$org_vars" | jq -r --arg k "$key" '.[] | select(.name == $k) | .value // empty')
    if [[ -z "$value" ]]; then
        skipped=$((skipped + 1))
        continue
    fi
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "  [DRY-RUN] $key=$value"
    else
        update_env_file "$ENV_FILE" "$key" "$value"
    fi
    updated=$((updated + 1))
done

log_info "Synced $updated variable(s), skipped $skipped"
if [[ "$DRY_RUN" != "true" && "$updated" -gt 0 ]]; then
    log_info "Updated: $ENV_FILE"
fi
