#!/bin/bash
# Create E2E test environment file
# Usage: create-e2e-env.sh --api-url <url> --output <path> [--base-url <url>]
#
# Options:
#   --api-url    Backend API URL (tunnel URL)
#   --output     Output .env file path
#   --base-url   Frontend base URL (default: http://localhost:3000/console/)
#
# Example:
#   .ci/scripts/env/create-e2e-env.sh --api-url https://tunnel.com --output packages/e2e/.env

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

# Parse arguments
parse_args "$@"

API_URL="${ARG_API_URL:-}"
OUTPUT="${ARG_OUTPUT:-}"
BASE_URL="${ARG_BASE_URL:-http://localhost:3000/console/}"

# Validate required arguments
if [[ -z "$API_URL" ]] || [[ -z "$OUTPUT" ]]; then
    log_error "Usage: create-e2e-env.sh --api-url <url> --output <path> [--base-url <url>]"
    exit 1
fi

# Create output directory if needed
OUTPUT_DIR="$(dirname "$OUTPUT")"
mkdir -p "$OUTPUT_DIR"

log_step "Creating E2E test environment: $OUTPUT"

# E2E tests run against Vite dev server (source code)
# Vite proxies /api/* to the tunnel URL (backend)
# User registration happens dynamically in globalSetup
cat > "$OUTPUT" << EOF
# E2E Test Environment
# Generated by .ci/scripts/env/create-e2e-env.sh

E2E_BASE_URL=$BASE_URL
VITE_API_URL=$API_URL
CI=true
EOF

log_info "Created E2E test environment: $OUTPUT"
