#!/bin/bash
# Create CLI local mode E2E test environment file
# Usage: create-cli-local-env.sh --output <path> [options]
#
# Generates a .env file for CLI local mode E2E tests with VM network configuration.
#
# Options:
#   --output        Output .env file path (required)
#   --vm-net-base   VM network base (default: 192.168.111)
#   --vm-workers    Worker VM IDs, space-separated (default: "11")
#   --ssh-user      SSH user (default: root)
#   --ssh-key       Path to SSH private key (default: ~/.ssh/id_ed25519)
#
# Example:
#   .ci/scripts/env/create-cli-local-env.sh --output packages/cli/tests/.env
#   .ci/scripts/env/create-cli-local-env.sh --output .env --vm-workers "11 12"

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

# Parse arguments
parse_args "$@"

OUTPUT="${ARG_OUTPUT:-}"
VM_NET_BASE="${ARG_VM_NET_BASE:-192.168.111}"
VM_WORKERS="${ARG_VM_WORKERS:-11}"
SSH_USER="${ARG_SSH_USER:-root}"
SSH_KEY="${ARG_SSH_KEY:-~/.ssh/id_ed25519}"

# Validate required arguments
if [[ -z "$OUTPUT" ]]; then
    log_error "Usage: create-cli-local-env.sh --output <path>"
    exit 1
fi

# Create output directory if needed
mkdir -p "$(dirname "$OUTPUT")"

log_step "Creating CLI local E2E test environment: $OUTPUT"

# Compute VM IPs from worker IDs
read -ra WORKER_IDS <<< "$VM_WORKERS"
VM1_IP="${VM_NET_BASE}.${WORKER_IDS[0]}"
VM2_IP=""
[[ ${#WORKER_IDS[@]} -ge 2 ]] && VM2_IP="${VM_NET_BASE}.${WORKER_IDS[1]}"

cat > "$OUTPUT" << EOF
# CLI Local Mode E2E Test Environment
# Generated by .ci/scripts/env/create-cli-local-env.sh

E2E_VM1_IP=$VM1_IP
E2E_VM2_IP=$VM2_IP
E2E_SSH_USER=$SSH_USER
E2E_SSH_KEY=$SSH_KEY
PLAYWRIGHT_SKIP_GLOBAL_SETUP=true
CI=true
EOF

log_info "Created CLI local E2E env: $OUTPUT"

# Display contents for debugging
if [[ "${DEBUG:-false}" == "true" ]]; then
    echo ""
    echo "Contents:"
    cat "$OUTPUT"
fi
