#!/bin/bash
# Create bridge test environment file
# Usage: create-bridge-env.sh --output <path> [options]
#
# Generates a .env file for bridge integration tests with VM network configuration.
#
# Options:
#   --output        Output .env file path (required)
#   --vm-net-base   VM network base (default: 192.168.111)
#   --vm-net-offset VM network offset (default: 0)
#   --vm-bridge     Bridge VM ID (default: 1)
#   --vm-workers    Worker VM IDs, space-separated (default: "11 12")
#   --vm-ceph-nodes Ceph node VM IDs, space-separated (default: "21 22 23" if --ceph)
#   --ceph          Enable Ceph mode (no workers, only Ceph nodes)
#   --timeout       Bridge timeout in ms (default: BRIDGE_TIMEOUT env or 120000)
#   --renet-path    Path to renet binary (default: RENET_BINARY_PATH env)
#   --vm-image      OS image name (default: VM_IMAGE env or "ubuntu-24.04")
#
# Example:
#   .ci/scripts/env/create-bridge-env.sh --output packages/bridge-tests/.env
#   .ci/scripts/env/create-bridge-env.sh --output .env --vm-workers "11 12 13"
#   .ci/scripts/env/create-bridge-env.sh --ceph --output packages/bridge-tests/.env

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

# Parse arguments
parse_args "$@"

OUTPUT="${ARG_OUTPUT:-}"
VM_NET_BASE="${ARG_VM_NET_BASE:-192.168.111}"
VM_NET_OFFSET="${ARG_VM_NET_OFFSET:-0}"
VM_BRIDGE="${ARG_VM_BRIDGE:-1}"
TIMEOUT="${ARG_TIMEOUT:-${BRIDGE_TIMEOUT:-120000}}"
RENET_PATH="${ARG_RENET_PATH:-${RENET_BINARY_PATH:-}}"

# Handle Ceph mode
# Note: PROVISION_CEPH_CLUSTER is now inferred from VM_CEPH_NODES (if set, Ceph provisioning is enabled)
CEPH_MODE="${ARG_CEPH:-false}"
if [[ "$CEPH_MODE" == "true" ]]; then
    VM_WORKERS=""
    VM_CEPH_NODES="${ARG_VM_CEPH_NODES:-21 22 23}"
else
    VM_WORKERS="${ARG_VM_WORKERS:-11 12}"
    VM_CEPH_NODES="${ARG_VM_CEPH_NODES:-}"
fi

# VM image (e.g., "ubuntu-24.04", "debian-12")
VM_IMAGE_VALUE="${ARG_VM_IMAGE:-${VM_IMAGE:-ubuntu-24.04}}"

# Validate required arguments
if [[ -z "$OUTPUT" ]]; then
    log_error "Usage: create-bridge-env.sh --output <path> [options]"
    exit 1
fi

# Create output directory if needed
OUTPUT_DIR="$(dirname "$OUTPUT")"
mkdir -p "$OUTPUT_DIR"

log_step "Creating bridge test environment: $OUTPUT"

cat >"$OUTPUT" <<EOF
# Bridge Test Environment
# Generated by .ci/scripts/env/create-bridge-env.sh
# Note: PROVISION_CEPH_CLUSTER is inferred from VM_CEPH_NODES (if set, Ceph provisioning is enabled)
# Note: Renet auto-detects data directory via CI env var (uses \$RUNNER_TEMP/renet in CI)

VM_NET_BASE=$VM_NET_BASE
VM_NET_OFFSET=$VM_NET_OFFSET
VM_BRIDGE=$VM_BRIDGE
VM_WORKERS=$VM_WORKERS
VM_CEPH_NODES=$VM_CEPH_NODES
VM_IMAGE=$VM_IMAGE_VALUE
CEPH_MODE=$CEPH_MODE
BRIDGE_TIMEOUT=$TIMEOUT
RENET_BINARY_PATH=$RENET_PATH
CI=${CI:-true}
NODE_ENV=test
EOF

log_info "Created bridge test environment: $OUTPUT"

# Display contents for debugging
if [[ "${DEBUG:-false}" == "true" ]]; then
    echo ""
    echo "Contents:"
    cat "$OUTPUT"
fi
