#!/bin/bash
# Create CLI test environment file
# Usage: create-cli-env.sh --api-url <url> --output <path> [--email <email>] [--password <pass>] [--minimal]
#
# Options:
#   --api-url    API URL (required unless --minimal)
#   --output     Output .env file path (required)
#   --email      Test user email (default: admin@rediacc.io)
#   --password   Test user password (default: admin)
#   --minimal    Create minimal env for non-API tests (e.g., VS Code detection)
#   --timeout    CLI timeout in ms (default: 30000)
#
# Example:
#   .ci/scripts/env/create-cli-env.sh --api-url https://tunnel.com/api --output packages/cli/tests/.env

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

# Parse arguments
parse_args "$@"

API_URL="${ARG_API_URL:-}"
OUTPUT="${ARG_OUTPUT:-}"
EMAIL="${ARG_EMAIL:-admin@rediacc.io}"
PASSWORD="${ARG_PASSWORD:-admin}"
TIMEOUT="${ARG_TIMEOUT:-30000}"
MINIMAL="${ARG_MINIMAL:-false}"

# Validate required arguments
if [[ -z "$OUTPUT" ]]; then
    log_error "Usage: create-cli-env.sh --api-url <url> --output <path> [options]"
    exit 1
fi

if [[ "$MINIMAL" != "true" ]] && [[ -z "$API_URL" ]]; then
    log_error "--api-url is required unless --minimal is specified"
    exit 1
fi

# Create output directory if needed
OUTPUT_DIR="$(dirname "$OUTPUT")"
mkdir -p "$OUTPUT_DIR"

log_step "Creating CLI test environment: $OUTPUT"

if [[ "$MINIMAL" == "true" ]]; then
    # Minimal config for tests that don't need API
    cat > "$OUTPUT" << EOF
# CLI Test Environment (Minimal)
# Generated by .ci/scripts/env/create-cli-env.sh

CLI_API_URL=http://localhost/api
CLI_MASTER_EMAIL=test@example.com
CLI_MASTER_PASSWORD=testpass
CLI_TIMEOUT=$TIMEOUT
CI=true
EOF
else
    # Full config for integration tests
    cat > "$OUTPUT" << EOF
# CLI Test Environment
# Generated by .ci/scripts/env/create-cli-env.sh

CLI_API_URL=$API_URL
CLI_MASTER_EMAIL=$EMAIL
CLI_MASTER_PASSWORD=$PASSWORD
CLI_TIMEOUT=$TIMEOUT
CI=true
DEBUG=false
EOF
fi

log_info "Created CLI test environment: $OUTPUT"
