services:
  redis:
    image: redis:7-alpine
    container_name: ${CONTAINER_NAME}
    restart: always
    command: ["sh", "-c", "exec redis-server --bind $${SERVICE_IP:-0.0.0.0} --requirepass ${REDIS_PASSWORD} --maxmemory ${REDIS_MAXMEMORY} --maxmemory-policy ${REDIS_MAXMEMORY_POLICY}"]
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h $${SERVICE_IP:-127.0.0.1} --raw incr ping"]
      interval: 10s
      timeout: 5s
      retries: 5
